/* DQ-35 数据留存（10-02，执行模型）：pump 迁移池在 2025-11-16～2025-11-30 的成交；只存不分析；由 build_grad_sql.py 生成 */
WITH
bn(base) AS (
    /* 币安现货全部 746 个基础资产名（Probe L 母表 u_trade，公开信息）；留出按 sha256(baseAsset) 首字节 mod 5 == 0 在下面计算 */
    SELECT base FROM (VALUES
        ('0G'),
        ('1000CAT'),
        ('1000CHEEMS'),
        ('1000SATS'),
        ('1INCH'),
        ('1MBABYDOGE'),
        ('2Z'),
        ('A'),
        ('A2Z'),
        ('AAOIB'),
        ('AAPLB'),
        ('AAVE'),
        ('ACA'),
        ('ACE'),
        ('ACH'),
        ('ACM'),
        ('ACT'),
        ('ACX'),
        ('ADA'),
        ('ADX'),
        ('AE'),
        ('AERGO'),
        ('AERO'),
        ('AEUR'),
        ('AEVO'),
        ('AGI'),
        ('AGIX'),
        ('AGLD'),
        ('AI'),
        ('AIGENSYN'),
        ('AION'),
        ('AIXBT'),
        ('AKRO'),
        ('ALCX'),
        ('ALGO'),
        ('ALICE'),
        ('ALLO'),
        ('ALPACA'),
        ('ALPHA'),
        ('ALPINE'),
        ('ALT'),
        ('AMATB'),
        ('AMB'),
        ('AMDB'),
        ('AMP'),
        ('AMZNB'),
        ('ANC'),
        ('ANIME'),
        ('ANKR'),
        ('ANT'),
        ('ANY'),
        ('APE'),
        ('API3'),
        ('APPC'),
        ('APT'),
        ('AR'),
        ('ARB'),
        ('ARDR'),
        ('ARK'),
        ('ARKM'),
        ('ARMB'),
        ('ARN'),
        ('ARPA'),
        ('ASR'),
        ('AST'),
        ('ASTER'),
        ('ASTR'),
        ('AT'),
        ('ATA'),
        ('ATM'),
        ('ATOM'),
        ('AUCTION'),
        ('AUD'),
        ('AUDIO'),
        ('AUTO'),
        ('AVA'),
        ('AVAX'),
        ('AVGOB'),
        ('AVNT'),
        ('AWE'),
        ('AXL'),
        ('AXS'),
        ('AXTIB'),
        ('BABAB'),
        ('BABY'),
        ('BADGER'),
        ('BAKE'),
        ('BAL'),
        ('BANANA'),
        ('BANANAS31'),
        ('BAND'),
        ('BANK'),
        ('BAR'),
        ('BARD'),
        ('BAT'),
        ('BB'),
        ('BCC'),
        ('BCD'),
        ('BCH'),
        ('BCHA'),
        ('BCHABC'),
        ('BCHSV'),
        ('BCN'),
        ('BCPT'),
        ('BDOT'),
        ('BEAM'),
        ('BEAMX'),
        ('BEAR'),
        ('BEB'),
        ('BEL'),
        ('BERA'),
        ('BETA'),
        ('BETH'),
        ('BFUSD'),
        ('BGBP'),
        ('BICO'),
        ('BIFI'),
        ('BIGTIME'),
        ('BIO'),
        ('BKRW'),
        ('BLUR'),
        ('BLZ'),
        ('BMT'),
        ('BNB'),
        ('BNSOL'),
        ('BNT'),
        ('BNX'),
        ('BOME'),
        ('BOND'),
        ('BONK'),
        ('BOT'),
        ('BQX'),
        ('BRD'),
        ('BREV'),
        ('BROCCOLI714'),
        ('BSW'),
        ('BTC'),
        ('BTCB'),
        ('BTCST'),
        ('BTG'),
        ('BTS'),
        ('BTT'),
        ('BTTC'),
        ('BULL'),
        ('BURGER'),
        ('BUSD'),
        ('BZRX'),
        ('C'),
        ('C98'),
        ('CAKE'),
        ('CATI'),
        ('CBRSB'),
        ('CDT'),
        ('CELO'),
        ('CELR'),
        ('CETUS'),
        ('CFG'),
        ('CFX'),
        ('CGPT'),
        ('CHAT'),
        ('CHESS'),
        ('CHIP'),
        ('CHR'),
        ('CHZ'),
        ('CITY'),
        ('CKB'),
        ('CLOAK'),
        ('CLV'),
        ('CMT'),
        ('CND'),
        ('COCOS'),
        ('COINB'),
        ('COMBO'),
        ('COMP'),
        ('COOKIE'),
        ('COS'),
        ('COTI'),
        ('COVER'),
        ('COW'),
        ('CRCLB'),
        ('CREAM'),
        ('CRV'),
        ('CRWVB'),
        ('CTK'),
        ('CTSI'),
        ('CTXC'),
        ('CVC'),
        ('CVP'),
        ('CVX'),
        ('CYBER'),
        ('D'),
        ('DAI'),
        ('DAR'),
        ('DASH'),
        ('DATA'),
        ('DCR'),
        ('DEGO'),
        ('DELLB'),
        ('DENT'),
        ('DEXE'),
        ('DF'),
        ('DGB'),
        ('DGD'),
        ('DIA'),
        ('DLT'),
        ('DNT'),
        ('DOCK'),
        ('DODO'),
        ('DOGE'),
        ('DOGS'),
        ('DOLO'),
        ('DOT'),
        ('DRAMB'),
        ('DREP'),
        ('DUSK'),
        ('DYDX'),
        ('DYM'),
        ('EASY'),
        ('EDEN'),
        ('EDO'),
        ('EDU'),
        ('EGLD'),
        ('EIGEN'),
        ('ELF'),
        ('ENA'),
        ('ENG'),
        ('ENJ'),
        ('ENS'),
        ('ENSO'),
        ('EOS'),
        ('EPIC'),
        ('EPS'),
        ('EPX'),
        ('ERA'),
        ('ERD'),
        ('ERN'),
        ('ESP'),
        ('ETC'),
        ('ETH'),
        ('ETHFI'),
        ('EUL'),
        ('EUR'),
        ('EURI'),
        ('EVX'),
        ('EWYB'),
        ('EZ'),
        ('F'),
        ('FARM'),
        ('FDUSD'),
        ('FET'),
        ('FF'),
        ('FIDA'),
        ('FIL'),
        ('FIO'),
        ('FIRO'),
        ('FIS'),
        ('FLM'),
        ('FLNCB'),
        ('FLOKI'),
        ('FLOW'),
        ('FLUX'),
        ('FOGO'),
        ('FOR'),
        ('FORM'),
        ('FORTH'),
        ('FRAX'),
        ('FRONT'),
        ('FTM'),
        ('FTT'),
        ('FUEL'),
        ('FUN'),
        ('FXS'),
        ('G'),
        ('GAL'),
        ('GALA'),
        ('GAS'),
        ('GBP'),
        ('GENIUS'),
        ('GFT'),
        ('GHST'),
        ('GIGGLE'),
        ('GLM'),
        ('GLMR'),
        ('GLWB'),
        ('GMT'),
        ('GMX'),
        ('GNO'),
        ('GNS'),
        ('GNT'),
        ('GO'),
        ('GOOGLB'),
        ('GPS'),
        ('GRAM'),
        ('GRS'),
        ('GRT'),
        ('GSB'),
        ('GTC'),
        ('GTO'),
        ('GUN'),
        ('GVT'),
        ('GXS'),
        ('HAEDAL'),
        ('HARD'),
        ('HBAR'),
        ('HC'),
        ('HEGIC'),
        ('HEI'),
        ('HEMI'),
        ('HFT'),
        ('HIFI'),
        ('HIGH'),
        ('HIVE'),
        ('HMSTR'),
        ('HNT'),
        ('HOLO'),
        ('HOME'),
        ('HOODB'),
        ('HOOK'),
        ('HOT'),
        ('HSR'),
        ('HUMA'),
        ('HYPER'),
        ('IBMB'),
        ('ICN'),
        ('ICP'),
        ('ICX'),
        ('ID'),
        ('IDEX'),
        ('ILV'),
        ('IMX'),
        ('INIT'),
        ('INJ'),
        ('INS'),
        ('INTCB'),
        ('INTWB'),
        ('IO'),
        ('IOST'),
        ('IOTA'),
        ('IOTX'),
        ('IQ'),
        ('IRIS'),
        ('JASMY'),
        ('JOE'),
        ('JST'),
        ('JTO'),
        ('JUP'),
        ('JUV'),
        ('KAIA'),
        ('KAITO'),
        ('KAT'),
        ('KAVA'),
        ('KDA'),
        ('KEEP'),
        ('KERNEL'),
        ('KEY'),
        ('KGST'),
        ('KITE'),
        ('KLAY'),
        ('KMD'),
        ('KMNO'),
        ('KNC'),
        ('KORUB'),
        ('KP3R'),
        ('KSM'),
        ('LA'),
        ('LAYER'),
        ('LAZIO'),
        ('LDO'),
        ('LEND'),
        ('LEVER'),
        ('LINA'),
        ('LINEA'),
        ('LINK'),
        ('LISTA'),
        ('LIT'),
        ('LITEB'),
        ('LOKA'),
        ('LOOM'),
        ('LPT'),
        ('LQTY'),
        ('LRC'),
        ('LSK'),
        ('LTC'),
        ('LTO'),
        ('LUMIA'),
        ('LUN'),
        ('LUNA'),
        ('LUNC'),
        ('MAGIC'),
        ('MANA'),
        ('MANTA'),
        ('MANTRA'),
        ('MASK'),
        ('MATIC'),
        ('MAV'),
        ('MBL'),
        ('MBOX'),
        ('MC'),
        ('MCO'),
        ('MDA'),
        ('MDT'),
        ('MDX'),
        ('ME'),
        ('MEGA'),
        ('MEME'),
        ('MET'),
        ('METAB'),
        ('METIS'),
        ('MFT'),
        ('MINA'),
        ('MIR'),
        ('MIRA'),
        ('MITH'),
        ('MITO'),
        ('MKR'),
        ('MLN'),
        ('MMT'),
        ('MOB'),
        ('MOD'),
        ('MORPHO'),
        ('MOVE'),
        ('MOVR'),
        ('MRVLB'),
        ('MSFTB'),
        ('MSTRB'),
        ('MTH'),
        ('MTL'),
        ('MUB'),
        ('MUBARAK'),
        ('MULTI'),
        ('MUUB'),
        ('MVLLB'),
        ('NANO'),
        ('NAS'),
        ('NAV'),
        ('NBISB'),
        ('NBS'),
        ('NBT'),
        ('NCASH'),
        ('NEAR'),
        ('NEBL'),
        ('NEIRO'),
        ('NEO'),
        ('NEWT'),
        ('NEXO'),
        ('NFP'),
        ('NIGHT'),
        ('NIL'),
        ('NKN'),
        ('NMR'),
        ('NOKB'),
        ('NOM'),
        ('NOT'),
        ('NPXS'),
        ('NTRN'),
        ('NU'),
        ('NULS'),
        ('NVDAB'),
        ('NXPC'),
        ('NXS'),
        ('OAX'),
        ('OCEAN'),
        ('OG'),
        ('OGN'),
        ('OM'),
        ('OMG'),
        ('OMNI'),
        ('ONDO'),
        ('ONE'),
        ('ONG'),
        ('ONT'),
        ('OOKI'),
        ('OP'),
        ('OPEN'),
        ('OPG'),
        ('OPN'),
        ('ORCA'),
        ('ORCLB'),
        ('ORDI'),
        ('ORN'),
        ('OSMO'),
        ('OST'),
        ('OXT'),
        ('PARTI'),
        ('PAX'),
        ('PAXG'),
        ('PDA'),
        ('PENDLE'),
        ('PENGU'),
        ('PEOPLE'),
        ('PEPE'),
        ('PERL'),
        ('PERP'),
        ('PHA'),
        ('PHB'),
        ('PHX'),
        ('PIVX'),
        ('PIXEL'),
        ('PLA'),
        ('PLTRB'),
        ('PLUME'),
        ('PNT'),
        ('PNUT'),
        ('POA'),
        ('POE'),
        ('POL'),
        ('POLS'),
        ('POLY'),
        ('POLYX'),
        ('POND'),
        ('PORTAL'),
        ('PORTO'),
        ('POWR'),
        ('PPT'),
        ('PROM'),
        ('PROS'),
        ('PROVE'),
        ('PSG'),
        ('PUMP'),
        ('PUNDIX'),
        ('PYPLB'),
        ('PYR'),
        ('PYTH'),
        ('QCOMB'),
        ('QI'),
        ('QKC'),
        ('QLC'),
        ('QNT'),
        ('QNTB'),
        ('QQQB'),
        ('QSP'),
        ('QTUM'),
        ('QUICK'),
        ('RAD'),
        ('RAMP'),
        ('RARE'),
        ('RAY'),
        ('RCN'),
        ('RDN'),
        ('RDNT'),
        ('RE'),
        ('RED'),
        ('REEF'),
        ('REI'),
        ('REN'),
        ('RENBTC'),
        ('RENDER'),
        ('REP'),
        ('REQ'),
        ('RESOLV'),
        ('REZ'),
        ('RGT'),
        ('RIF'),
        ('RKLBB'),
        ('RLC'),
        ('RLUSD'),
        ('RNDR'),
        ('ROBO'),
        ('RONIN'),
        ('ROSE'),
        ('RPL'),
        ('RPX'),
        ('RSR'),
        ('RUNE'),
        ('RVN'),
        ('S'),
        ('SAGA'),
        ('SAHARA'),
        ('SALT'),
        ('SAND'),
        ('SANTOS'),
        ('SAPIEN'),
        ('SC'),
        ('SCR'),
        ('SCRT'),
        ('SEI'),
        ('SENT'),
        ('SFP'),
        ('SHELL'),
        ('SHIB'),
        ('SIGN'),
        ('SKHYB'),
        ('SKL'),
        ('SKY'),
        ('SLF'),
        ('SLP'),
        ('SMHB'),
        ('SNDKB'),
        ('SNGLS'),
        ('SNM'),
        ('SNT'),
        ('SNX'),
        ('SNXXB'),
        ('SOL'),
        ('SOLV'),
        ('SOMI'),
        ('SOPH'),
        ('SOXLB'),
        ('SOXSB'),
        ('SPARTA'),
        ('SPCXB'),
        ('SPELL'),
        ('SPK'),
        ('SPYB'),
        ('SRM'),
        ('SSV'),
        ('STEEM'),
        ('STG'),
        ('STMX'),
        ('STO'),
        ('STORJ'),
        ('STORM'),
        ('STPT'),
        ('STRAT'),
        ('STRAX'),
        ('STRK'),
        ('STX'),
        ('SUB'),
        ('SUI'),
        ('SUN'),
        ('SUPER'),
        ('SUSD'),
        ('SUSHI'),
        ('SWRV'),
        ('SXP'),
        ('SXT'),
        ('SYN'),
        ('SYRUP'),
        ('SYS'),
        ('T'),
        ('TAO'),
        ('TCT'),
        ('TFUEL'),
        ('THE'),
        ('THETA'),
        ('TIA'),
        ('TKO'),
        ('TLM'),
        ('TNB'),
        ('TNSR'),
        ('TNT'),
        ('TOMO'),
        ('TON'),
        ('TORN'),
        ('TOWNS'),
        ('TQQQB'),
        ('TRB'),
        ('TREE'),
        ('TRIBE'),
        ('TRIG'),
        ('TROY'),
        ('TRU'),
        ('TRUMP'),
        ('TRX'),
        ('TSLAB'),
        ('TSMB'),
        ('TST'),
        ('TURBO'),
        ('TURTLE'),
        ('TUSD'),
        ('TUSDB'),
        ('TUT'),
        ('TVK'),
        ('TWT'),
        ('U'),
        ('UFT'),
        ('UMA'),
        ('UNFI'),
        ('UNI'),
        ('USD1'),
        ('USDC'),
        ('USDE'),
        ('USDP'),
        ('USDS'),
        ('USDSB'),
        ('USDT'),
        ('UST'),
        ('USTC'),
        ('USUAL'),
        ('UTK'),
        ('VANA'),
        ('VANRY'),
        ('VELODROME'),
        ('VEN'),
        ('VET'),
        ('VGX'),
        ('VIA'),
        ('VIB'),
        ('VIBE'),
        ('VIC'),
        ('VIDT'),
        ('VIRTUAL'),
        ('VITE'),
        ('VOXEL'),
        ('VTHO'),
        ('W'),
        ('WABI'),
        ('WAL'),
        ('WAN'),
        ('WAVES'),
        ('WAXP'),
        ('WBETH'),
        ('WBTC'),
        ('WCT'),
        ('WDCB'),
        ('WIF'),
        ('WIN'),
        ('WING'),
        ('WINGS'),
        ('WLD'),
        ('WLFI'),
        ('WNXM'),
        ('WOO'),
        ('WPR'),
        ('WRX'),
        ('WTC'),
        ('XAI'),
        ('XAUT'),
        ('XEC'),
        ('XEM'),
        ('XLM'),
        ('XMR'),
        ('XNO'),
        ('XPL'),
        ('XRP'),
        ('XTZ'),
        ('XUSD'),
        ('XVG'),
        ('XVS'),
        ('XZC'),
        ('YB'),
        ('YFI'),
        ('YFII'),
        ('YGG'),
        ('YOYO'),
        ('ZAMA'),
        ('ZBT'),
        ('ZEC'),
        ('ZEN'),
        ('ZIL'),
        ('ZK'),
        ('ZKC'),
        ('ZKP'),
        ('ZRO'),
        ('ZRX'),
        ('币安人生')
    ) AS v(base)
),
excl AS (
    SELECT base FROM bn
    WHERE mod(from_big_endian_32(from_hex('000000' || substr(to_hex(sha256(to_utf8(base))), 1, 2))), 5) = 0
),
cp AS (
    /* 由 pump 程序在迁移交易里创建、池序号为 0 的 PumpSwap 池（DQ-1M 的 by_pump 口径；迁移事件表 2025 年为空） */
    SELECT pool, min(evt_block_time) AS created_at, max(base_mint) AS mint, max(quote_mint) AS quote_mint,
           max(base_mint_decimals) AS bd, max(quote_mint_decimals) AS qd
    FROM pumpdotfun_solana.pump_amm_evt_createpoolevent
    WHERE evt_block_date BETWEEN DATE '2025-05-19' AND DATE '2025-11-30'
      AND evt_outer_executing_account = '6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P'
      AND index = 0
    GROUP BY 1
),
sym AS (
    SELECT mint, arbitrary(symbol) AS symbol
    FROM pumpdotfun_solana.pump_evt_createevent
    WHERE evt_block_date BETWEEN DATE '2025-02-18' AND DATE '2025-11-30'
      AND mint IN (SELECT mint FROM cp)
    GROUP BY 1
),
pools AS (
    SELECT c.pool, c.mint, c.quote_mint, c.created_at, c.bd, c.qd
    FROM cp c
    LEFT JOIN sym s ON s.mint = c.mint
    WHERE c.created_at >= TIMESTAMP '2025-11-16 00:00:00' - INTERVAL '180' DAY
      AND c.created_at < TIMESTAMP '2025-11-30 00:00:00' + INTERVAL '1' DAY
      AND NOT (c.created_at >= TIMESTAMP '2026-06-15 00:00:00' AND c.created_at < TIMESTAMP '2026-07-13 00:00:00')
      AND s.symbol IS NOT NULL
      AND upper(trim(replace(s.symbol, '$', ''))) NOT IN (SELECT base FROM excl)
),
ev AS (
    SELECT pool, evt_block_time AS ts, evt_block_slot AS slot, evt_tx_index AS txi,
           COALESCE(evt_inner_instruction_index, 0) AS iix, 'B' AS side, "user" AS usr,
           CAST(pool_quote_token_reserves AS DOUBLE) AS q0,
           CAST(pool_base_token_reserves AS DOUBLE) AS b0,
           CAST(quote_amount_in AS DOUBLE) AS q_amt,
           CAST(base_amount_out AS DOUBLE) AS b_amt,
           CAST(user_quote_amount_in AS DOUBLE) AS q_user,
           CAST(pool_quote_token_reserves AS DOUBLE) + CAST(quote_amount_in AS DOUBLE)
             - COALESCE(CAST(protocol_fee AS DOUBLE), 0) - COALESCE(CAST(coin_creator_fee AS DOUBLE), 0) AS q1,
           CAST(pool_base_token_reserves AS DOUBLE) - CAST(base_amount_out AS DOUBLE) AS b1
    FROM pumpdotfun_solana.pump_amm_evt_buyevent
    WHERE evt_block_date BETWEEN DATE '2025-11-16' AND DATE '2025-11-30'
      AND pool IN (SELECT pool FROM pools)
    UNION ALL
    SELECT pool, evt_block_time AS ts, evt_block_slot AS slot, evt_tx_index AS txi,
           COALESCE(evt_inner_instruction_index, 0) AS iix, 'S' AS side, "user" AS usr,
           CAST(pool_quote_token_reserves AS DOUBLE) AS q0,
           CAST(pool_base_token_reserves AS DOUBLE) AS b0,
           CAST(quote_amount_out AS DOUBLE) AS q_amt,
           CAST(base_amount_in AS DOUBLE) AS b_amt,
           CAST(user_quote_amount_out AS DOUBLE) AS q_user,
           CAST(pool_quote_token_reserves AS DOUBLE)
             - (CAST(quote_amount_out AS DOUBLE) - COALESCE(CAST(lp_fee AS DOUBLE), 0)) AS q1,
           CAST(pool_base_token_reserves AS DOUBLE) + CAST(base_amount_in AS DOUBLE) AS b1
    FROM pumpdotfun_solana.pump_amm_evt_sellevent
    WHERE evt_block_date BETWEEN DATE '2025-11-16' AND DATE '2025-11-30'
      AND pool IN (SELECT pool FROM pools)
),
k AS (
    SELECT e.*, p.mint, p.quote_mint, p.created_at, p.bd, p.qd,
           date_diff('second', p.created_at, e.ts) AS age,
           (e.q1 / power(10, p.qd)) / nullif(e.b1 / power(10, p.bd), 0) AS px,
           CAST(e.slot AS DOUBLE) * 1e7 + e.txi * 1e3 + e.iix AS ord
    FROM ev e
    JOIN pools p ON p.pool = e.pool
    WHERE e.ts >= p.created_at AND e.ts < p.created_at + INTERVAL '180' DAY
)
SELECT CASE WHEN age < 300 THEN 'S' WHEN age < 604800 THEN 'H' ELSE 'D' END AS kind,
       mint, pool, quote_mint, created_at, bd, qd,
       CASE WHEN age < 300 THEN floor(age / 5e0) WHEN age < 604800 THEN floor(age / 3600e0)
            ELSE floor(age / 86400e0) END AS bkey,
       count(*) AS n, count_if(side = 'B') AS n_buy, approx_distinct(usr) AS n_users,
       sum(CASE WHEN side = 'B' THEN q_user END) AS q_buy_user,
       sum(CASE WHEN side = 'S' THEN q_user END) AS q_sell_user,
       sum(CASE WHEN side = 'B' THEN b_amt END) AS b_buy,
       sum(CASE WHEN side = 'S' THEN b_amt END) AS b_sell,
       min_by(q0, ord) AS q0_open, min_by(b0, ord) AS b0_open,
       max_by(q1, ord) AS q1_close, max_by(b1, ord) AS b1_close,
       min_by(px, ord) AS px_open, max_by(px, ord) AS px_close, max(px) AS px_high, min(px) AS px_low,
       min(ts) AS t_first, max(ts) AS t_last
FROM k
GROUP BY 1, 2, 3, 4, 5, 6, 7, 8
