/* DQ-35 v2.2 扩大样本逐笔（10-05，执行模型）：建池于 2026-09-24 00:00:00～2026-09-25 00:00:00 的 pump 迁移池在 2026-09-24～2026-09-24 的全部买卖、加撤池事件；独立母体；只用于核对 */
WITH
bn(base) AS (
    /* 币安现货全部 746 个基础资产名（Probe L 母表 u_trade，公开信息）；留出按 sha256(baseAsset) 首字节 mod 5 == 0 在下面计算 */
    SELECT base FROM (VALUES
        ('0G'),
        ('1000CAT'),
        ('1000CHEEMS'),
        ('1000SATS'),
        ('1INCH'),
        ('1MBABYDOGE'),
        ('2Z'),
        ('A'),
        ('A2Z'),
        ('AAOIB'),
        ('AAPLB'),
        ('AAVE'),
        ('ACA'),
        ('ACE'),
        ('ACH'),
        ('ACM'),
        ('ACT'),
        ('ACX'),
        ('ADA'),
        ('ADX'),
        ('AE'),
        ('AERGO'),
        ('AERO'),
        ('AEUR'),
        ('AEVO'),
        ('AGI'),
        ('AGIX'),
        ('AGLD'),
        ('AI'),
        ('AIGENSYN'),
        ('AION'),
        ('AIXBT'),
        ('AKRO'),
        ('ALCX'),
        ('ALGO'),
        ('ALICE'),
        ('ALLO'),
        ('ALPACA'),
        ('ALPHA'),
        ('ALPINE'),
        ('ALT'),
        ('AMATB'),
        ('AMB'),
        ('AMDB'),
        ('AMP'),
        ('AMZNB'),
        ('ANC'),
        ('ANIME'),
        ('ANKR'),
        ('ANT'),
        ('ANY'),
        ('APE'),
        ('API3'),
        ('APPC'),
        ('APT'),
        ('AR'),
        ('ARB'),
        ('ARDR'),
        ('ARK'),
        ('ARKM'),
        ('ARMB'),
        ('ARN'),
        ('ARPA'),
        ('ASR'),
        ('AST'),
        ('ASTER'),
        ('ASTR'),
        ('AT'),
        ('ATA'),
        ('ATM'),
        ('ATOM'),
        ('AUCTION'),
        ('AUD'),
        ('AUDIO'),
        ('AUTO'),
        ('AVA'),
        ('AVAX'),
        ('AVGOB'),
        ('AVNT'),
        ('AWE'),
        ('AXL'),
        ('AXS'),
        ('AXTIB'),
        ('BABAB'),
        ('BABY'),
        ('BADGER'),
        ('BAKE'),
        ('BAL'),
        ('BANANA'),
        ('BANANAS31'),
        ('BAND'),
        ('BANK'),
        ('BAR'),
        ('BARD'),
        ('BAT'),
        ('BB'),
        ('BCC'),
        ('BCD'),
        ('BCH'),
        ('BCHA'),
        ('BCHABC'),
        ('BCHSV'),
        ('BCN'),
        ('BCPT'),
        ('BDOT'),
        ('BEAM'),
        ('BEAMX'),
        ('BEAR'),
        ('BEB'),
        ('BEL'),
        ('BERA'),
        ('BETA'),
        ('BETH'),
        ('BFUSD'),
        ('BGBP'),
        ('BICO'),
        ('BIFI'),
        ('BIGTIME'),
        ('BIO'),
        ('BKRW'),
        ('BLUR'),
        ('BLZ'),
        ('BMT'),
        ('BNB'),
        ('BNSOL'),
        ('BNT'),
        ('BNX'),
        ('BOME'),
        ('BOND'),
        ('BONK'),
        ('BOT'),
        ('BQX'),
        ('BRD'),
        ('BREV'),
        ('BROCCOLI714'),
        ('BSW'),
        ('BTC'),
        ('BTCB'),
        ('BTCST'),
        ('BTG'),
        ('BTS'),
        ('BTT'),
        ('BTTC'),
        ('BULL'),
        ('BURGER'),
        ('BUSD'),
        ('BZRX'),
        ('C'),
        ('C98'),
        ('CAKE'),
        ('CATI'),
        ('CBRSB'),
        ('CDT'),
        ('CELO'),
        ('CELR'),
        ('CETUS'),
        ('CFG'),
        ('CFX'),
        ('CGPT'),
        ('CHAT'),
        ('CHESS'),
        ('CHIP'),
        ('CHR'),
        ('CHZ'),
        ('CITY'),
        ('CKB'),
        ('CLOAK'),
        ('CLV'),
        ('CMT'),
        ('CND'),
        ('COCOS'),
        ('COINB'),
        ('COMBO'),
        ('COMP'),
        ('COOKIE'),
        ('COS'),
        ('COTI'),
        ('COVER'),
        ('COW'),
        ('CRCLB'),
        ('CREAM'),
        ('CRV'),
        ('CRWVB'),
        ('CTK'),
        ('CTSI'),
        ('CTXC'),
        ('CVC'),
        ('CVP'),
        ('CVX'),
        ('CYBER'),
        ('D'),
        ('DAI'),
        ('DAR'),
        ('DASH'),
        ('DATA'),
        ('DCR'),
        ('DEGO'),
        ('DELLB'),
        ('DENT'),
        ('DEXE'),
        ('DF'),
        ('DGB'),
        ('DGD'),
        ('DIA'),
        ('DLT'),
        ('DNT'),
        ('DOCK'),
        ('DODO'),
        ('DOGE'),
        ('DOGS'),
        ('DOLO'),
        ('DOT'),
        ('DRAMB'),
        ('DREP'),
        ('DUSK'),
        ('DYDX'),
        ('DYM'),
        ('EASY'),
        ('EDEN'),
        ('EDO'),
        ('EDU'),
        ('EGLD'),
        ('EIGEN'),
        ('ELF'),
        ('ENA'),
        ('ENG'),
        ('ENJ'),
        ('ENS'),
        ('ENSO'),
        ('EOS'),
        ('EPIC'),
        ('EPS'),
        ('EPX'),
        ('ERA'),
        ('ERD'),
        ('ERN'),
        ('ESP'),
        ('ETC'),
        ('ETH'),
        ('ETHFI'),
        ('EUL'),
        ('EUR'),
        ('EURI'),
        ('EVX'),
        ('EWYB'),
        ('EZ'),
        ('F'),
        ('FARM'),
        ('FDUSD'),
        ('FET'),
        ('FF'),
        ('FIDA'),
        ('FIL'),
        ('FIO'),
        ('FIRO'),
        ('FIS'),
        ('FLM'),
        ('FLNCB'),
        ('FLOKI'),
        ('FLOW'),
        ('FLUX'),
        ('FOGO'),
        ('FOR'),
        ('FORM'),
        ('FORTH'),
        ('FRAX'),
        ('FRONT'),
        ('FTM'),
        ('FTT'),
        ('FUEL'),
        ('FUN'),
        ('FXS'),
        ('G'),
        ('GAL'),
        ('GALA'),
        ('GAS'),
        ('GBP'),
        ('GENIUS'),
        ('GFT'),
        ('GHST'),
        ('GIGGLE'),
        ('GLM'),
        ('GLMR'),
        ('GLWB'),
        ('GMT'),
        ('GMX'),
        ('GNO'),
        ('GNS'),
        ('GNT'),
        ('GO'),
        ('GOOGLB'),
        ('GPS'),
        ('GRAM'),
        ('GRS'),
        ('GRT'),
        ('GSB'),
        ('GTC'),
        ('GTO'),
        ('GUN'),
        ('GVT'),
        ('GXS'),
        ('HAEDAL'),
        ('HARD'),
        ('HBAR'),
        ('HC'),
        ('HEGIC'),
        ('HEI'),
        ('HEMI'),
        ('HFT'),
        ('HIFI'),
        ('HIGH'),
        ('HIVE'),
        ('HMSTR'),
        ('HNT'),
        ('HOLO'),
        ('HOME'),
        ('HOODB'),
        ('HOOK'),
        ('HOT'),
        ('HSR'),
        ('HUMA'),
        ('HYPER'),
        ('IBMB'),
        ('ICN'),
        ('ICP'),
        ('ICX'),
        ('ID'),
        ('IDEX'),
        ('ILV'),
        ('IMX'),
        ('INIT'),
        ('INJ'),
        ('INS'),
        ('INTCB'),
        ('INTWB'),
        ('IO'),
        ('IOST'),
        ('IOTA'),
        ('IOTX'),
        ('IQ'),
        ('IRIS'),
        ('JASMY'),
        ('JOE'),
        ('JST'),
        ('JTO'),
        ('JUP'),
        ('JUV'),
        ('KAIA'),
        ('KAITO'),
        ('KAT'),
        ('KAVA'),
        ('KDA'),
        ('KEEP'),
        ('KERNEL'),
        ('KEY'),
        ('KGST'),
        ('KITE'),
        ('KLAY'),
        ('KMD'),
        ('KMNO'),
        ('KNC'),
        ('KORUB'),
        ('KP3R'),
        ('KSM'),
        ('LA'),
        ('LAYER'),
        ('LAZIO'),
        ('LDO'),
        ('LEND'),
        ('LEVER'),
        ('LINA'),
        ('LINEA'),
        ('LINK'),
        ('LISTA'),
        ('LIT'),
        ('LITEB'),
        ('LOKA'),
        ('LOOM'),
        ('LPT'),
        ('LQTY'),
        ('LRC'),
        ('LSK'),
        ('LTC'),
        ('LTO'),
        ('LUMIA'),
        ('LUN'),
        ('LUNA'),
        ('LUNC'),
        ('MAGIC'),
        ('MANA'),
        ('MANTA'),
        ('MANTRA'),
        ('MASK'),
        ('MATIC'),
        ('MAV'),
        ('MBL'),
        ('MBOX'),
        ('MC'),
        ('MCO'),
        ('MDA'),
        ('MDT'),
        ('MDX'),
        ('ME'),
        ('MEGA'),
        ('MEME'),
        ('MET'),
        ('METAB'),
        ('METIS'),
        ('MFT'),
        ('MINA'),
        ('MIR'),
        ('MIRA'),
        ('MITH'),
        ('MITO'),
        ('MKR'),
        ('MLN'),
        ('MMT'),
        ('MOB'),
        ('MOD'),
        ('MORPHO'),
        ('MOVE'),
        ('MOVR'),
        ('MRVLB'),
        ('MSFTB'),
        ('MSTRB'),
        ('MTH'),
        ('MTL'),
        ('MUB'),
        ('MUBARAK'),
        ('MULTI'),
        ('MUUB'),
        ('MVLLB'),
        ('NANO'),
        ('NAS'),
        ('NAV'),
        ('NBISB'),
        ('NBS'),
        ('NBT'),
        ('NCASH'),
        ('NEAR'),
        ('NEBL'),
        ('NEIRO'),
        ('NEO'),
        ('NEWT'),
        ('NEXO'),
        ('NFP'),
        ('NIGHT'),
        ('NIL'),
        ('NKN'),
        ('NMR'),
        ('NOKB'),
        ('NOM'),
        ('NOT'),
        ('NPXS'),
        ('NTRN'),
        ('NU'),
        ('NULS'),
        ('NVDAB'),
        ('NXPC'),
        ('NXS'),
        ('OAX'),
        ('OCEAN'),
        ('OG'),
        ('OGN'),
        ('OM'),
        ('OMG'),
        ('OMNI'),
        ('ONDO'),
        ('ONE'),
        ('ONG'),
        ('ONT'),
        ('OOKI'),
        ('OP'),
        ('OPEN'),
        ('OPG'),
        ('OPN'),
        ('ORCA'),
        ('ORCLB'),
        ('ORDI'),
        ('ORN'),
        ('OSMO'),
        ('OST'),
        ('OXT'),
        ('PARTI'),
        ('PAX'),
        ('PAXG'),
        ('PDA'),
        ('PENDLE'),
        ('PENGU'),
        ('PEOPLE'),
        ('PEPE'),
        ('PERL'),
        ('PERP'),
        ('PHA'),
        ('PHB'),
        ('PHX'),
        ('PIVX'),
        ('PIXEL'),
        ('PLA'),
        ('PLTRB'),
        ('PLUME'),
        ('PNT'),
        ('PNUT'),
        ('POA'),
        ('POE'),
        ('POL'),
        ('POLS'),
        ('POLY'),
        ('POLYX'),
        ('POND'),
        ('PORTAL'),
        ('PORTO'),
        ('POWR'),
        ('PPT'),
        ('PROM'),
        ('PROS'),
        ('PROVE'),
        ('PSG'),
        ('PUMP'),
        ('PUNDIX'),
        ('PYPLB'),
        ('PYR'),
        ('PYTH'),
        ('QCOMB'),
        ('QI'),
        ('QKC'),
        ('QLC'),
        ('QNT'),
        ('QNTB'),
        ('QQQB'),
        ('QSP'),
        ('QTUM'),
        ('QUICK'),
        ('RAD'),
        ('RAMP'),
        ('RARE'),
        ('RAY'),
        ('RCN'),
        ('RDN'),
        ('RDNT'),
        ('RE'),
        ('RED'),
        ('REEF'),
        ('REI'),
        ('REN'),
        ('RENBTC'),
        ('RENDER'),
        ('REP'),
        ('REQ'),
        ('RESOLV'),
        ('REZ'),
        ('RGT'),
        ('RIF'),
        ('RKLBB'),
        ('RLC'),
        ('RLUSD'),
        ('RNDR'),
        ('ROBO'),
        ('RONIN'),
        ('ROSE'),
        ('RPL'),
        ('RPX'),
        ('RSR'),
        ('RUNE'),
        ('RVN'),
        ('S'),
        ('SAGA'),
        ('SAHARA'),
        ('SALT'),
        ('SAND'),
        ('SANTOS'),
        ('SAPIEN'),
        ('SC'),
        ('SCR'),
        ('SCRT'),
        ('SEI'),
        ('SENT'),
        ('SFP'),
        ('SHELL'),
        ('SHIB'),
        ('SIGN'),
        ('SKHYB'),
        ('SKL'),
        ('SKY'),
        ('SLF'),
        ('SLP'),
        ('SMHB'),
        ('SNDKB'),
        ('SNGLS'),
        ('SNM'),
        ('SNT'),
        ('SNX'),
        ('SNXXB'),
        ('SOL'),
        ('SOLV'),
        ('SOMI'),
        ('SOPH'),
        ('SOXLB'),
        ('SOXSB'),
        ('SPARTA'),
        ('SPCXB'),
        ('SPELL'),
        ('SPK'),
        ('SPYB'),
        ('SRM'),
        ('SSV'),
        ('STEEM'),
        ('STG'),
        ('STMX'),
        ('STO'),
        ('STORJ'),
        ('STORM'),
        ('STPT'),
        ('STRAT'),
        ('STRAX'),
        ('STRK'),
        ('STX'),
        ('SUB'),
        ('SUI'),
        ('SUN'),
        ('SUPER'),
        ('SUSD'),
        ('SUSHI'),
        ('SWRV'),
        ('SXP'),
        ('SXT'),
        ('SYN'),
        ('SYRUP'),
        ('SYS'),
        ('T'),
        ('TAO'),
        ('TCT'),
        ('TFUEL'),
        ('THE'),
        ('THETA'),
        ('TIA'),
        ('TKO'),
        ('TLM'),
        ('TNB'),
        ('TNSR'),
        ('TNT'),
        ('TOMO'),
        ('TON'),
        ('TORN'),
        ('TOWNS'),
        ('TQQQB'),
        ('TRB'),
        ('TREE'),
        ('TRIBE'),
        ('TRIG'),
        ('TROY'),
        ('TRU'),
        ('TRUMP'),
        ('TRX'),
        ('TSLAB'),
        ('TSMB'),
        ('TST'),
        ('TURBO'),
        ('TURTLE'),
        ('TUSD'),
        ('TUSDB'),
        ('TUT'),
        ('TVK'),
        ('TWT'),
        ('U'),
        ('UFT'),
        ('UMA'),
        ('UNFI'),
        ('UNI'),
        ('USD1'),
        ('USDC'),
        ('USDE'),
        ('USDP'),
        ('USDS'),
        ('USDSB'),
        ('USDT'),
        ('UST'),
        ('USTC'),
        ('USUAL'),
        ('UTK'),
        ('VANA'),
        ('VANRY'),
        ('VELODROME'),
        ('VEN'),
        ('VET'),
        ('VGX'),
        ('VIA'),
        ('VIB'),
        ('VIBE'),
        ('VIC'),
        ('VIDT'),
        ('VIRTUAL'),
        ('VITE'),
        ('VOXEL'),
        ('VTHO'),
        ('W'),
        ('WABI'),
        ('WAL'),
        ('WAN'),
        ('WAVES'),
        ('WAXP'),
        ('WBETH'),
        ('WBTC'),
        ('WCT'),
        ('WDCB'),
        ('WIF'),
        ('WIN'),
        ('WING'),
        ('WINGS'),
        ('WLD'),
        ('WLFI'),
        ('WNXM'),
        ('WOO'),
        ('WPR'),
        ('WRX'),
        ('WTC'),
        ('XAI'),
        ('XAUT'),
        ('XEC'),
        ('XEM'),
        ('XLM'),
        ('XMR'),
        ('XNO'),
        ('XPL'),
        ('XRP'),
        ('XTZ'),
        ('XUSD'),
        ('XVG'),
        ('XVS'),
        ('XZC'),
        ('YB'),
        ('YFI'),
        ('YFII'),
        ('YGG'),
        ('YOYO'),
        ('ZAMA'),
        ('ZBT'),
        ('ZEC'),
        ('ZEN'),
        ('ZIL'),
        ('ZK'),
        ('ZKC'),
        ('ZKP'),
        ('ZRO'),
        ('ZRX'),
        ('币安人生')
    ) AS v(base)
),
excl AS (
    SELECT base FROM bn
    WHERE mod(from_big_endian_32(from_hex('000000' || substr(to_hex(sha256(to_utf8(base))), 1, 2))), 5) = 0
),
c0 AS (
    SELECT pool, min(evt_block_time) AS created_at, max(base_mint) AS mint, max(quote_mint) AS quote_mint,
           max(base_mint_decimals) AS bd, max(quote_mint_decimals) AS qd,
           max(evt_block_slot) AS cs, max(evt_tx_index) AS ctx, max(evt_outer_instruction_index) AS co,
           max(evt_inner_instruction_index) AS ci, max(evt_tx_id) AS ctid,
           CAST(max(pool_quote_amount) AS varchar) AS cq, CAST(max(pool_base_amount) AS varchar) AS cb
    FROM pumpdotfun_solana.pump_amm_evt_createpoolevent
    WHERE evt_block_date BETWEEN DATE '2026-09-24' AND DATE '2026-09-24'
      AND evt_outer_executing_account = '6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P'
      AND index = 0
    GROUP BY 1
    HAVING min(evt_block_time) >= TIMESTAMP '2026-09-24 00:00:00' AND min(evt_block_time) < TIMESTAMP '2026-09-25 00:00:00'
       AND max(quote_mint) <> 'So11111111111111111111111111111111111111112'
),
cr AS (
    SELECT mint, min(evt_block_time) AS cct, min_by(symbol, evt_block_time) AS sym
    FROM pumpdotfun_solana.pump_evt_createevent
    WHERE evt_block_date BETWEEN DATE '2024-01-01' AND DATE '2026-09-24'
      AND mint IN (SELECT mint FROM c0)
    GROUP BY 1
),
lab AS (
    SELECT c0.*, cr.cct,
           CASE WHEN cr.cct IS NULL THEN 'no_create'
                WHEN TIMESTAMP '2026-06-15 00:00:00' <= cr.cct AND cr.cct < TIMESTAMP '2026-07-13 00:00:00' THEN 'sealed'
                WHEN cr.sym IS NULL THEN 'no_symbol'
                WHEN upper(trim(replace(cr.sym, '$', ''))) IN (SELECT base FROM excl) THEN 'holdout_name'
                ELSE 'in' END AS cls
    FROM c0 LEFT JOIN cr ON cr.mint = c0.mint
),
inp AS (SELECT * FROM lab WHERE cls = 'in')
SELECT 'C' AS ev, pool, created_at AS ts, cs AS slot, ctx AS txi, co AS oix, ci AS iix, ctid AS tx_id, NULL AS usr,
       quote_mint AS q0, CAST(qd AS varchar) AS b0, mint AS q_amt, CAST(bd AS varchar) AS q_amt_lp,
       CAST(to_unixtime(cct) AS varchar) AS q_user, cq AS b_amt, cb AS f_lp, NULL AS f_pr, NULL AS f_cr, NULL AS f_cb, NULL AS f_bb
FROM inp
UNION ALL
SELECT 'X', cls, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(count(*) AS varchar), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
FROM lab WHERE cls <> 'in' GROUP BY cls
UNION ALL
SELECT 'B', pool, evt_block_time, evt_block_slot, evt_tx_index, evt_outer_instruction_index, evt_inner_instruction_index,
       evt_tx_id, "user",
       CAST(pool_quote_token_reserves AS varchar), CAST(pool_base_token_reserves AS varchar),
       CAST(quote_amount_in AS varchar), CAST(quote_amount_in_with_lp_fee AS varchar),
       CAST(user_quote_amount_in AS varchar), CAST(base_amount_out AS varchar),
       CAST(lp_fee AS varchar), CAST(protocol_fee AS varchar), CAST(coin_creator_fee AS varchar), NULL, NULL
FROM pumpdotfun_solana.pump_amm_evt_buyevent
WHERE evt_block_date BETWEEN DATE '2026-09-24' AND DATE '2026-09-24' AND pool IN (SELECT pool FROM inp)
UNION ALL
SELECT 'S', pool, evt_block_time, evt_block_slot, evt_tx_index, evt_outer_instruction_index, evt_inner_instruction_index,
       evt_tx_id, "user",
       CAST(pool_quote_token_reserves AS varchar), CAST(pool_base_token_reserves AS varchar),
       CAST(quote_amount_out AS varchar), CAST(quote_amount_out_without_lp_fee AS varchar),
       CAST(user_quote_amount_out AS varchar), CAST(base_amount_in AS varchar),
       CAST(lp_fee AS varchar), CAST(protocol_fee AS varchar), CAST(coin_creator_fee AS varchar),
       CAST(cashback AS varchar), CAST(buyback_fee AS varchar)
FROM pumpdotfun_solana.pump_amm_evt_sellevent
WHERE evt_block_date BETWEEN DATE '2026-09-24' AND DATE '2026-09-24' AND pool IN (SELECT pool FROM inp)
UNION ALL
SELECT 'D', pool, evt_block_time, evt_block_slot, evt_tx_index, evt_outer_instruction_index, evt_inner_instruction_index,
       evt_tx_id, "user",
       CAST(pool_quote_token_reserves AS varchar), CAST(pool_base_token_reserves AS varchar),
       CAST(quote_amount_in AS varchar), NULL, NULL, CAST(base_amount_in AS varchar), NULL, NULL, NULL, NULL, NULL
FROM pumpdotfun_solana.pump_amm_evt_depositevent
WHERE evt_block_date BETWEEN DATE '2026-09-24' AND DATE '2026-09-24' AND pool IN (SELECT pool FROM inp)
UNION ALL
SELECT 'W', pool, evt_block_time, evt_block_slot, evt_tx_index, evt_outer_instruction_index, evt_inner_instruction_index,
       evt_tx_id, "user",
       CAST(pool_quote_token_reserves AS varchar), CAST(pool_base_token_reserves AS varchar),
       CAST(quote_amount_out AS varchar), NULL, NULL, CAST(base_amount_out AS varchar), NULL, NULL, NULL, NULL, NULL
FROM pumpdotfun_solana.pump_amm_evt_withdrawevent
WHERE evt_block_date BETWEEN DATE '2026-09-24' AND DATE '2026-09-24' AND pool IN (SELECT pool FROM inp)
UNION ALL
SELECT 'R', rp, block_time, block_slot, tx_index, outer_instruction_index, inner_instruction_index, tx_id, rk,
       to_hex(bytearray_substring(data, st, length(data) - st + 1)), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
FROM (
    SELECT *,
           CASE WHEN dsc = 0x67f4521f2cf57777 THEN 'B' WHEN dsc = 0x3e2f370aa503dc2a THEN 'S'
                WHEN dsc = 0xae7c4af90451f611 THEN 'I' ELSE 'U' END AS rk,
           CASE WHEN dsc = 0x67f4521f2cf57777 THEN 410 WHEN dsc = 0x3e2f370aa503dc2a THEN 369 ELSE 89 END AS st,
           to_base58(bytearray_substring(data, CASE WHEN dsc IN (0x67f4521f2cf57777, 0x3e2f370aa503dc2a) THEN 129 ELSE 89 END, 32)) AS rp
    FROM (
        SELECT block_time, block_slot, tx_index, outer_instruction_index, inner_instruction_index, tx_id, data,
               bytearray_substring(data, 9, 8) AS dsc
        FROM solana.instruction_calls
        WHERE block_date BETWEEN DATE '2026-09-24' AND DATE '2026-09-24'
          AND executing_account = 'pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA'
          AND is_inner = true AND tx_success = true
          AND bytearray_substring(data, 1, 8) = 0xe445a52e51cb9a1d
          AND bytearray_substring(data, 9, 8) IN (0x67f4521f2cf57777, 0x3e2f370aa503dc2a, 0xae7c4af90451f611, 0x3f451c16305cc2b9)
    ) z
) y
WHERE rp IN (SELECT pool FROM inp)
