/* DQ-35 v2.2 数据留存（10-05，执行模型）：层 B；Solana；曲线完成于 2026-09-23～2026-09-23 的 pump 币；只存不分析；由 build_gradpre_sql_v22.py 生成 */
WITH
bn(base) AS (
    /* 币安现货全部 746 个基础资产名（Probe L 母表 u_trade，公开信息）；留出按 sha256(baseAsset) 首字节 mod 5 == 0 在下面计算 */
    SELECT base FROM (VALUES
        ('0G'),
        ('1000CAT'),
        ('1000CHEEMS'),
        ('1000SATS'),
        ('1INCH'),
        ('1MBABYDOGE'),
        ('2Z'),
        ('A'),
        ('A2Z'),
        ('AAOIB'),
        ('AAPLB'),
        ('AAVE'),
        ('ACA'),
        ('ACE'),
        ('ACH'),
        ('ACM'),
        ('ACT'),
        ('ACX'),
        ('ADA'),
        ('ADX'),
        ('AE'),
        ('AERGO'),
        ('AERO'),
        ('AEUR'),
        ('AEVO'),
        ('AGI'),
        ('AGIX'),
        ('AGLD'),
        ('AI'),
        ('AIGENSYN'),
        ('AION'),
        ('AIXBT'),
        ('AKRO'),
        ('ALCX'),
        ('ALGO'),
        ('ALICE'),
        ('ALLO'),
        ('ALPACA'),
        ('ALPHA'),
        ('ALPINE'),
        ('ALT'),
        ('AMATB'),
        ('AMB'),
        ('AMDB'),
        ('AMP'),
        ('AMZNB'),
        ('ANC'),
        ('ANIME'),
        ('ANKR'),
        ('ANT'),
        ('ANY'),
        ('APE'),
        ('API3'),
        ('APPC'),
        ('APT'),
        ('AR'),
        ('ARB'),
        ('ARDR'),
        ('ARK'),
        ('ARKM'),
        ('ARMB'),
        ('ARN'),
        ('ARPA'),
        ('ASR'),
        ('AST'),
        ('ASTER'),
        ('ASTR'),
        ('AT'),
        ('ATA'),
        ('ATM'),
        ('ATOM'),
        ('AUCTION'),
        ('AUD'),
        ('AUDIO'),
        ('AUTO'),
        ('AVA'),
        ('AVAX'),
        ('AVGOB'),
        ('AVNT'),
        ('AWE'),
        ('AXL'),
        ('AXS'),
        ('AXTIB'),
        ('BABAB'),
        ('BABY'),
        ('BADGER'),
        ('BAKE'),
        ('BAL'),
        ('BANANA'),
        ('BANANAS31'),
        ('BAND'),
        ('BANK'),
        ('BAR'),
        ('BARD'),
        ('BAT'),
        ('BB'),
        ('BCC'),
        ('BCD'),
        ('BCH'),
        ('BCHA'),
        ('BCHABC'),
        ('BCHSV'),
        ('BCN'),
        ('BCPT'),
        ('BDOT'),
        ('BEAM'),
        ('BEAMX'),
        ('BEAR'),
        ('BEB'),
        ('BEL'),
        ('BERA'),
        ('BETA'),
        ('BETH'),
        ('BFUSD'),
        ('BGBP'),
        ('BICO'),
        ('BIFI'),
        ('BIGTIME'),
        ('BIO'),
        ('BKRW'),
        ('BLUR'),
        ('BLZ'),
        ('BMT'),
        ('BNB'),
        ('BNSOL'),
        ('BNT'),
        ('BNX'),
        ('BOME'),
        ('BOND'),
        ('BONK'),
        ('BOT'),
        ('BQX'),
        ('BRD'),
        ('BREV'),
        ('BROCCOLI714'),
        ('BSW'),
        ('BTC'),
        ('BTCB'),
        ('BTCST'),
        ('BTG'),
        ('BTS'),
        ('BTT'),
        ('BTTC'),
        ('BULL'),
        ('BURGER'),
        ('BUSD'),
        ('BZRX'),
        ('C'),
        ('C98'),
        ('CAKE'),
        ('CATI'),
        ('CBRSB'),
        ('CDT'),
        ('CELO'),
        ('CELR'),
        ('CETUS'),
        ('CFG'),
        ('CFX'),
        ('CGPT'),
        ('CHAT'),
        ('CHESS'),
        ('CHIP'),
        ('CHR'),
        ('CHZ'),
        ('CITY'),
        ('CKB'),
        ('CLOAK'),
        ('CLV'),
        ('CMT'),
        ('CND'),
        ('COCOS'),
        ('COINB'),
        ('COMBO'),
        ('COMP'),
        ('COOKIE'),
        ('COS'),
        ('COTI'),
        ('COVER'),
        ('COW'),
        ('CRCLB'),
        ('CREAM'),
        ('CRV'),
        ('CRWVB'),
        ('CTK'),
        ('CTSI'),
        ('CTXC'),
        ('CVC'),
        ('CVP'),
        ('CVX'),
        ('CYBER'),
        ('D'),
        ('DAI'),
        ('DAR'),
        ('DASH'),
        ('DATA'),
        ('DCR'),
        ('DEGO'),
        ('DELLB'),
        ('DENT'),
        ('DEXE'),
        ('DF'),
        ('DGB'),
        ('DGD'),
        ('DIA'),
        ('DLT'),
        ('DNT'),
        ('DOCK'),
        ('DODO'),
        ('DOGE'),
        ('DOGS'),
        ('DOLO'),
        ('DOT'),
        ('DRAMB'),
        ('DREP'),
        ('DUSK'),
        ('DYDX'),
        ('DYM'),
        ('EASY'),
        ('EDEN'),
        ('EDO'),
        ('EDU'),
        ('EGLD'),
        ('EIGEN'),
        ('ELF'),
        ('ENA'),
        ('ENG'),
        ('ENJ'),
        ('ENS'),
        ('ENSO'),
        ('EOS'),
        ('EPIC'),
        ('EPS'),
        ('EPX'),
        ('ERA'),
        ('ERD'),
        ('ERN'),
        ('ESP'),
        ('ETC'),
        ('ETH'),
        ('ETHFI'),
        ('EUL'),
        ('EUR'),
        ('EURI'),
        ('EVX'),
        ('EWYB'),
        ('EZ'),
        ('F'),
        ('FARM'),
        ('FDUSD'),
        ('FET'),
        ('FF'),
        ('FIDA'),
        ('FIL'),
        ('FIO'),
        ('FIRO'),
        ('FIS'),
        ('FLM'),
        ('FLNCB'),
        ('FLOKI'),
        ('FLOW'),
        ('FLUX'),
        ('FOGO'),
        ('FOR'),
        ('FORM'),
        ('FORTH'),
        ('FRAX'),
        ('FRONT'),
        ('FTM'),
        ('FTT'),
        ('FUEL'),
        ('FUN'),
        ('FXS'),
        ('G'),
        ('GAL'),
        ('GALA'),
        ('GAS'),
        ('GBP'),
        ('GENIUS'),
        ('GFT'),
        ('GHST'),
        ('GIGGLE'),
        ('GLM'),
        ('GLMR'),
        ('GLWB'),
        ('GMT'),
        ('GMX'),
        ('GNO'),
        ('GNS'),
        ('GNT'),
        ('GO'),
        ('GOOGLB'),
        ('GPS'),
        ('GRAM'),
        ('GRS'),
        ('GRT'),
        ('GSB'),
        ('GTC'),
        ('GTO'),
        ('GUN'),
        ('GVT'),
        ('GXS'),
        ('HAEDAL'),
        ('HARD'),
        ('HBAR'),
        ('HC'),
        ('HEGIC'),
        ('HEI'),
        ('HEMI'),
        ('HFT'),
        ('HIFI'),
        ('HIGH'),
        ('HIVE'),
        ('HMSTR'),
        ('HNT'),
        ('HOLO'),
        ('HOME'),
        ('HOODB'),
        ('HOOK'),
        ('HOT'),
        ('HSR'),
        ('HUMA'),
        ('HYPER'),
        ('IBMB'),
        ('ICN'),
        ('ICP'),
        ('ICX'),
        ('ID'),
        ('IDEX'),
        ('ILV'),
        ('IMX'),
        ('INIT'),
        ('INJ'),
        ('INS'),
        ('INTCB'),
        ('INTWB'),
        ('IO'),
        ('IOST'),
        ('IOTA'),
        ('IOTX'),
        ('IQ'),
        ('IRIS'),
        ('JASMY'),
        ('JOE'),
        ('JST'),
        ('JTO'),
        ('JUP'),
        ('JUV'),
        ('KAIA'),
        ('KAITO'),
        ('KAT'),
        ('KAVA'),
        ('KDA'),
        ('KEEP'),
        ('KERNEL'),
        ('KEY'),
        ('KGST'),
        ('KITE'),
        ('KLAY'),
        ('KMD'),
        ('KMNO'),
        ('KNC'),
        ('KORUB'),
        ('KP3R'),
        ('KSM'),
        ('LA'),
        ('LAYER'),
        ('LAZIO'),
        ('LDO'),
        ('LEND'),
        ('LEVER'),
        ('LINA'),
        ('LINEA'),
        ('LINK'),
        ('LISTA'),
        ('LIT'),
        ('LITEB'),
        ('LOKA'),
        ('LOOM'),
        ('LPT'),
        ('LQTY'),
        ('LRC'),
        ('LSK'),
        ('LTC'),
        ('LTO'),
        ('LUMIA'),
        ('LUN'),
        ('LUNA'),
        ('LUNC'),
        ('MAGIC'),
        ('MANA'),
        ('MANTA'),
        ('MANTRA'),
        ('MASK'),
        ('MATIC'),
        ('MAV'),
        ('MBL'),
        ('MBOX'),
        ('MC'),
        ('MCO'),
        ('MDA'),
        ('MDT'),
        ('MDX'),
        ('ME'),
        ('MEGA'),
        ('MEME'),
        ('MET'),
        ('METAB'),
        ('METIS'),
        ('MFT'),
        ('MINA'),
        ('MIR'),
        ('MIRA'),
        ('MITH'),
        ('MITO'),
        ('MKR'),
        ('MLN'),
        ('MMT'),
        ('MOB'),
        ('MOD'),
        ('MORPHO'),
        ('MOVE'),
        ('MOVR'),
        ('MRVLB'),
        ('MSFTB'),
        ('MSTRB'),
        ('MTH'),
        ('MTL'),
        ('MUB'),
        ('MUBARAK'),
        ('MULTI'),
        ('MUUB'),
        ('MVLLB'),
        ('NANO'),
        ('NAS'),
        ('NAV'),
        ('NBISB'),
        ('NBS'),
        ('NBT'),
        ('NCASH'),
        ('NEAR'),
        ('NEBL'),
        ('NEIRO'),
        ('NEO'),
        ('NEWT'),
        ('NEXO'),
        ('NFP'),
        ('NIGHT'),
        ('NIL'),
        ('NKN'),
        ('NMR'),
        ('NOKB'),
        ('NOM'),
        ('NOT'),
        ('NPXS'),
        ('NTRN'),
        ('NU'),
        ('NULS'),
        ('NVDAB'),
        ('NXPC'),
        ('NXS'),
        ('OAX'),
        ('OCEAN'),
        ('OG'),
        ('OGN'),
        ('OM'),
        ('OMG'),
        ('OMNI'),
        ('ONDO'),
        ('ONE'),
        ('ONG'),
        ('ONT'),
        ('OOKI'),
        ('OP'),
        ('OPEN'),
        ('OPG'),
        ('OPN'),
        ('ORCA'),
        ('ORCLB'),
        ('ORDI'),
        ('ORN'),
        ('OSMO'),
        ('OST'),
        ('OXT'),
        ('PARTI'),
        ('PAX'),
        ('PAXG'),
        ('PDA'),
        ('PENDLE'),
        ('PENGU'),
        ('PEOPLE'),
        ('PEPE'),
        ('PERL'),
        ('PERP'),
        ('PHA'),
        ('PHB'),
        ('PHX'),
        ('PIVX'),
        ('PIXEL'),
        ('PLA'),
        ('PLTRB'),
        ('PLUME'),
        ('PNT'),
        ('PNUT'),
        ('POA'),
        ('POE'),
        ('POL'),
        ('POLS'),
        ('POLY'),
        ('POLYX'),
        ('POND'),
        ('PORTAL'),
        ('PORTO'),
        ('POWR'),
        ('PPT'),
        ('PROM'),
        ('PROS'),
        ('PROVE'),
        ('PSG'),
        ('PUMP'),
        ('PUNDIX'),
        ('PYPLB'),
        ('PYR'),
        ('PYTH'),
        ('QCOMB'),
        ('QI'),
        ('QKC'),
        ('QLC'),
        ('QNT'),
        ('QNTB'),
        ('QQQB'),
        ('QSP'),
        ('QTUM'),
        ('QUICK'),
        ('RAD'),
        ('RAMP'),
        ('RARE'),
        ('RAY'),
        ('RCN'),
        ('RDN'),
        ('RDNT'),
        ('RE'),
        ('RED'),
        ('REEF'),
        ('REI'),
        ('REN'),
        ('RENBTC'),
        ('RENDER'),
        ('REP'),
        ('REQ'),
        ('RESOLV'),
        ('REZ'),
        ('RGT'),
        ('RIF'),
        ('RKLBB'),
        ('RLC'),
        ('RLUSD'),
        ('RNDR'),
        ('ROBO'),
        ('RONIN'),
        ('ROSE'),
        ('RPL'),
        ('RPX'),
        ('RSR'),
        ('RUNE'),
        ('RVN'),
        ('S'),
        ('SAGA'),
        ('SAHARA'),
        ('SALT'),
        ('SAND'),
        ('SANTOS'),
        ('SAPIEN'),
        ('SC'),
        ('SCR'),
        ('SCRT'),
        ('SEI'),
        ('SENT'),
        ('SFP'),
        ('SHELL'),
        ('SHIB'),
        ('SIGN'),
        ('SKHYB'),
        ('SKL'),
        ('SKY'),
        ('SLF'),
        ('SLP'),
        ('SMHB'),
        ('SNDKB'),
        ('SNGLS'),
        ('SNM'),
        ('SNT'),
        ('SNX'),
        ('SNXXB'),
        ('SOL'),
        ('SOLV'),
        ('SOMI'),
        ('SOPH'),
        ('SOXLB'),
        ('SOXSB'),
        ('SPARTA'),
        ('SPCXB'),
        ('SPELL'),
        ('SPK'),
        ('SPYB'),
        ('SRM'),
        ('SSV'),
        ('STEEM'),
        ('STG'),
        ('STMX'),
        ('STO'),
        ('STORJ'),
        ('STORM'),
        ('STPT'),
        ('STRAT'),
        ('STRAX'),
        ('STRK'),
        ('STX'),
        ('SUB'),
        ('SUI'),
        ('SUN'),
        ('SUPER'),
        ('SUSD'),
        ('SUSHI'),
        ('SWRV'),
        ('SXP'),
        ('SXT'),
        ('SYN'),
        ('SYRUP'),
        ('SYS'),
        ('T'),
        ('TAO'),
        ('TCT'),
        ('TFUEL'),
        ('THE'),
        ('THETA'),
        ('TIA'),
        ('TKO'),
        ('TLM'),
        ('TNB'),
        ('TNSR'),
        ('TNT'),
        ('TOMO'),
        ('TON'),
        ('TORN'),
        ('TOWNS'),
        ('TQQQB'),
        ('TRB'),
        ('TREE'),
        ('TRIBE'),
        ('TRIG'),
        ('TROY'),
        ('TRU'),
        ('TRUMP'),
        ('TRX'),
        ('TSLAB'),
        ('TSMB'),
        ('TST'),
        ('TURBO'),
        ('TURTLE'),
        ('TUSD'),
        ('TUSDB'),
        ('TUT'),
        ('TVK'),
        ('TWT'),
        ('U'),
        ('UFT'),
        ('UMA'),
        ('UNFI'),
        ('UNI'),
        ('USD1'),
        ('USDC'),
        ('USDE'),
        ('USDP'),
        ('USDS'),
        ('USDSB'),
        ('USDT'),
        ('UST'),
        ('USTC'),
        ('USUAL'),
        ('UTK'),
        ('VANA'),
        ('VANRY'),
        ('VELODROME'),
        ('VEN'),
        ('VET'),
        ('VGX'),
        ('VIA'),
        ('VIB'),
        ('VIBE'),
        ('VIC'),
        ('VIDT'),
        ('VIRTUAL'),
        ('VITE'),
        ('VOXEL'),
        ('VTHO'),
        ('W'),
        ('WABI'),
        ('WAL'),
        ('WAN'),
        ('WAVES'),
        ('WAXP'),
        ('WBETH'),
        ('WBTC'),
        ('WCT'),
        ('WDCB'),
        ('WIF'),
        ('WIN'),
        ('WING'),
        ('WINGS'),
        ('WLD'),
        ('WLFI'),
        ('WNXM'),
        ('WOO'),
        ('WPR'),
        ('WRX'),
        ('WTC'),
        ('XAI'),
        ('XAUT'),
        ('XEC'),
        ('XEM'),
        ('XLM'),
        ('XMR'),
        ('XNO'),
        ('XPL'),
        ('XRP'),
        ('XTZ'),
        ('XUSD'),
        ('XVG'),
        ('XVS'),
        ('XZC'),
        ('YB'),
        ('YFI'),
        ('YFII'),
        ('YGG'),
        ('YOYO'),
        ('ZAMA'),
        ('ZBT'),
        ('ZEC'),
        ('ZEN'),
        ('ZIL'),
        ('ZK'),
        ('ZKC'),
        ('ZKP'),
        ('ZRO'),
        ('ZRX'),
        ('币安人生')
    ) AS v(base)
),
excl AS (
    SELECT base FROM bn
    WHERE mod(from_big_endian_32(from_hex('000000' || substr(to_hex(sha256(to_utf8(base))), 1, 2))), 5) = 0
),
comp AS (
    SELECT mint, min(evt_block_time) AS completed_at, min_by(quote_mint, evt_block_time) AS c_quote_mint
    FROM pumpdotfun_solana.pump_evt_completeevent
    WHERE evt_block_date BETWEEN DATE '2026-09-23' AND DATE '2026-09-23'
    GROUP BY 1
),
cc AS (
    SELECT mint, min(evt_block_time) AS curve_created_at, min_by(symbol, evt_block_time) AS symbol
    FROM pumpdotfun_solana.pump_evt_createevent
    WHERE evt_block_date BETWEEN DATE '2024-01-01' AND DATE '2026-09-23'
      AND mint IN (SELECT mint FROM comp)
    GROUP BY 1
),
call AS (
    /* 互斥类别，按此顺序：无曲线创建 → 封存 → 无代号 → 留出同名 → 纳入 */
    SELECT c.mint, c.completed_at, c.c_quote_mint, s.curve_created_at, s.symbol,
           CASE WHEN s.curve_created_at IS NULL THEN 'no_create'
                WHEN s.curve_created_at >= TIMESTAMP '2026-06-15 00:00:00' AND s.curve_created_at < TIMESTAMP '2026-07-13 00:00:00' THEN 'sealed'
                WHEN s.symbol IS NULL THEN 'no_symbol'
                WHEN upper(trim(replace(s.symbol, '$', ''))) IN (SELECT base FROM excl) THEN 'holdout_name'
                ELSE 'in' END AS cls
    FROM comp c
    LEFT JOIN cc s ON s.mint = c.mint
    WHERE c.completed_at >= TIMESTAMP '2026-09-23 00:00:00'
      AND c.completed_at >= TIMESTAMP '2026-09-23 00:00:00' AND c.completed_at < TIMESTAMP '2026-09-23 01:00:00'
),
mints AS (
    SELECT mint, completed_at, c_quote_mint, curve_created_at,
           (c_quote_mint IS NULL OR c_quote_mint IN ('So11111111111111111111111111111111111111112', '11111111111111111111111111111111')) AS sol_quote
    FROM call
    WHERE cls = 'in'
),
tr AS (
    SELECT t.mint, m.completed_at, m.curve_created_at, m.c_quote_mint, m.sol_quote, t.evt_block_time AS ts,
           t.evt_block_slot AS slot, t.evt_tx_index AS txi, t.evt_outer_instruction_index AS oix,
           COALESCE(t.evt_inner_instruction_index, -1) AS iix, t.evt_tx_id AS tx_id,
           CAST(t.evt_block_slot AS BIGINT) * 10000000000 + CAST(t.evt_tx_index AS BIGINT) * 100000
             + CAST(t.evt_outer_instruction_index AS BIGINT) * 1000 + CAST(COALESCE(t.evt_inner_instruction_index, -1) AS BIGINT) AS ord,
           CASE WHEN t.evt_block_slot IS NULL OR t.evt_tx_index IS NULL OR t.evt_tx_index < 0 OR t.evt_outer_instruction_index < 0
                  OR t.evt_tx_index >= 100000 OR t.evt_outer_instruction_index >= 100 OR t.evt_outer_instruction_index IS NULL
                  OR COALESCE(t.evt_inner_instruction_index, -1) >= 1000 OR t.evt_inner_instruction_index IS NULL
                THEN 1 ELSE 0 END AS ovf,
           COALESCE(t.is_buy, t.isBuy) AS is_buy,
           CAST(t."user" AS varchar) AS usr,
           CAST(COALESCE(t.sol_amount, t.solAmount) AS DECIMAL(38,0)) AS sol,
           CAST(COALESCE(t.token_amount, t.tokenAmount) AS DECIMAL(38,0)) AS tok,
           CAST(t.quote_amount AS DECIMAL(38,0)) AS qa,
           CAST(COALESCE(t.virtual_sol_reserves, t.virtualSolReserves) AS DECIMAL(38,0)) AS x,
           CAST(COALESCE(t.virtual_token_reserves, t.virtualTokenReserves) AS DECIMAL(38,0)) AS y,
           CAST(t.real_sol_reserves AS DECIMAL(38,0)) AS xr,
           CAST(t.fee AS DECIMAL(38,0)) AS f_pr,
           CAST(t.creator_fee AS DECIMAL(38,0)) AS f_cr,
           CAST(t.cashback AS DECIMAL(38,0)) AS f_cb,
           CAST(t.buyback_fee AS DECIMAL(38,0)) AS f_bb,
           COALESCE(t.mayhem_mode, false) AS mayhem
    FROM pumpdotfun_solana.pump_evt_tradeevent t
    JOIN mints m ON m.mint = t.mint
    WHERE t.evt_block_date BETWEEN DATE '2026-09-22' AND DATE '2026-09-23'
      AND t.evt_block_time > m.completed_at - INTERVAL '300' SECOND
      AND t.evt_block_time <= m.completed_at
)
SELECT 'solana' AS chain, mint, to_unixtime(completed_at) AS completed_t, to_unixtime(curve_created_at) AS curve_created_t, c_quote_mint,
       sol_quote AS sol_unit_ok, max(CASE WHEN mayhem THEN 1 ELSE 0 END) AS mayhem,
       CAST(floor(date_diff('millisecond', ts, completed_at) / 5000e0) AS BIGINT) AS bkey,
       count(*) AS n, count_if(is_buy) AS n_buy, count(DISTINCT usr) AS n_users,
       CAST(sum(CASE WHEN is_buy THEN sol ELSE 0 END) AS varchar) AS sol_buy,
       CAST(sum(CASE WHEN NOT is_buy THEN sol ELSE 0 END) AS varchar) AS sol_sell,
       CAST(sum(CASE WHEN is_buy THEN tok ELSE 0 END) AS varchar) AS tok_buy,
       CAST(sum(CASE WHEN NOT is_buy THEN tok ELSE 0 END) AS varchar) AS tok_sell,
       CAST(sum(CASE WHEN is_buy THEN qa END) AS varchar) AS qa_buy,
       CAST(sum(CASE WHEN NOT is_buy THEN qa END) AS varchar) AS qa_sell,
       CAST(max(CASE WHEN is_buy THEN sol END) AS varchar) AS max_buy_sol,
       CAST(sum(f_pr) AS varchar) AS f_pr, CAST(sum(f_cr) AS varchar) AS f_cr,
       CAST(sum(f_cb) AS varchar) AS f_cb, CAST(sum(f_bb) AS varchar) AS f_bb,
       count_if(f_pr IS NULL OR f_cr IS NULL) AS n_fee_null,
       count_if(f_cb IS NULL) AS n_cb_null, count_if(f_bb IS NULL) AS n_bb_null,
       min_by(slot, ord) AS slot_f, min_by(txi, ord) AS txi_f, min_by(oix, ord) AS oix_f, min_by(iix, ord) AS iix_f,
       min_by(tx_id, ord) AS tx_f,
       max_by(slot, ord) AS slot_l, max_by(txi, ord) AS txi_l, max_by(oix, ord) AS oix_l, max_by(iix, ord) AS iix_l,
       max_by(tx_id, ord) AS tx_l,
       min_by(is_buy, ord) AS buy_first, CAST(min_by(sol, ord) AS varchar) AS sol_first, CAST(min_by(tok, ord) AS varchar) AS tok_first,
       CAST(min_by(x, ord) AS varchar) AS x_post_first, CAST(min_by(y, ord) AS varchar) AS y_post_first,
       CASE WHEN sol_quote AND max(CASE WHEN mayhem THEN 1 ELSE 0 END) = 0 THEN true ELSE false END AS pre_valid,
       CASE WHEN sol_quote AND max(CASE WHEN mayhem THEN 1 ELSE 0 END) = 0
            THEN CAST(min_by(CASE WHEN is_buy THEN x - sol ELSE x + sol END, ord) AS varchar) END AS x_pre_first,
       CASE WHEN sol_quote AND max(CASE WHEN mayhem THEN 1 ELSE 0 END) = 0
            THEN CAST(min_by(CASE WHEN is_buy THEN y + tok ELSE y - tok END, ord) AS varchar) END AS y_pre_first,
       max_by(is_buy, ord) AS buy_last,
       CAST(max_by(x, ord) AS varchar) AS x_last, CAST(max_by(y, ord) AS varchar) AS y_last, CAST(max_by(xr, ord) AS varchar) AS xr_last,
       to_unixtime(min(ts)) AS t_first, to_unixtime(max(ts)) AS t_last,
       sum(ovf) AS n_ord_overflow
FROM tr
GROUP BY mint, completed_at, curve_created_at, c_quote_mint, sol_quote,
         CAST(floor(date_diff('millisecond', ts, completed_at) / 5000e0) AS BIGINT)
