/* DQ-35 v2.2 数据留存（10-05，执行模型）：层 P；Solana；pump 迁移池在 2026-09-23～2026-09-23 的事件；只存不分析；由 build_grad_sql_v22.py 生成 */
WITH
bn(base) AS (
    /* 币安现货全部 746 个基础资产名（Probe L 母表 u_trade，公开信息）；留出按 sha256(baseAsset) 首字节 mod 5 == 0 在下面计算 */
    SELECT base FROM (VALUES
        ('0G'),
        ('1000CAT'),
        ('1000CHEEMS'),
        ('1000SATS'),
        ('1INCH'),
        ('1MBABYDOGE'),
        ('2Z'),
        ('A'),
        ('A2Z'),
        ('AAOIB'),
        ('AAPLB'),
        ('AAVE'),
        ('ACA'),
        ('ACE'),
        ('ACH'),
        ('ACM'),
        ('ACT'),
        ('ACX'),
        ('ADA'),
        ('ADX'),
        ('AE'),
        ('AERGO'),
        ('AERO'),
        ('AEUR'),
        ('AEVO'),
        ('AGI'),
        ('AGIX'),
        ('AGLD'),
        ('AI'),
        ('AIGENSYN'),
        ('AION'),
        ('AIXBT'),
        ('AKRO'),
        ('ALCX'),
        ('ALGO'),
        ('ALICE'),
        ('ALLO'),
        ('ALPACA'),
        ('ALPHA'),
        ('ALPINE'),
        ('ALT'),
        ('AMATB'),
        ('AMB'),
        ('AMDB'),
        ('AMP'),
        ('AMZNB'),
        ('ANC'),
        ('ANIME'),
        ('ANKR'),
        ('ANT'),
        ('ANY'),
        ('APE'),
        ('API3'),
        ('APPC'),
        ('APT'),
        ('AR'),
        ('ARB'),
        ('ARDR'),
        ('ARK'),
        ('ARKM'),
        ('ARMB'),
        ('ARN'),
        ('ARPA'),
        ('ASR'),
        ('AST'),
        ('ASTER'),
        ('ASTR'),
        ('AT'),
        ('ATA'),
        ('ATM'),
        ('ATOM'),
        ('AUCTION'),
        ('AUD'),
        ('AUDIO'),
        ('AUTO'),
        ('AVA'),
        ('AVAX'),
        ('AVGOB'),
        ('AVNT'),
        ('AWE'),
        ('AXL'),
        ('AXS'),
        ('AXTIB'),
        ('BABAB'),
        ('BABY'),
        ('BADGER'),
        ('BAKE'),
        ('BAL'),
        ('BANANA'),
        ('BANANAS31'),
        ('BAND'),
        ('BANK'),
        ('BAR'),
        ('BARD'),
        ('BAT'),
        ('BB'),
        ('BCC'),
        ('BCD'),
        ('BCH'),
        ('BCHA'),
        ('BCHABC'),
        ('BCHSV'),
        ('BCN'),
        ('BCPT'),
        ('BDOT'),
        ('BEAM'),
        ('BEAMX'),
        ('BEAR'),
        ('BEB'),
        ('BEL'),
        ('BERA'),
        ('BETA'),
        ('BETH'),
        ('BFUSD'),
        ('BGBP'),
        ('BICO'),
        ('BIFI'),
        ('BIGTIME'),
        ('BIO'),
        ('BKRW'),
        ('BLUR'),
        ('BLZ'),
        ('BMT'),
        ('BNB'),
        ('BNSOL'),
        ('BNT'),
        ('BNX'),
        ('BOME'),
        ('BOND'),
        ('BONK'),
        ('BOT'),
        ('BQX'),
        ('BRD'),
        ('BREV'),
        ('BROCCOLI714'),
        ('BSW'),
        ('BTC'),
        ('BTCB'),
        ('BTCST'),
        ('BTG'),
        ('BTS'),
        ('BTT'),
        ('BTTC'),
        ('BULL'),
        ('BURGER'),
        ('BUSD'),
        ('BZRX'),
        ('C'),
        ('C98'),
        ('CAKE'),
        ('CATI'),
        ('CBRSB'),
        ('CDT'),
        ('CELO'),
        ('CELR'),
        ('CETUS'),
        ('CFG'),
        ('CFX'),
        ('CGPT'),
        ('CHAT'),
        ('CHESS'),
        ('CHIP'),
        ('CHR'),
        ('CHZ'),
        ('CITY'),
        ('CKB'),
        ('CLOAK'),
        ('CLV'),
        ('CMT'),
        ('CND'),
        ('COCOS'),
        ('COINB'),
        ('COMBO'),
        ('COMP'),
        ('COOKIE'),
        ('COS'),
        ('COTI'),
        ('COVER'),
        ('COW'),
        ('CRCLB'),
        ('CREAM'),
        ('CRV'),
        ('CRWVB'),
        ('CTK'),
        ('CTSI'),
        ('CTXC'),
        ('CVC'),
        ('CVP'),
        ('CVX'),
        ('CYBER'),
        ('D'),
        ('DAI'),
        ('DAR'),
        ('DASH'),
        ('DATA'),
        ('DCR'),
        ('DEGO'),
        ('DELLB'),
        ('DENT'),
        ('DEXE'),
        ('DF'),
        ('DGB'),
        ('DGD'),
        ('DIA'),
        ('DLT'),
        ('DNT'),
        ('DOCK'),
        ('DODO'),
        ('DOGE'),
        ('DOGS'),
        ('DOLO'),
        ('DOT'),
        ('DRAMB'),
        ('DREP'),
        ('DUSK'),
        ('DYDX'),
        ('DYM'),
        ('EASY'),
        ('EDEN'),
        ('EDO'),
        ('EDU'),
        ('EGLD'),
        ('EIGEN'),
        ('ELF'),
        ('ENA'),
        ('ENG'),
        ('ENJ'),
        ('ENS'),
        ('ENSO'),
        ('EOS'),
        ('EPIC'),
        ('EPS'),
        ('EPX'),
        ('ERA'),
        ('ERD'),
        ('ERN'),
        ('ESP'),
        ('ETC'),
        ('ETH'),
        ('ETHFI'),
        ('EUL'),
        ('EUR'),
        ('EURI'),
        ('EVX'),
        ('EWYB'),
        ('EZ'),
        ('F'),
        ('FARM'),
        ('FDUSD'),
        ('FET'),
        ('FF'),
        ('FIDA'),
        ('FIL'),
        ('FIO'),
        ('FIRO'),
        ('FIS'),
        ('FLM'),
        ('FLNCB'),
        ('FLOKI'),
        ('FLOW'),
        ('FLUX'),
        ('FOGO'),
        ('FOR'),
        ('FORM'),
        ('FORTH'),
        ('FRAX'),
        ('FRONT'),
        ('FTM'),
        ('FTT'),
        ('FUEL'),
        ('FUN'),
        ('FXS'),
        ('G'),
        ('GAL'),
        ('GALA'),
        ('GAS'),
        ('GBP'),
        ('GENIUS'),
        ('GFT'),
        ('GHST'),
        ('GIGGLE'),
        ('GLM'),
        ('GLMR'),
        ('GLWB'),
        ('GMT'),
        ('GMX'),
        ('GNO'),
        ('GNS'),
        ('GNT'),
        ('GO'),
        ('GOOGLB'),
        ('GPS'),
        ('GRAM'),
        ('GRS'),
        ('GRT'),
        ('GSB'),
        ('GTC'),
        ('GTO'),
        ('GUN'),
        ('GVT'),
        ('GXS'),
        ('HAEDAL'),
        ('HARD'),
        ('HBAR'),
        ('HC'),
        ('HEGIC'),
        ('HEI'),
        ('HEMI'),
        ('HFT'),
        ('HIFI'),
        ('HIGH'),
        ('HIVE'),
        ('HMSTR'),
        ('HNT'),
        ('HOLO'),
        ('HOME'),
        ('HOODB'),
        ('HOOK'),
        ('HOT'),
        ('HSR'),
        ('HUMA'),
        ('HYPER'),
        ('IBMB'),
        ('ICN'),
        ('ICP'),
        ('ICX'),
        ('ID'),
        ('IDEX'),
        ('ILV'),
        ('IMX'),
        ('INIT'),
        ('INJ'),
        ('INS'),
        ('INTCB'),
        ('INTWB'),
        ('IO'),
        ('IOST'),
        ('IOTA'),
        ('IOTX'),
        ('IQ'),
        ('IRIS'),
        ('JASMY'),
        ('JOE'),
        ('JST'),
        ('JTO'),
        ('JUP'),
        ('JUV'),
        ('KAIA'),
        ('KAITO'),
        ('KAT'),
        ('KAVA'),
        ('KDA'),
        ('KEEP'),
        ('KERNEL'),
        ('KEY'),
        ('KGST'),
        ('KITE'),
        ('KLAY'),
        ('KMD'),
        ('KMNO'),
        ('KNC'),
        ('KORUB'),
        ('KP3R'),
        ('KSM'),
        ('LA'),
        ('LAYER'),
        ('LAZIO'),
        ('LDO'),
        ('LEND'),
        ('LEVER'),
        ('LINA'),
        ('LINEA'),
        ('LINK'),
        ('LISTA'),
        ('LIT'),
        ('LITEB'),
        ('LOKA'),
        ('LOOM'),
        ('LPT'),
        ('LQTY'),
        ('LRC'),
        ('LSK'),
        ('LTC'),
        ('LTO'),
        ('LUMIA'),
        ('LUN'),
        ('LUNA'),
        ('LUNC'),
        ('MAGIC'),
        ('MANA'),
        ('MANTA'),
        ('MANTRA'),
        ('MASK'),
        ('MATIC'),
        ('MAV'),
        ('MBL'),
        ('MBOX'),
        ('MC'),
        ('MCO'),
        ('MDA'),
        ('MDT'),
        ('MDX'),
        ('ME'),
        ('MEGA'),
        ('MEME'),
        ('MET'),
        ('METAB'),
        ('METIS'),
        ('MFT'),
        ('MINA'),
        ('MIR'),
        ('MIRA'),
        ('MITH'),
        ('MITO'),
        ('MKR'),
        ('MLN'),
        ('MMT'),
        ('MOB'),
        ('MOD'),
        ('MORPHO'),
        ('MOVE'),
        ('MOVR'),
        ('MRVLB'),
        ('MSFTB'),
        ('MSTRB'),
        ('MTH'),
        ('MTL'),
        ('MUB'),
        ('MUBARAK'),
        ('MULTI'),
        ('MUUB'),
        ('MVLLB'),
        ('NANO'),
        ('NAS'),
        ('NAV'),
        ('NBISB'),
        ('NBS'),
        ('NBT'),
        ('NCASH'),
        ('NEAR'),
        ('NEBL'),
        ('NEIRO'),
        ('NEO'),
        ('NEWT'),
        ('NEXO'),
        ('NFP'),
        ('NIGHT'),
        ('NIL'),
        ('NKN'),
        ('NMR'),
        ('NOKB'),
        ('NOM'),
        ('NOT'),
        ('NPXS'),
        ('NTRN'),
        ('NU'),
        ('NULS'),
        ('NVDAB'),
        ('NXPC'),
        ('NXS'),
        ('OAX'),
        ('OCEAN'),
        ('OG'),
        ('OGN'),
        ('OM'),
        ('OMG'),
        ('OMNI'),
        ('ONDO'),
        ('ONE'),
        ('ONG'),
        ('ONT'),
        ('OOKI'),
        ('OP'),
        ('OPEN'),
        ('OPG'),
        ('OPN'),
        ('ORCA'),
        ('ORCLB'),
        ('ORDI'),
        ('ORN'),
        ('OSMO'),
        ('OST'),
        ('OXT'),
        ('PARTI'),
        ('PAX'),
        ('PAXG'),
        ('PDA'),
        ('PENDLE'),
        ('PENGU'),
        ('PEOPLE'),
        ('PEPE'),
        ('PERL'),
        ('PERP'),
        ('PHA'),
        ('PHB'),
        ('PHX'),
        ('PIVX'),
        ('PIXEL'),
        ('PLA'),
        ('PLTRB'),
        ('PLUME'),
        ('PNT'),
        ('PNUT'),
        ('POA'),
        ('POE'),
        ('POL'),
        ('POLS'),
        ('POLY'),
        ('POLYX'),
        ('POND'),
        ('PORTAL'),
        ('PORTO'),
        ('POWR'),
        ('PPT'),
        ('PROM'),
        ('PROS'),
        ('PROVE'),
        ('PSG'),
        ('PUMP'),
        ('PUNDIX'),
        ('PYPLB'),
        ('PYR'),
        ('PYTH'),
        ('QCOMB'),
        ('QI'),
        ('QKC'),
        ('QLC'),
        ('QNT'),
        ('QNTB'),
        ('QQQB'),
        ('QSP'),
        ('QTUM'),
        ('QUICK'),
        ('RAD'),
        ('RAMP'),
        ('RARE'),
        ('RAY'),
        ('RCN'),
        ('RDN'),
        ('RDNT'),
        ('RE'),
        ('RED'),
        ('REEF'),
        ('REI'),
        ('REN'),
        ('RENBTC'),
        ('RENDER'),
        ('REP'),
        ('REQ'),
        ('RESOLV'),
        ('REZ'),
        ('RGT'),
        ('RIF'),
        ('RKLBB'),
        ('RLC'),
        ('RLUSD'),
        ('RNDR'),
        ('ROBO'),
        ('RONIN'),
        ('ROSE'),
        ('RPL'),
        ('RPX'),
        ('RSR'),
        ('RUNE'),
        ('RVN'),
        ('S'),
        ('SAGA'),
        ('SAHARA'),
        ('SALT'),
        ('SAND'),
        ('SANTOS'),
        ('SAPIEN'),
        ('SC'),
        ('SCR'),
        ('SCRT'),
        ('SEI'),
        ('SENT'),
        ('SFP'),
        ('SHELL'),
        ('SHIB'),
        ('SIGN'),
        ('SKHYB'),
        ('SKL'),
        ('SKY'),
        ('SLF'),
        ('SLP'),
        ('SMHB'),
        ('SNDKB'),
        ('SNGLS'),
        ('SNM'),
        ('SNT'),
        ('SNX'),
        ('SNXXB'),
        ('SOL'),
        ('SOLV'),
        ('SOMI'),
        ('SOPH'),
        ('SOXLB'),
        ('SOXSB'),
        ('SPARTA'),
        ('SPCXB'),
        ('SPELL'),
        ('SPK'),
        ('SPYB'),
        ('SRM'),
        ('SSV'),
        ('STEEM'),
        ('STG'),
        ('STMX'),
        ('STO'),
        ('STORJ'),
        ('STORM'),
        ('STPT'),
        ('STRAT'),
        ('STRAX'),
        ('STRK'),
        ('STX'),
        ('SUB'),
        ('SUI'),
        ('SUN'),
        ('SUPER'),
        ('SUSD'),
        ('SUSHI'),
        ('SWRV'),
        ('SXP'),
        ('SXT'),
        ('SYN'),
        ('SYRUP'),
        ('SYS'),
        ('T'),
        ('TAO'),
        ('TCT'),
        ('TFUEL'),
        ('THE'),
        ('THETA'),
        ('TIA'),
        ('TKO'),
        ('TLM'),
        ('TNB'),
        ('TNSR'),
        ('TNT'),
        ('TOMO'),
        ('TON'),
        ('TORN'),
        ('TOWNS'),
        ('TQQQB'),
        ('TRB'),
        ('TREE'),
        ('TRIBE'),
        ('TRIG'),
        ('TROY'),
        ('TRU'),
        ('TRUMP'),
        ('TRX'),
        ('TSLAB'),
        ('TSMB'),
        ('TST'),
        ('TURBO'),
        ('TURTLE'),
        ('TUSD'),
        ('TUSDB'),
        ('TUT'),
        ('TVK'),
        ('TWT'),
        ('U'),
        ('UFT'),
        ('UMA'),
        ('UNFI'),
        ('UNI'),
        ('USD1'),
        ('USDC'),
        ('USDE'),
        ('USDP'),
        ('USDS'),
        ('USDSB'),
        ('USDT'),
        ('UST'),
        ('USTC'),
        ('USUAL'),
        ('UTK'),
        ('VANA'),
        ('VANRY'),
        ('VELODROME'),
        ('VEN'),
        ('VET'),
        ('VGX'),
        ('VIA'),
        ('VIB'),
        ('VIBE'),
        ('VIC'),
        ('VIDT'),
        ('VIRTUAL'),
        ('VITE'),
        ('VOXEL'),
        ('VTHO'),
        ('W'),
        ('WABI'),
        ('WAL'),
        ('WAN'),
        ('WAVES'),
        ('WAXP'),
        ('WBETH'),
        ('WBTC'),
        ('WCT'),
        ('WDCB'),
        ('WIF'),
        ('WIN'),
        ('WING'),
        ('WINGS'),
        ('WLD'),
        ('WLFI'),
        ('WNXM'),
        ('WOO'),
        ('WPR'),
        ('WRX'),
        ('WTC'),
        ('XAI'),
        ('XAUT'),
        ('XEC'),
        ('XEM'),
        ('XLM'),
        ('XMR'),
        ('XNO'),
        ('XPL'),
        ('XRP'),
        ('XTZ'),
        ('XUSD'),
        ('XVG'),
        ('XVS'),
        ('XZC'),
        ('YB'),
        ('YFI'),
        ('YFII'),
        ('YGG'),
        ('YOYO'),
        ('ZAMA'),
        ('ZBT'),
        ('ZEC'),
        ('ZEN'),
        ('ZIL'),
        ('ZK'),
        ('ZKC'),
        ('ZKP'),
        ('ZRO'),
        ('ZRX'),
        ('币安人生')
    ) AS v(base)
),
excl AS (
    SELECT base FROM bn
    WHERE mod(from_big_endian_32(from_hex('000000' || substr(to_hex(sha256(to_utf8(base))), 1, 2))), 5) = 0
),
cp AS (
    /* 由 pump 程序在迁移交易里创建、池序号为 0 的 PumpSwap 池；建池后储备＝pool_*_amount */
    SELECT pool, min(evt_block_time) AS created_at, max(base_mint) AS mint, max(quote_mint) AS quote_mint,
           max(base_mint_decimals) AS bd, max(quote_mint_decimals) AS qd,
           min_by(evt_block_slot, evt_block_time) AS c_slot, min_by(evt_tx_index, evt_block_time) AS c_txi,
           min_by(evt_outer_instruction_index, evt_block_time) AS c_oix,
           min_by(COALESCE(evt_inner_instruction_index, -1), evt_block_time) AS c_iix,
           min_by(evt_tx_id, evt_block_time) AS c_tx,
           CAST(min_by(pool_quote_amount, evt_block_time) AS DECIMAL(38,0)) AS c_q,
           CAST(min_by(pool_base_amount, evt_block_time) AS DECIMAL(38,0)) AS c_b
    FROM pumpdotfun_solana.pump_amm_evt_createpoolevent
    WHERE evt_block_date BETWEEN DATE '2026-03-26' AND DATE '2026-09-23'
      AND evt_outer_executing_account = '6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P'
      AND index = 0
    GROUP BY 1
),
cand AS (
    SELECT * FROM cp
    WHERE created_at >= TIMESTAMP '2026-09-23 00:00:00' - INTERVAL '180' DAY
      AND created_at < TIMESTAMP '2026-09-23 00:00:00' + INTERVAL '1' DAY
      AND created_at >= TIMESTAMP '2026-09-23 00:00:00' AND created_at < TIMESTAMP '2026-09-23 01:00:00'
),
cc AS (
    /* 曲线创建事件，全历史 */
    SELECT mint, min(evt_block_time) AS curve_created_at, min_by(symbol, evt_block_time) AS symbol
    FROM pumpdotfun_solana.pump_evt_createevent
    WHERE evt_block_date BETWEEN DATE '2024-01-01' AND DATE '2026-09-23'
      AND mint IN (SELECT mint FROM cand)
    GROUP BY 1
),
lab AS (
    /* 互斥类别，按此顺序：无曲线创建 → 封存 → 无代号 → 留出同名 → 纳入 */
    SELECT c.*, s.curve_created_at, s.symbol,
           CASE WHEN s.curve_created_at IS NULL THEN 'no_create'
                WHEN s.curve_created_at >= TIMESTAMP '2026-06-15 00:00:00' AND s.curve_created_at < TIMESTAMP '2026-07-13 00:00:00' THEN 'sealed'
                WHEN s.symbol IS NULL THEN 'no_symbol'
                WHEN upper(trim(replace(s.symbol, '$', ''))) IN (SELECT base FROM excl) THEN 'holdout_name'
                ELSE 'in' END AS cls
    FROM cand c
    LEFT JOIN cc s ON s.mint = c.mint
),
pools AS (SELECT * FROM lab WHERE cls = 'in'),
ic AS (
    SELECT tx_id, block_slot AS slot, tx_index AS txi, outer_instruction_index AS oix, inner_instruction_index AS iix,
           block_time AS ts, data AS b, bytearray_substring(data, 9, 8) AS disc
    FROM solana.instruction_calls
    WHERE block_date BETWEEN DATE '2026-09-23' AND DATE '2026-10-01'
      AND executing_account = 'pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA'
      AND is_inner = true AND tx_success = true
      AND bytearray_substring(data, 1, 8) = 0xe445a52e51cb9a1d
      AND bytearray_substring(data, 9, 8) IN (0x67f4521f2cf57777, 0x3e2f370aa503dc2a, 0xae7c4af90451f611, 0x3f451c16305cc2b9)
),
icp AS (
    SELECT ic.*,
           CASE WHEN disc = 0x67f4521f2cf57777 THEN 446 + CAST(bytearray_to_bigint(reverse(bytearray_substring(b, 410, 4))) AS INTEGER)
                WHEN disc = 0x3e2f370aa503dc2a THEN 401 WHEN disc = 0xae7c4af90451f611 THEN 121 WHEN disc = 0x3f451c16305cc2b9 THEN 177 END AS pv,
           CASE WHEN disc = 0x67f4521f2cf57777 THEN 414 + CAST(bytearray_to_bigint(reverse(bytearray_substring(b, 410, 4))) AS INTEGER) END AS pc
    FROM ic
),
icv AS (
    SELECT icp.*,
           CASE WHEN length(b) >= pv + 15 THEN bytearray_to_bigint(reverse(bytearray_substring(b, pv, 8))) END AS lo_s,
           CASE WHEN length(b) >= pv + 15 THEN bytearray_to_bigint(reverse(bytearray_substring(b, pv + 8, 8))) END AS hi_s
    FROM icp
),
rv AS (
    SELECT tx_id, slot, txi, oix, iix, ts, disc,
           CASE WHEN disc = 0x67f4521f2cf57777 THEN 'B' WHEN disc = 0x3e2f370aa503dc2a THEN 'S' WHEN disc = 0xae7c4af90451f611 THEN 'I' ELSE 'U' END AS kind,
           CASE WHEN hi_s IS NOT NULL AND abs(hi_s) < 4000000000000000000
                THEN CAST(hi_s AS DECIMAL(38,0)) * DECIMAL '18446744073709551616' + CAST(lo_s AS DECIMAL(38,0))
                     + CASE WHEN lo_s < 0 THEN DECIMAL '18446744073709551616' ELSE DECIMAL '0' END END AS vq,
           CASE WHEN hi_s IS NOT NULL AND abs(hi_s) >= 4000000000000000000 THEN 1 ELSE 0 END AS vq_ovf,
           CASE WHEN disc = 0x67f4521f2cf57777 AND length(b) >= pc + 31 THEN CAST(bytearray_to_bigint(reverse(bytearray_substring(b, pc + 8, 8))) AS DECIMAL(38,0)) END AS cb,
           CASE WHEN disc = 0x67f4521f2cf57777 AND length(b) >= pc + 31 THEN CAST(bytearray_to_bigint(reverse(bytearray_substring(b, pc + 24, 8))) AS DECIMAL(38,0)) END AS bb,
           CASE WHEN disc IN (0xae7c4af90451f611, 0x3f451c16305cc2b9) THEN to_base58(bytearray_substring(b, 89, 32)) END AS boost_pool,
           CASE WHEN disc = 0xae7c4af90451f611 THEN CAST(bytearray_to_bigint(reverse(bytearray_substring(b, 137, 8))) AS DECIMAL(38,0))
                WHEN disc = 0x3f451c16305cc2b9 THEN CAST(bytearray_to_bigint(reverse(bytearray_substring(b, 193, 8))) AS DECIMAL(38,0)) END AS boost_q1,
           CASE WHEN disc = 0x3f451c16305cc2b9 THEN CAST(bytearray_to_bigint(reverse(bytearray_substring(b, 201, 8))) AS DECIMAL(38,0)) END AS boost_b1
    FROM icv
),
ev0 AS (
    SELECT pool, evt_block_time AS ts, evt_block_slot AS slot, evt_tx_index AS txi,
           evt_outer_instruction_index AS oix, evt_inner_instruction_index AS iix0, evt_tx_id AS tx_id,
           'B' AS side, "user" AS usr,
           CAST(pool_quote_token_reserves AS DECIMAL(38,0)) AS q0,
           CAST(pool_base_token_reserves AS DECIMAL(38,0)) AS b0,
           CAST(quote_amount_in_with_lp_fee AS DECIMAL(38,0)) AS q_pool,
           CAST(base_amount_out AS DECIMAL(38,0)) AS b_amt,
           CAST(user_quote_amount_in AS DECIMAL(38,0)) AS q_user,
           CAST(lp_fee AS DECIMAL(38,0)) AS f_lp,
           CAST(protocol_fee AS DECIMAL(38,0)) AS f_pr,
           CAST(coin_creator_fee AS DECIMAL(38,0)) AS f_cr,
           CAST(NULL AS DECIMAL(38,0)) AS f_cb0, CAST(NULL AS DECIMAL(38,0)) AS f_bb0,
           CAST(NULL AS DECIMAL(38,0)) AS q_gross_out
    FROM pumpdotfun_solana.pump_amm_evt_buyevent
    WHERE evt_block_date BETWEEN DATE '2026-09-23' AND DATE '2026-10-01'
    UNION ALL
    SELECT pool, evt_block_time, evt_block_slot, evt_tx_index,
           evt_outer_instruction_index, evt_inner_instruction_index, evt_tx_id,
           'S', "user",
           CAST(pool_quote_token_reserves AS DECIMAL(38,0)),
           CAST(pool_base_token_reserves AS DECIMAL(38,0)),
           CAST(quote_amount_out AS DECIMAL(38,0)) - COALESCE(CAST(lp_fee AS DECIMAL(38,0)), 0),
           CAST(base_amount_in AS DECIMAL(38,0)),
           CAST(user_quote_amount_out AS DECIMAL(38,0)),
           CAST(lp_fee AS DECIMAL(38,0)),
           CAST(protocol_fee AS DECIMAL(38,0)),
           CAST(coin_creator_fee AS DECIMAL(38,0)),
           CAST(cashback AS DECIMAL(38,0)),
           CAST(buyback_fee AS DECIMAL(38,0)),
           CAST(quote_amount_out AS DECIMAL(38,0))
    FROM pumpdotfun_solana.pump_amm_evt_sellevent
    WHERE evt_block_date BETWEEN DATE '2026-09-23' AND DATE '2026-10-01'
),
ev AS (
    SELECT e.pool, e.ts, e.slot, e.txi, e.oix, COALESCE(e.iix0, -1) AS iix, e.tx_id, e.side, e.usr,
           e.q0, e.b0, e.q_pool, e.b_amt, e.q_user, e.f_lp, e.f_pr, e.f_cr, e.q_gross_out,
           CASE WHEN e.side = 'S' THEN e.f_cb0 ELSE r.cb END AS f_cb,
           CASE WHEN e.side = 'S' THEN e.f_bb0 ELSE r.bb END AS f_bb,
           CASE WHEN e.ts < TIMESTAMP '2026-07-15 00:00:00' THEN CAST(0 AS DECIMAL(38,0)) ELSE r.vq END AS vq, CASE WHEN e.ts < TIMESTAMP '2026-07-15 00:00:00' THEN 'layout0' WHEN r.tx_id IS NULL THEN 'missing' ELSE 'raw' END AS vq_src, COALESCE(r.vq_ovf, 0) AS vq_ovf
    FROM ev0 e
    LEFT JOIN rv r ON r.tx_id = e.tx_id AND r.oix = e.oix AND r.iix = e.iix0 AND r.kind = e.side
),
k AS (
    SELECT e.*, p.created_at, p.bd, p.qd,
           CASE WHEN e.side = 'B' THEN e.q0 + e.q_pool ELSE e.q0 - e.q_pool END AS q1,
           CASE WHEN e.side = 'B' THEN e.b0 - e.b_amt ELSE e.b0 + e.b_amt END AS b1,
           date_diff('millisecond', p.created_at, e.ts) AS age_ms,
           CAST(e.slot AS BIGINT) * 10000000000 + CAST(e.txi AS BIGINT) * 100000
             + CAST(e.oix AS BIGINT) * 1000 + CAST(e.iix AS BIGINT) AS ord,
           CASE WHEN e.slot IS NULL OR e.txi IS NULL OR e.oix IS NULL OR e.txi >= 100000 OR e.txi < 0
                  OR e.oix >= 100 OR e.oix < 0 OR e.iix >= 1000 OR e.iix < 0
                THEN 1 ELSE 0 END AS ovf,
           /* 卖出交叉核对：整数反解区间，量级受限时不核 */
           CASE WHEN e.side = 'S' AND e.b_amt > 0 AND e.b0 + e.b_amt < DECIMAL '10000000000000000000'
                     AND e.q_gross_out + 1 < DECIMAL '1000000000000000000' THEN
                (e.q_gross_out * (e.b0 + e.b_amt) + e.b_amt - 1
                 - mod(e.q_gross_out * (e.b0 + e.b_amt) + e.b_amt - 1, e.b_amt)) / e.b_amt - e.q0 END AS vlo,
           CASE WHEN e.side = 'S' AND e.b_amt > 0 AND e.b0 + e.b_amt < DECIMAL '10000000000000000000'
                     AND e.q_gross_out + 1 < DECIMAL '1000000000000000000' THEN
                ((e.q_gross_out + 1) * (e.b0 + e.b_amt) + e.b_amt - 1
                 - mod((e.q_gross_out + 1) * (e.b0 + e.b_amt) + e.b_amt - 1, e.b_amt)) / e.b_amt - 1 - e.q0 END AS vhi
    FROM ev e
    JOIN pools p ON p.pool = e.pool
    WHERE e.ts >= p.created_at AND e.ts < p.created_at + INTERVAL '7' DAY
),
lq AS (
    SELECT pool, evt_block_time AS ts, evt_block_slot AS slot, evt_tx_index AS txi, evt_outer_instruction_index AS oix,
           COALESCE(evt_inner_instruction_index, -1) AS iix, evt_tx_id AS tx_id, 'D' AS kind,
           CAST(pool_quote_token_reserves AS DECIMAL(38,0)) AS q0, CAST(pool_base_token_reserves AS DECIMAL(38,0)) AS b0,
           CAST(pool_quote_token_reserves AS DECIMAL(38,0)) + CAST(quote_amount_in AS DECIMAL(38,0)) AS q1,
           CAST(pool_base_token_reserves AS DECIMAL(38,0)) + CAST(base_amount_in AS DECIMAL(38,0)) AS b1
    FROM pumpdotfun_solana.pump_amm_evt_depositevent
    WHERE evt_block_date BETWEEN DATE '2026-09-23' AND DATE '2026-10-01'
    UNION ALL
    SELECT pool, evt_block_time, evt_block_slot, evt_tx_index, evt_outer_instruction_index,
           COALESCE(evt_inner_instruction_index, -1), evt_tx_id, 'W',
           CAST(pool_quote_token_reserves AS DECIMAL(38,0)), CAST(pool_base_token_reserves AS DECIMAL(38,0)),
           CAST(pool_quote_token_reserves AS DECIMAL(38,0)) - CAST(quote_amount_out AS DECIMAL(38,0)),
           CAST(pool_base_token_reserves AS DECIMAL(38,0)) - CAST(base_amount_out AS DECIMAL(38,0))
    FROM pumpdotfun_solana.pump_amm_evt_withdrawevent
    WHERE evt_block_date BETWEEN DATE '2026-09-23' AND DATE '2026-10-01'
),
st AS (
    SELECT pool, created_at, ts, slot, txi, oix, iix, tx_id, side AS kind, q0, b0, q1, b1, vq, age_ms, ord FROM k
    UNION ALL
    SELECT l.pool, p.created_at, l.ts, l.slot, l.txi, l.oix, l.iix, l.tx_id, l.kind, l.q0, l.b0, l.q1, l.b1,
           CAST(NULL AS DECIMAL(38,0)), date_diff('millisecond', p.created_at, l.ts),
           CAST(l.slot AS BIGINT) * 10000000000 + CAST(l.txi AS BIGINT) * 100000 + CAST(l.oix AS BIGINT) * 1000 + CAST(l.iix AS BIGINT)
    FROM lq l JOIN pools p ON p.pool = l.pool
    WHERE l.ts >= p.created_at AND l.ts < p.created_at + INTERVAL '7' DAY
    UNION ALL
    SELECT pool, created_at, created_at, c_slot, c_txi, c_oix, c_iix, c_tx, 'C', CAST(NULL AS DECIMAL(38,0)), CAST(NULL AS DECIMAL(38,0)),
           c_q, c_b, CAST(NULL AS DECIMAL(38,0)), 0,
           CAST(c_slot AS BIGINT) * 10000000000 + CAST(c_txi AS BIGINT) * 100000 + CAST(c_oix AS BIGINT) * 1000 + CAST(c_iix AS BIGINT)
    FROM pools
    UNION ALL
    SELECT r.boost_pool, p.created_at, r.ts, r.slot, r.txi, r.oix, COALESCE(r.iix, -1), r.tx_id, r.kind,
           CAST(NULL AS DECIMAL(38,0)), CAST(NULL AS DECIMAL(38,0)), r.boost_q1, r.boost_b1, r.vq,
           date_diff('millisecond', p.created_at, r.ts),
           CAST(r.slot AS BIGINT) * 10000000000 + CAST(r.txi AS BIGINT) * 100000 + CAST(r.oix AS BIGINT) * 1000 + CAST(COALESCE(r.iix, -1) AS BIGINT)
    FROM rv r JOIN pools p ON p.pool = r.boost_pool
    WHERE r.kind IN ('I', 'U') AND r.ts >= p.created_at AND r.ts < p.created_at + INTERVAL '7' DAY
),
meta AS (
    SELECT mint, min_by(name, evt_block_time) AS name, min_by(uri, evt_block_time) AS uri,
           min_by(COALESCE(creator, "user"), evt_block_time) AS creator,
           min_by(is_mayhem_mode, evt_block_time) AS mayhem, min_by(is_cashback_enabled, evt_block_time) AS cashback,
           min_by(quote_mint, evt_block_time) AS curve_quote_mint
    FROM pumpdotfun_solana.pump_evt_createevent
    WHERE evt_block_date BETWEEN DATE '2024-01-01' AND DATE '2026-09-23'
      AND mint IN (SELECT mint FROM pools)
    GROUP BY 1
),
comp AS (
    SELECT mint, min(evt_block_time) AS completed_at
    FROM pumpdotfun_solana.pump_evt_completeevent
    WHERE evt_block_date BETWEEN DATE '2024-01-01' AND DATE '2026-09-23'
      AND mint IN (SELECT mint FROM pools)
    GROUP BY 1
),
stt AS (
    SELECT st.*,
           created_at + INTERVAL '2' SECOND AS tt2,
           created_at + INTERVAL '10' SECOND AS tt10,
           created_at + INTERVAL '45' SECOND AS tt45,
           created_at + INTERVAL '60' SECOND AS tt60,
           created_at + INTERVAL '75' SECOND AS tt75,
           created_at + INTERVAL '900' SECOND AS tt900,
           created_at + INTERVAL '3600' SECOND AS tt3600,
           created_at + INTERVAL '86400' SECOND AS tt86400
    FROM st
),
sn AS (
    SELECT pool, count_if(kind IN ('B', 'S')) AS n_7d, count_if(kind IN ('D', 'W')) AS n_lp_7d,
           count_if(kind IN ('I', 'U')) AS n_boost_7d,
           CAST(min(vq) AS varchar) AS vq_min_7d, CAST(max(vq) AS varchar) AS vq_max_7d,
       max_by(slot, ord) FILTER (WHERE ts < tt2) AS a2_slot, max_by(txi, ord) FILTER (WHERE ts < tt2) AS a2_txi,
       max_by(oix, ord) FILTER (WHERE ts < tt2) AS a2_oix, max_by(iix, ord) FILTER (WHERE ts < tt2) AS a2_iix,
       max_by(kind, ord) FILTER (WHERE ts < tt2) AS a2_kind, max_by(tx_id, ord) FILTER (WHERE ts < tt2) AS a2_tx,
       CAST(max_by(q1, ord) FILTER (WHERE ts < tt2) AS varchar) AS a2_q1,
       CAST(max_by(b1, ord) FILTER (WHERE ts < tt2) AS varchar) AS a2_b1,
       to_unixtime(max_by(ts, ord) FILTER (WHERE ts < tt2)) AS a2_t,
       CAST(max_by(vq, ord) FILTER (WHERE ts < tt2 AND vq IS NOT NULL) AS varchar) AS vq2,
       count_if(kind IN ('I', 'U') AND ts < tt2) AS nboost2,
       min_by(slot, ord) FILTER (WHERE ts >= tt2) AS b2_slot, min_by(txi, ord) FILTER (WHERE ts >= tt2) AS b2_txi,
       min_by(oix, ord) FILTER (WHERE ts >= tt2) AS b2_oix, min_by(iix, ord) FILTER (WHERE ts >= tt2) AS b2_iix,
       min_by(kind, ord) FILTER (WHERE ts >= tt2) AS b2_kind, min_by(tx_id, ord) FILTER (WHERE ts >= tt2) AS b2_tx,
       CAST(min_by(q0, ord) FILTER (WHERE ts >= tt2) AS varchar) AS b2_q0,
       CAST(min_by(b0, ord) FILTER (WHERE ts >= tt2) AS varchar) AS b2_b0,
       to_unixtime(min_by(ts, ord) FILTER (WHERE ts >= tt2)) AS b2_t,
       max_by(slot, ord) FILTER (WHERE ts < tt10) AS a10_slot, max_by(txi, ord) FILTER (WHERE ts < tt10) AS a10_txi,
       max_by(oix, ord) FILTER (WHERE ts < tt10) AS a10_oix, max_by(iix, ord) FILTER (WHERE ts < tt10) AS a10_iix,
       max_by(kind, ord) FILTER (WHERE ts < tt10) AS a10_kind, max_by(tx_id, ord) FILTER (WHERE ts < tt10) AS a10_tx,
       CAST(max_by(q1, ord) FILTER (WHERE ts < tt10) AS varchar) AS a10_q1,
       CAST(max_by(b1, ord) FILTER (WHERE ts < tt10) AS varchar) AS a10_b1,
       to_unixtime(max_by(ts, ord) FILTER (WHERE ts < tt10)) AS a10_t,
       CAST(max_by(vq, ord) FILTER (WHERE ts < tt10 AND vq IS NOT NULL) AS varchar) AS vq10,
       count_if(kind IN ('I', 'U') AND ts < tt10) AS nboost10,
       min_by(slot, ord) FILTER (WHERE ts >= tt10) AS b10_slot, min_by(txi, ord) FILTER (WHERE ts >= tt10) AS b10_txi,
       min_by(oix, ord) FILTER (WHERE ts >= tt10) AS b10_oix, min_by(iix, ord) FILTER (WHERE ts >= tt10) AS b10_iix,
       min_by(kind, ord) FILTER (WHERE ts >= tt10) AS b10_kind, min_by(tx_id, ord) FILTER (WHERE ts >= tt10) AS b10_tx,
       CAST(min_by(q0, ord) FILTER (WHERE ts >= tt10) AS varchar) AS b10_q0,
       CAST(min_by(b0, ord) FILTER (WHERE ts >= tt10) AS varchar) AS b10_b0,
       to_unixtime(min_by(ts, ord) FILTER (WHERE ts >= tt10)) AS b10_t,
       max_by(slot, ord) FILTER (WHERE ts < tt45) AS a45_slot, max_by(txi, ord) FILTER (WHERE ts < tt45) AS a45_txi,
       max_by(oix, ord) FILTER (WHERE ts < tt45) AS a45_oix, max_by(iix, ord) FILTER (WHERE ts < tt45) AS a45_iix,
       max_by(kind, ord) FILTER (WHERE ts < tt45) AS a45_kind, max_by(tx_id, ord) FILTER (WHERE ts < tt45) AS a45_tx,
       CAST(max_by(q1, ord) FILTER (WHERE ts < tt45) AS varchar) AS a45_q1,
       CAST(max_by(b1, ord) FILTER (WHERE ts < tt45) AS varchar) AS a45_b1,
       to_unixtime(max_by(ts, ord) FILTER (WHERE ts < tt45)) AS a45_t,
       CAST(max_by(vq, ord) FILTER (WHERE ts < tt45 AND vq IS NOT NULL) AS varchar) AS vq45,
       count_if(kind IN ('I', 'U') AND ts < tt45) AS nboost45,
       min_by(slot, ord) FILTER (WHERE ts >= tt45) AS b45_slot, min_by(txi, ord) FILTER (WHERE ts >= tt45) AS b45_txi,
       min_by(oix, ord) FILTER (WHERE ts >= tt45) AS b45_oix, min_by(iix, ord) FILTER (WHERE ts >= tt45) AS b45_iix,
       min_by(kind, ord) FILTER (WHERE ts >= tt45) AS b45_kind, min_by(tx_id, ord) FILTER (WHERE ts >= tt45) AS b45_tx,
       CAST(min_by(q0, ord) FILTER (WHERE ts >= tt45) AS varchar) AS b45_q0,
       CAST(min_by(b0, ord) FILTER (WHERE ts >= tt45) AS varchar) AS b45_b0,
       to_unixtime(min_by(ts, ord) FILTER (WHERE ts >= tt45)) AS b45_t,
       max_by(slot, ord) FILTER (WHERE ts < tt60) AS a60_slot, max_by(txi, ord) FILTER (WHERE ts < tt60) AS a60_txi,
       max_by(oix, ord) FILTER (WHERE ts < tt60) AS a60_oix, max_by(iix, ord) FILTER (WHERE ts < tt60) AS a60_iix,
       max_by(kind, ord) FILTER (WHERE ts < tt60) AS a60_kind, max_by(tx_id, ord) FILTER (WHERE ts < tt60) AS a60_tx,
       CAST(max_by(q1, ord) FILTER (WHERE ts < tt60) AS varchar) AS a60_q1,
       CAST(max_by(b1, ord) FILTER (WHERE ts < tt60) AS varchar) AS a60_b1,
       to_unixtime(max_by(ts, ord) FILTER (WHERE ts < tt60)) AS a60_t,
       CAST(max_by(vq, ord) FILTER (WHERE ts < tt60 AND vq IS NOT NULL) AS varchar) AS vq60,
       count_if(kind IN ('I', 'U') AND ts < tt60) AS nboost60,
       min_by(slot, ord) FILTER (WHERE ts >= tt60) AS b60_slot, min_by(txi, ord) FILTER (WHERE ts >= tt60) AS b60_txi,
       min_by(oix, ord) FILTER (WHERE ts >= tt60) AS b60_oix, min_by(iix, ord) FILTER (WHERE ts >= tt60) AS b60_iix,
       min_by(kind, ord) FILTER (WHERE ts >= tt60) AS b60_kind, min_by(tx_id, ord) FILTER (WHERE ts >= tt60) AS b60_tx,
       CAST(min_by(q0, ord) FILTER (WHERE ts >= tt60) AS varchar) AS b60_q0,
       CAST(min_by(b0, ord) FILTER (WHERE ts >= tt60) AS varchar) AS b60_b0,
       to_unixtime(min_by(ts, ord) FILTER (WHERE ts >= tt60)) AS b60_t,
       max_by(slot, ord) FILTER (WHERE ts < tt75) AS a75_slot, max_by(txi, ord) FILTER (WHERE ts < tt75) AS a75_txi,
       max_by(oix, ord) FILTER (WHERE ts < tt75) AS a75_oix, max_by(iix, ord) FILTER (WHERE ts < tt75) AS a75_iix,
       max_by(kind, ord) FILTER (WHERE ts < tt75) AS a75_kind, max_by(tx_id, ord) FILTER (WHERE ts < tt75) AS a75_tx,
       CAST(max_by(q1, ord) FILTER (WHERE ts < tt75) AS varchar) AS a75_q1,
       CAST(max_by(b1, ord) FILTER (WHERE ts < tt75) AS varchar) AS a75_b1,
       to_unixtime(max_by(ts, ord) FILTER (WHERE ts < tt75)) AS a75_t,
       CAST(max_by(vq, ord) FILTER (WHERE ts < tt75 AND vq IS NOT NULL) AS varchar) AS vq75,
       count_if(kind IN ('I', 'U') AND ts < tt75) AS nboost75,
       min_by(slot, ord) FILTER (WHERE ts >= tt75) AS b75_slot, min_by(txi, ord) FILTER (WHERE ts >= tt75) AS b75_txi,
       min_by(oix, ord) FILTER (WHERE ts >= tt75) AS b75_oix, min_by(iix, ord) FILTER (WHERE ts >= tt75) AS b75_iix,
       min_by(kind, ord) FILTER (WHERE ts >= tt75) AS b75_kind, min_by(tx_id, ord) FILTER (WHERE ts >= tt75) AS b75_tx,
       CAST(min_by(q0, ord) FILTER (WHERE ts >= tt75) AS varchar) AS b75_q0,
       CAST(min_by(b0, ord) FILTER (WHERE ts >= tt75) AS varchar) AS b75_b0,
       to_unixtime(min_by(ts, ord) FILTER (WHERE ts >= tt75)) AS b75_t,
       max_by(slot, ord) FILTER (WHERE ts < tt900) AS a900_slot, max_by(txi, ord) FILTER (WHERE ts < tt900) AS a900_txi,
       max_by(oix, ord) FILTER (WHERE ts < tt900) AS a900_oix, max_by(iix, ord) FILTER (WHERE ts < tt900) AS a900_iix,
       max_by(kind, ord) FILTER (WHERE ts < tt900) AS a900_kind, max_by(tx_id, ord) FILTER (WHERE ts < tt900) AS a900_tx,
       CAST(max_by(q1, ord) FILTER (WHERE ts < tt900) AS varchar) AS a900_q1,
       CAST(max_by(b1, ord) FILTER (WHERE ts < tt900) AS varchar) AS a900_b1,
       to_unixtime(max_by(ts, ord) FILTER (WHERE ts < tt900)) AS a900_t,
       CAST(max_by(vq, ord) FILTER (WHERE ts < tt900 AND vq IS NOT NULL) AS varchar) AS vq900,
       count_if(kind IN ('I', 'U') AND ts < tt900) AS nboost900,
       min_by(slot, ord) FILTER (WHERE ts >= tt900) AS b900_slot, min_by(txi, ord) FILTER (WHERE ts >= tt900) AS b900_txi,
       min_by(oix, ord) FILTER (WHERE ts >= tt900) AS b900_oix, min_by(iix, ord) FILTER (WHERE ts >= tt900) AS b900_iix,
       min_by(kind, ord) FILTER (WHERE ts >= tt900) AS b900_kind, min_by(tx_id, ord) FILTER (WHERE ts >= tt900) AS b900_tx,
       CAST(min_by(q0, ord) FILTER (WHERE ts >= tt900) AS varchar) AS b900_q0,
       CAST(min_by(b0, ord) FILTER (WHERE ts >= tt900) AS varchar) AS b900_b0,
       to_unixtime(min_by(ts, ord) FILTER (WHERE ts >= tt900)) AS b900_t,
       max_by(slot, ord) FILTER (WHERE ts < tt3600) AS a3600_slot, max_by(txi, ord) FILTER (WHERE ts < tt3600) AS a3600_txi,
       max_by(oix, ord) FILTER (WHERE ts < tt3600) AS a3600_oix, max_by(iix, ord) FILTER (WHERE ts < tt3600) AS a3600_iix,
       max_by(kind, ord) FILTER (WHERE ts < tt3600) AS a3600_kind, max_by(tx_id, ord) FILTER (WHERE ts < tt3600) AS a3600_tx,
       CAST(max_by(q1, ord) FILTER (WHERE ts < tt3600) AS varchar) AS a3600_q1,
       CAST(max_by(b1, ord) FILTER (WHERE ts < tt3600) AS varchar) AS a3600_b1,
       to_unixtime(max_by(ts, ord) FILTER (WHERE ts < tt3600)) AS a3600_t,
       CAST(max_by(vq, ord) FILTER (WHERE ts < tt3600 AND vq IS NOT NULL) AS varchar) AS vq3600,
       count_if(kind IN ('I', 'U') AND ts < tt3600) AS nboost3600,
       min_by(slot, ord) FILTER (WHERE ts >= tt3600) AS b3600_slot, min_by(txi, ord) FILTER (WHERE ts >= tt3600) AS b3600_txi,
       min_by(oix, ord) FILTER (WHERE ts >= tt3600) AS b3600_oix, min_by(iix, ord) FILTER (WHERE ts >= tt3600) AS b3600_iix,
       min_by(kind, ord) FILTER (WHERE ts >= tt3600) AS b3600_kind, min_by(tx_id, ord) FILTER (WHERE ts >= tt3600) AS b3600_tx,
       CAST(min_by(q0, ord) FILTER (WHERE ts >= tt3600) AS varchar) AS b3600_q0,
       CAST(min_by(b0, ord) FILTER (WHERE ts >= tt3600) AS varchar) AS b3600_b0,
       to_unixtime(min_by(ts, ord) FILTER (WHERE ts >= tt3600)) AS b3600_t,
       max_by(slot, ord) FILTER (WHERE ts < tt86400) AS a86400_slot, max_by(txi, ord) FILTER (WHERE ts < tt86400) AS a86400_txi,
       max_by(oix, ord) FILTER (WHERE ts < tt86400) AS a86400_oix, max_by(iix, ord) FILTER (WHERE ts < tt86400) AS a86400_iix,
       max_by(kind, ord) FILTER (WHERE ts < tt86400) AS a86400_kind, max_by(tx_id, ord) FILTER (WHERE ts < tt86400) AS a86400_tx,
       CAST(max_by(q1, ord) FILTER (WHERE ts < tt86400) AS varchar) AS a86400_q1,
       CAST(max_by(b1, ord) FILTER (WHERE ts < tt86400) AS varchar) AS a86400_b1,
       to_unixtime(max_by(ts, ord) FILTER (WHERE ts < tt86400)) AS a86400_t,
       CAST(max_by(vq, ord) FILTER (WHERE ts < tt86400 AND vq IS NOT NULL) AS varchar) AS vq86400,
       count_if(kind IN ('I', 'U') AND ts < tt86400) AS nboost86400,
       min_by(slot, ord) FILTER (WHERE ts >= tt86400) AS b86400_slot, min_by(txi, ord) FILTER (WHERE ts >= tt86400) AS b86400_txi,
       min_by(oix, ord) FILTER (WHERE ts >= tt86400) AS b86400_oix, min_by(iix, ord) FILTER (WHERE ts >= tt86400) AS b86400_iix,
       min_by(kind, ord) FILTER (WHERE ts >= tt86400) AS b86400_kind, min_by(tx_id, ord) FILTER (WHERE ts >= tt86400) AS b86400_tx,
       CAST(min_by(q0, ord) FILTER (WHERE ts >= tt86400) AS varchar) AS b86400_q0,
       CAST(min_by(b0, ord) FILTER (WHERE ts >= tt86400) AS varchar) AS b86400_b0,
       to_unixtime(min_by(ts, ord) FILTER (WHERE ts >= tt86400)) AS b86400_t
    FROM stt
    GROUP BY 1
)
SELECT 'solana' AS chain, p.pool, p.mint, p.quote_mint,
       CASE WHEN p.quote_mint = 'So11111111111111111111111111111111111111112' THEN 'SOL' WHEN p.quote_mint = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v' THEN 'USDC' ELSE 'OTHER' END AS quote_class,
       p.bd, p.qd, to_unixtime(p.created_at) AS created_t,
       p.c_slot, p.c_txi, p.c_oix, p.c_iix, p.c_tx, CAST(p.c_q AS varchar) AS c_q, CAST(p.c_b AS varchar) AS c_b,
       to_unixtime(p.curve_created_at) AS curve_created_t, to_unixtime(cm.completed_at) AS curve_completed_t,
       p.symbol, m.name, m.uri, m.creator, m.mayhem, m.cashback, m.curve_quote_mint,
       p.created_at + INTERVAL '7' DAY <= TIMESTAMP '2026-10-04 00:00:00' + INTERVAL '1' DAY AS mature_7d,
       sn.n_7d, sn.n_lp_7d, sn.n_boost_7d, sn.vq_min_7d, sn.vq_max_7d, sn.a2_slot, sn.a2_txi, sn.a2_oix, sn.a2_iix, sn.a2_kind, sn.a2_tx, sn.a2_q1, sn.a2_b1, sn.a2_t, sn.vq2, sn.nboost2, sn.b2_slot, sn.b2_txi, sn.b2_oix, sn.b2_iix, sn.b2_kind, sn.b2_tx, sn.b2_q0, sn.b2_b0, sn.b2_t, sn.a10_slot, sn.a10_txi, sn.a10_oix, sn.a10_iix, sn.a10_kind, sn.a10_tx, sn.a10_q1, sn.a10_b1, sn.a10_t, sn.vq10, sn.nboost10, sn.b10_slot, sn.b10_txi, sn.b10_oix, sn.b10_iix, sn.b10_kind, sn.b10_tx, sn.b10_q0, sn.b10_b0, sn.b10_t, sn.a45_slot, sn.a45_txi, sn.a45_oix, sn.a45_iix, sn.a45_kind, sn.a45_tx, sn.a45_q1, sn.a45_b1, sn.a45_t, sn.vq45, sn.nboost45, sn.b45_slot, sn.b45_txi, sn.b45_oix, sn.b45_iix, sn.b45_kind, sn.b45_tx, sn.b45_q0, sn.b45_b0, sn.b45_t, sn.a60_slot, sn.a60_txi, sn.a60_oix, sn.a60_iix, sn.a60_kind, sn.a60_tx, sn.a60_q1, sn.a60_b1, sn.a60_t, sn.vq60, sn.nboost60, sn.b60_slot, sn.b60_txi, sn.b60_oix, sn.b60_iix, sn.b60_kind, sn.b60_tx, sn.b60_q0, sn.b60_b0, sn.b60_t, sn.a75_slot, sn.a75_txi, sn.a75_oix, sn.a75_iix, sn.a75_kind, sn.a75_tx, sn.a75_q1, sn.a75_b1, sn.a75_t, sn.vq75, sn.nboost75, sn.b75_slot, sn.b75_txi, sn.b75_oix, sn.b75_iix, sn.b75_kind, sn.b75_tx, sn.b75_q0, sn.b75_b0, sn.b75_t, sn.a900_slot, sn.a900_txi, sn.a900_oix, sn.a900_iix, sn.a900_kind, sn.a900_tx, sn.a900_q1, sn.a900_b1, sn.a900_t, sn.vq900, sn.nboost900, sn.b900_slot, sn.b900_txi, sn.b900_oix, sn.b900_iix, sn.b900_kind, sn.b900_tx, sn.b900_q0, sn.b900_b0, sn.b900_t, sn.a3600_slot, sn.a3600_txi, sn.a3600_oix, sn.a3600_iix, sn.a3600_kind, sn.a3600_tx, sn.a3600_q1, sn.a3600_b1, sn.a3600_t, sn.vq3600, sn.nboost3600, sn.b3600_slot, sn.b3600_txi, sn.b3600_oix, sn.b3600_iix, sn.b3600_kind, sn.b3600_tx, sn.b3600_q0, sn.b3600_b0, sn.b3600_t, sn.a86400_slot, sn.a86400_txi, sn.a86400_oix, sn.a86400_iix, sn.a86400_kind, sn.a86400_tx, sn.a86400_q1, sn.a86400_b1, sn.a86400_t, sn.vq86400, sn.nboost86400, sn.b86400_slot, sn.b86400_txi, sn.b86400_oix, sn.b86400_iix, sn.b86400_kind, sn.b86400_tx, sn.b86400_q0, sn.b86400_b0, sn.b86400_t,
       to_unixtime(p.created_at + INTERVAL '2' SECOND) AS target2_time, sn.a2_t AS state2_time, sn.a2_t AS known2_at, CASE WHEN p.created_at + INTERVAL '2' SECOND >= TIMESTAMP '2026-10-04 00:00:00' + INTERVAL '1' DAY THEN 'immature' WHEN sn.a2_kind = 'I' THEN 'partial' WHEN sn.b2_slot IS NULL THEN 'no_next' WHEN sn.a2_q1 IS NULL OR sn.a2_b1 IS NULL OR sn.b2_q0 IS NULL OR sn.b2_b0 IS NULL THEN 'unverified' WHEN sn.a2_q1 IS DISTINCT FROM sn.b2_q0 OR sn.a2_b1 IS DISTINCT FROM sn.b2_b0 THEN 'gap' ELSE 'ok' END AS coverage2, (CASE WHEN p.created_at + INTERVAL '2' SECOND >= TIMESTAMP '2026-10-04 00:00:00' + INTERVAL '1' DAY THEN 'immature' WHEN sn.a2_kind = 'I' THEN 'partial' WHEN sn.b2_slot IS NULL THEN 'no_next' WHEN sn.a2_q1 IS NULL OR sn.a2_b1 IS NULL OR sn.b2_q0 IS NULL OR sn.b2_b0 IS NULL THEN 'unverified' WHEN sn.a2_q1 IS DISTINCT FROM sn.b2_q0 OR sn.a2_b1 IS DISTINCT FROM sn.b2_b0 THEN 'gap' ELSE 'ok' END) <> 'ok' AS gap2_flag,
       to_unixtime(p.created_at + INTERVAL '10' SECOND) AS target10_time, sn.a10_t AS state10_time, sn.a10_t AS known10_at, CASE WHEN p.created_at + INTERVAL '10' SECOND >= TIMESTAMP '2026-10-04 00:00:00' + INTERVAL '1' DAY THEN 'immature' WHEN sn.a10_kind = 'I' THEN 'partial' WHEN sn.b10_slot IS NULL THEN 'no_next' WHEN sn.a10_q1 IS NULL OR sn.a10_b1 IS NULL OR sn.b10_q0 IS NULL OR sn.b10_b0 IS NULL THEN 'unverified' WHEN sn.a10_q1 IS DISTINCT FROM sn.b10_q0 OR sn.a10_b1 IS DISTINCT FROM sn.b10_b0 THEN 'gap' ELSE 'ok' END AS coverage10, (CASE WHEN p.created_at + INTERVAL '10' SECOND >= TIMESTAMP '2026-10-04 00:00:00' + INTERVAL '1' DAY THEN 'immature' WHEN sn.a10_kind = 'I' THEN 'partial' WHEN sn.b10_slot IS NULL THEN 'no_next' WHEN sn.a10_q1 IS NULL OR sn.a10_b1 IS NULL OR sn.b10_q0 IS NULL OR sn.b10_b0 IS NULL THEN 'unverified' WHEN sn.a10_q1 IS DISTINCT FROM sn.b10_q0 OR sn.a10_b1 IS DISTINCT FROM sn.b10_b0 THEN 'gap' ELSE 'ok' END) <> 'ok' AS gap10_flag,
       to_unixtime(p.created_at + INTERVAL '45' SECOND) AS target45_time, sn.a45_t AS state45_time, sn.a45_t AS known45_at, CASE WHEN p.created_at + INTERVAL '45' SECOND >= TIMESTAMP '2026-10-04 00:00:00' + INTERVAL '1' DAY THEN 'immature' WHEN sn.a45_kind = 'I' THEN 'partial' WHEN sn.b45_slot IS NULL THEN 'no_next' WHEN sn.a45_q1 IS NULL OR sn.a45_b1 IS NULL OR sn.b45_q0 IS NULL OR sn.b45_b0 IS NULL THEN 'unverified' WHEN sn.a45_q1 IS DISTINCT FROM sn.b45_q0 OR sn.a45_b1 IS DISTINCT FROM sn.b45_b0 THEN 'gap' ELSE 'ok' END AS coverage45, (CASE WHEN p.created_at + INTERVAL '45' SECOND >= TIMESTAMP '2026-10-04 00:00:00' + INTERVAL '1' DAY THEN 'immature' WHEN sn.a45_kind = 'I' THEN 'partial' WHEN sn.b45_slot IS NULL THEN 'no_next' WHEN sn.a45_q1 IS NULL OR sn.a45_b1 IS NULL OR sn.b45_q0 IS NULL OR sn.b45_b0 IS NULL THEN 'unverified' WHEN sn.a45_q1 IS DISTINCT FROM sn.b45_q0 OR sn.a45_b1 IS DISTINCT FROM sn.b45_b0 THEN 'gap' ELSE 'ok' END) <> 'ok' AS gap45_flag,
       to_unixtime(p.created_at + INTERVAL '60' SECOND) AS target60_time, sn.a60_t AS state60_time, sn.a60_t AS known60_at, CASE WHEN p.created_at + INTERVAL '60' SECOND >= TIMESTAMP '2026-10-04 00:00:00' + INTERVAL '1' DAY THEN 'immature' WHEN sn.a60_kind = 'I' THEN 'partial' WHEN sn.b60_slot IS NULL THEN 'no_next' WHEN sn.a60_q1 IS NULL OR sn.a60_b1 IS NULL OR sn.b60_q0 IS NULL OR sn.b60_b0 IS NULL THEN 'unverified' WHEN sn.a60_q1 IS DISTINCT FROM sn.b60_q0 OR sn.a60_b1 IS DISTINCT FROM sn.b60_b0 THEN 'gap' ELSE 'ok' END AS coverage60, (CASE WHEN p.created_at + INTERVAL '60' SECOND >= TIMESTAMP '2026-10-04 00:00:00' + INTERVAL '1' DAY THEN 'immature' WHEN sn.a60_kind = 'I' THEN 'partial' WHEN sn.b60_slot IS NULL THEN 'no_next' WHEN sn.a60_q1 IS NULL OR sn.a60_b1 IS NULL OR sn.b60_q0 IS NULL OR sn.b60_b0 IS NULL THEN 'unverified' WHEN sn.a60_q1 IS DISTINCT FROM sn.b60_q0 OR sn.a60_b1 IS DISTINCT FROM sn.b60_b0 THEN 'gap' ELSE 'ok' END) <> 'ok' AS gap60_flag,
       to_unixtime(p.created_at + INTERVAL '75' SECOND) AS target75_time, sn.a75_t AS state75_time, sn.a75_t AS known75_at, CASE WHEN p.created_at + INTERVAL '75' SECOND >= TIMESTAMP '2026-10-04 00:00:00' + INTERVAL '1' DAY THEN 'immature' WHEN sn.a75_kind = 'I' THEN 'partial' WHEN sn.b75_slot IS NULL THEN 'no_next' WHEN sn.a75_q1 IS NULL OR sn.a75_b1 IS NULL OR sn.b75_q0 IS NULL OR sn.b75_b0 IS NULL THEN 'unverified' WHEN sn.a75_q1 IS DISTINCT FROM sn.b75_q0 OR sn.a75_b1 IS DISTINCT FROM sn.b75_b0 THEN 'gap' ELSE 'ok' END AS coverage75, (CASE WHEN p.created_at + INTERVAL '75' SECOND >= TIMESTAMP '2026-10-04 00:00:00' + INTERVAL '1' DAY THEN 'immature' WHEN sn.a75_kind = 'I' THEN 'partial' WHEN sn.b75_slot IS NULL THEN 'no_next' WHEN sn.a75_q1 IS NULL OR sn.a75_b1 IS NULL OR sn.b75_q0 IS NULL OR sn.b75_b0 IS NULL THEN 'unverified' WHEN sn.a75_q1 IS DISTINCT FROM sn.b75_q0 OR sn.a75_b1 IS DISTINCT FROM sn.b75_b0 THEN 'gap' ELSE 'ok' END) <> 'ok' AS gap75_flag,
       to_unixtime(p.created_at + INTERVAL '900' SECOND) AS target900_time, sn.a900_t AS state900_time, sn.a900_t AS known900_at, CASE WHEN p.created_at + INTERVAL '900' SECOND >= TIMESTAMP '2026-10-04 00:00:00' + INTERVAL '1' DAY THEN 'immature' WHEN sn.a900_kind = 'I' THEN 'partial' WHEN sn.b900_slot IS NULL THEN 'no_next' WHEN sn.a900_q1 IS NULL OR sn.a900_b1 IS NULL OR sn.b900_q0 IS NULL OR sn.b900_b0 IS NULL THEN 'unverified' WHEN sn.a900_q1 IS DISTINCT FROM sn.b900_q0 OR sn.a900_b1 IS DISTINCT FROM sn.b900_b0 THEN 'gap' ELSE 'ok' END AS coverage900, (CASE WHEN p.created_at + INTERVAL '900' SECOND >= TIMESTAMP '2026-10-04 00:00:00' + INTERVAL '1' DAY THEN 'immature' WHEN sn.a900_kind = 'I' THEN 'partial' WHEN sn.b900_slot IS NULL THEN 'no_next' WHEN sn.a900_q1 IS NULL OR sn.a900_b1 IS NULL OR sn.b900_q0 IS NULL OR sn.b900_b0 IS NULL THEN 'unverified' WHEN sn.a900_q1 IS DISTINCT FROM sn.b900_q0 OR sn.a900_b1 IS DISTINCT FROM sn.b900_b0 THEN 'gap' ELSE 'ok' END) <> 'ok' AS gap900_flag,
       to_unixtime(p.created_at + INTERVAL '3600' SECOND) AS target3600_time, sn.a3600_t AS state3600_time, sn.a3600_t AS known3600_at, CASE WHEN p.created_at + INTERVAL '3600' SECOND >= TIMESTAMP '2026-10-04 00:00:00' + INTERVAL '1' DAY THEN 'immature' WHEN sn.a3600_kind = 'I' THEN 'partial' WHEN sn.b3600_slot IS NULL THEN 'no_next' WHEN sn.a3600_q1 IS NULL OR sn.a3600_b1 IS NULL OR sn.b3600_q0 IS NULL OR sn.b3600_b0 IS NULL THEN 'unverified' WHEN sn.a3600_q1 IS DISTINCT FROM sn.b3600_q0 OR sn.a3600_b1 IS DISTINCT FROM sn.b3600_b0 THEN 'gap' ELSE 'ok' END AS coverage3600, (CASE WHEN p.created_at + INTERVAL '3600' SECOND >= TIMESTAMP '2026-10-04 00:00:00' + INTERVAL '1' DAY THEN 'immature' WHEN sn.a3600_kind = 'I' THEN 'partial' WHEN sn.b3600_slot IS NULL THEN 'no_next' WHEN sn.a3600_q1 IS NULL OR sn.a3600_b1 IS NULL OR sn.b3600_q0 IS NULL OR sn.b3600_b0 IS NULL THEN 'unverified' WHEN sn.a3600_q1 IS DISTINCT FROM sn.b3600_q0 OR sn.a3600_b1 IS DISTINCT FROM sn.b3600_b0 THEN 'gap' ELSE 'ok' END) <> 'ok' AS gap3600_flag,
       to_unixtime(p.created_at + INTERVAL '86400' SECOND) AS target86400_time, sn.a86400_t AS state86400_time, sn.a86400_t AS known86400_at, CASE WHEN p.created_at + INTERVAL '86400' SECOND >= TIMESTAMP '2026-10-04 00:00:00' + INTERVAL '1' DAY THEN 'immature' WHEN sn.a86400_kind = 'I' THEN 'partial' WHEN sn.b86400_slot IS NULL THEN 'no_next' WHEN sn.a86400_q1 IS NULL OR sn.a86400_b1 IS NULL OR sn.b86400_q0 IS NULL OR sn.b86400_b0 IS NULL THEN 'unverified' WHEN sn.a86400_q1 IS DISTINCT FROM sn.b86400_q0 OR sn.a86400_b1 IS DISTINCT FROM sn.b86400_b0 THEN 'gap' ELSE 'ok' END AS coverage86400, (CASE WHEN p.created_at + INTERVAL '86400' SECOND >= TIMESTAMP '2026-10-04 00:00:00' + INTERVAL '1' DAY THEN 'immature' WHEN sn.a86400_kind = 'I' THEN 'partial' WHEN sn.b86400_slot IS NULL THEN 'no_next' WHEN sn.a86400_q1 IS NULL OR sn.a86400_b1 IS NULL OR sn.b86400_q0 IS NULL OR sn.b86400_b0 IS NULL THEN 'unverified' WHEN sn.a86400_q1 IS DISTINCT FROM sn.b86400_q0 OR sn.a86400_b1 IS DISTINCT FROM sn.b86400_b0 THEN 'gap' ELSE 'ok' END) <> 'ok' AS gap86400_flag
FROM pools p
LEFT JOIN meta m ON m.mint = p.mint
LEFT JOIN comp cm ON cm.mint = p.mint
LEFT JOIN sn ON sn.pool = p.pool
WHERE p.created_at >= TIMESTAMP '2026-09-23 00:00:00' AND p.created_at < TIMESTAMP '2026-09-23 00:00:00' + INTERVAL '1' DAY
