/* DQ-35 v2.1 数据留存（10-04，执行模型）：层 B；pump 迁移池在 2025-10-07～2025-10-13 的事件；只存不分析；由 build_grad_sql_v21.py 生成 */
WITH
bn(base) AS (
    /* 币安现货全部 746 个基础资产名（Probe L 母表 u_trade，公开信息）；留出按 sha256(baseAsset) 首字节 mod 5 == 0 在下面计算 */
    SELECT base FROM (VALUES
        ('0G'),
        ('1000CAT'),
        ('1000CHEEMS'),
        ('1000SATS'),
        ('1INCH'),
        ('1MBABYDOGE'),
        ('2Z'),
        ('A'),
        ('A2Z'),
        ('AAOIB'),
        ('AAPLB'),
        ('AAVE'),
        ('ACA'),
        ('ACE'),
        ('ACH'),
        ('ACM'),
        ('ACT'),
        ('ACX'),
        ('ADA'),
        ('ADX'),
        ('AE'),
        ('AERGO'),
        ('AERO'),
        ('AEUR'),
        ('AEVO'),
        ('AGI'),
        ('AGIX'),
        ('AGLD'),
        ('AI'),
        ('AIGENSYN'),
        ('AION'),
        ('AIXBT'),
        ('AKRO'),
        ('ALCX'),
        ('ALGO'),
        ('ALICE'),
        ('ALLO'),
        ('ALPACA'),
        ('ALPHA'),
        ('ALPINE'),
        ('ALT'),
        ('AMATB'),
        ('AMB'),
        ('AMDB'),
        ('AMP'),
        ('AMZNB'),
        ('ANC'),
        ('ANIME'),
        ('ANKR'),
        ('ANT'),
        ('ANY'),
        ('APE'),
        ('API3'),
        ('APPC'),
        ('APT'),
        ('AR'),
        ('ARB'),
        ('ARDR'),
        ('ARK'),
        ('ARKM'),
        ('ARMB'),
        ('ARN'),
        ('ARPA'),
        ('ASR'),
        ('AST'),
        ('ASTER'),
        ('ASTR'),
        ('AT'),
        ('ATA'),
        ('ATM'),
        ('ATOM'),
        ('AUCTION'),
        ('AUD'),
        ('AUDIO'),
        ('AUTO'),
        ('AVA'),
        ('AVAX'),
        ('AVGOB'),
        ('AVNT'),
        ('AWE'),
        ('AXL'),
        ('AXS'),
        ('AXTIB'),
        ('BABAB'),
        ('BABY'),
        ('BADGER'),
        ('BAKE'),
        ('BAL'),
        ('BANANA'),
        ('BANANAS31'),
        ('BAND'),
        ('BANK'),
        ('BAR'),
        ('BARD'),
        ('BAT'),
        ('BB'),
        ('BCC'),
        ('BCD'),
        ('BCH'),
        ('BCHA'),
        ('BCHABC'),
        ('BCHSV'),
        ('BCN'),
        ('BCPT'),
        ('BDOT'),
        ('BEAM'),
        ('BEAMX'),
        ('BEAR'),
        ('BEB'),
        ('BEL'),
        ('BERA'),
        ('BETA'),
        ('BETH'),
        ('BFUSD'),
        ('BGBP'),
        ('BICO'),
        ('BIFI'),
        ('BIGTIME'),
        ('BIO'),
        ('BKRW'),
        ('BLUR'),
        ('BLZ'),
        ('BMT'),
        ('BNB'),
        ('BNSOL'),
        ('BNT'),
        ('BNX'),
        ('BOME'),
        ('BOND'),
        ('BONK'),
        ('BOT'),
        ('BQX'),
        ('BRD'),
        ('BREV'),
        ('BROCCOLI714'),
        ('BSW'),
        ('BTC'),
        ('BTCB'),
        ('BTCST'),
        ('BTG'),
        ('BTS'),
        ('BTT'),
        ('BTTC'),
        ('BULL'),
        ('BURGER'),
        ('BUSD'),
        ('BZRX'),
        ('C'),
        ('C98'),
        ('CAKE'),
        ('CATI'),
        ('CBRSB'),
        ('CDT'),
        ('CELO'),
        ('CELR'),
        ('CETUS'),
        ('CFG'),
        ('CFX'),
        ('CGPT'),
        ('CHAT'),
        ('CHESS'),
        ('CHIP'),
        ('CHR'),
        ('CHZ'),
        ('CITY'),
        ('CKB'),
        ('CLOAK'),
        ('CLV'),
        ('CMT'),
        ('CND'),
        ('COCOS'),
        ('COINB'),
        ('COMBO'),
        ('COMP'),
        ('COOKIE'),
        ('COS'),
        ('COTI'),
        ('COVER'),
        ('COW'),
        ('CRCLB'),
        ('CREAM'),
        ('CRV'),
        ('CRWVB'),
        ('CTK'),
        ('CTSI'),
        ('CTXC'),
        ('CVC'),
        ('CVP'),
        ('CVX'),
        ('CYBER'),
        ('D'),
        ('DAI'),
        ('DAR'),
        ('DASH'),
        ('DATA'),
        ('DCR'),
        ('DEGO'),
        ('DELLB'),
        ('DENT'),
        ('DEXE'),
        ('DF'),
        ('DGB'),
        ('DGD'),
        ('DIA'),
        ('DLT'),
        ('DNT'),
        ('DOCK'),
        ('DODO'),
        ('DOGE'),
        ('DOGS'),
        ('DOLO'),
        ('DOT'),
        ('DRAMB'),
        ('DREP'),
        ('DUSK'),
        ('DYDX'),
        ('DYM'),
        ('EASY'),
        ('EDEN'),
        ('EDO'),
        ('EDU'),
        ('EGLD'),
        ('EIGEN'),
        ('ELF'),
        ('ENA'),
        ('ENG'),
        ('ENJ'),
        ('ENS'),
        ('ENSO'),
        ('EOS'),
        ('EPIC'),
        ('EPS'),
        ('EPX'),
        ('ERA'),
        ('ERD'),
        ('ERN'),
        ('ESP'),
        ('ETC'),
        ('ETH'),
        ('ETHFI'),
        ('EUL'),
        ('EUR'),
        ('EURI'),
        ('EVX'),
        ('EWYB'),
        ('EZ'),
        ('F'),
        ('FARM'),
        ('FDUSD'),
        ('FET'),
        ('FF'),
        ('FIDA'),
        ('FIL'),
        ('FIO'),
        ('FIRO'),
        ('FIS'),
        ('FLM'),
        ('FLNCB'),
        ('FLOKI'),
        ('FLOW'),
        ('FLUX'),
        ('FOGO'),
        ('FOR'),
        ('FORM'),
        ('FORTH'),
        ('FRAX'),
        ('FRONT'),
        ('FTM'),
        ('FTT'),
        ('FUEL'),
        ('FUN'),
        ('FXS'),
        ('G'),
        ('GAL'),
        ('GALA'),
        ('GAS'),
        ('GBP'),
        ('GENIUS'),
        ('GFT'),
        ('GHST'),
        ('GIGGLE'),
        ('GLM'),
        ('GLMR'),
        ('GLWB'),
        ('GMT'),
        ('GMX'),
        ('GNO'),
        ('GNS'),
        ('GNT'),
        ('GO'),
        ('GOOGLB'),
        ('GPS'),
        ('GRAM'),
        ('GRS'),
        ('GRT'),
        ('GSB'),
        ('GTC'),
        ('GTO'),
        ('GUN'),
        ('GVT'),
        ('GXS'),
        ('HAEDAL'),
        ('HARD'),
        ('HBAR'),
        ('HC'),
        ('HEGIC'),
        ('HEI'),
        ('HEMI'),
        ('HFT'),
        ('HIFI'),
        ('HIGH'),
        ('HIVE'),
        ('HMSTR'),
        ('HNT'),
        ('HOLO'),
        ('HOME'),
        ('HOODB'),
        ('HOOK'),
        ('HOT'),
        ('HSR'),
        ('HUMA'),
        ('HYPER'),
        ('IBMB'),
        ('ICN'),
        ('ICP'),
        ('ICX'),
        ('ID'),
        ('IDEX'),
        ('ILV'),
        ('IMX'),
        ('INIT'),
        ('INJ'),
        ('INS'),
        ('INTCB'),
        ('INTWB'),
        ('IO'),
        ('IOST'),
        ('IOTA'),
        ('IOTX'),
        ('IQ'),
        ('IRIS'),
        ('JASMY'),
        ('JOE'),
        ('JST'),
        ('JTO'),
        ('JUP'),
        ('JUV'),
        ('KAIA'),
        ('KAITO'),
        ('KAT'),
        ('KAVA'),
        ('KDA'),
        ('KEEP'),
        ('KERNEL'),
        ('KEY'),
        ('KGST'),
        ('KITE'),
        ('KLAY'),
        ('KMD'),
        ('KMNO'),
        ('KNC'),
        ('KORUB'),
        ('KP3R'),
        ('KSM'),
        ('LA'),
        ('LAYER'),
        ('LAZIO'),
        ('LDO'),
        ('LEND'),
        ('LEVER'),
        ('LINA'),
        ('LINEA'),
        ('LINK'),
        ('LISTA'),
        ('LIT'),
        ('LITEB'),
        ('LOKA'),
        ('LOOM'),
        ('LPT'),
        ('LQTY'),
        ('LRC'),
        ('LSK'),
        ('LTC'),
        ('LTO'),
        ('LUMIA'),
        ('LUN'),
        ('LUNA'),
        ('LUNC'),
        ('MAGIC'),
        ('MANA'),
        ('MANTA'),
        ('MANTRA'),
        ('MASK'),
        ('MATIC'),
        ('MAV'),
        ('MBL'),
        ('MBOX'),
        ('MC'),
        ('MCO'),
        ('MDA'),
        ('MDT'),
        ('MDX'),
        ('ME'),
        ('MEGA'),
        ('MEME'),
        ('MET'),
        ('METAB'),
        ('METIS'),
        ('MFT'),
        ('MINA'),
        ('MIR'),
        ('MIRA'),
        ('MITH'),
        ('MITO'),
        ('MKR'),
        ('MLN'),
        ('MMT'),
        ('MOB'),
        ('MOD'),
        ('MORPHO'),
        ('MOVE'),
        ('MOVR'),
        ('MRVLB'),
        ('MSFTB'),
        ('MSTRB'),
        ('MTH'),
        ('MTL'),
        ('MUB'),
        ('MUBARAK'),
        ('MULTI'),
        ('MUUB'),
        ('MVLLB'),
        ('NANO'),
        ('NAS'),
        ('NAV'),
        ('NBISB'),
        ('NBS'),
        ('NBT'),
        ('NCASH'),
        ('NEAR'),
        ('NEBL'),
        ('NEIRO'),
        ('NEO'),
        ('NEWT'),
        ('NEXO'),
        ('NFP'),
        ('NIGHT'),
        ('NIL'),
        ('NKN'),
        ('NMR'),
        ('NOKB'),
        ('NOM'),
        ('NOT'),
        ('NPXS'),
        ('NTRN'),
        ('NU'),
        ('NULS'),
        ('NVDAB'),
        ('NXPC'),
        ('NXS'),
        ('OAX'),
        ('OCEAN'),
        ('OG'),
        ('OGN'),
        ('OM'),
        ('OMG'),
        ('OMNI'),
        ('ONDO'),
        ('ONE'),
        ('ONG'),
        ('ONT'),
        ('OOKI'),
        ('OP'),
        ('OPEN'),
        ('OPG'),
        ('OPN'),
        ('ORCA'),
        ('ORCLB'),
        ('ORDI'),
        ('ORN'),
        ('OSMO'),
        ('OST'),
        ('OXT'),
        ('PARTI'),
        ('PAX'),
        ('PAXG'),
        ('PDA'),
        ('PENDLE'),
        ('PENGU'),
        ('PEOPLE'),
        ('PEPE'),
        ('PERL'),
        ('PERP'),
        ('PHA'),
        ('PHB'),
        ('PHX'),
        ('PIVX'),
        ('PIXEL'),
        ('PLA'),
        ('PLTRB'),
        ('PLUME'),
        ('PNT'),
        ('PNUT'),
        ('POA'),
        ('POE'),
        ('POL'),
        ('POLS'),
        ('POLY'),
        ('POLYX'),
        ('POND'),
        ('PORTAL'),
        ('PORTO'),
        ('POWR'),
        ('PPT'),
        ('PROM'),
        ('PROS'),
        ('PROVE'),
        ('PSG'),
        ('PUMP'),
        ('PUNDIX'),
        ('PYPLB'),
        ('PYR'),
        ('PYTH'),
        ('QCOMB'),
        ('QI'),
        ('QKC'),
        ('QLC'),
        ('QNT'),
        ('QNTB'),
        ('QQQB'),
        ('QSP'),
        ('QTUM'),
        ('QUICK'),
        ('RAD'),
        ('RAMP'),
        ('RARE'),
        ('RAY'),
        ('RCN'),
        ('RDN'),
        ('RDNT'),
        ('RE'),
        ('RED'),
        ('REEF'),
        ('REI'),
        ('REN'),
        ('RENBTC'),
        ('RENDER'),
        ('REP'),
        ('REQ'),
        ('RESOLV'),
        ('REZ'),
        ('RGT'),
        ('RIF'),
        ('RKLBB'),
        ('RLC'),
        ('RLUSD'),
        ('RNDR'),
        ('ROBO'),
        ('RONIN'),
        ('ROSE'),
        ('RPL'),
        ('RPX'),
        ('RSR'),
        ('RUNE'),
        ('RVN'),
        ('S'),
        ('SAGA'),
        ('SAHARA'),
        ('SALT'),
        ('SAND'),
        ('SANTOS'),
        ('SAPIEN'),
        ('SC'),
        ('SCR'),
        ('SCRT'),
        ('SEI'),
        ('SENT'),
        ('SFP'),
        ('SHELL'),
        ('SHIB'),
        ('SIGN'),
        ('SKHYB'),
        ('SKL'),
        ('SKY'),
        ('SLF'),
        ('SLP'),
        ('SMHB'),
        ('SNDKB'),
        ('SNGLS'),
        ('SNM'),
        ('SNT'),
        ('SNX'),
        ('SNXXB'),
        ('SOL'),
        ('SOLV'),
        ('SOMI'),
        ('SOPH'),
        ('SOXLB'),
        ('SOXSB'),
        ('SPARTA'),
        ('SPCXB'),
        ('SPELL'),
        ('SPK'),
        ('SPYB'),
        ('SRM'),
        ('SSV'),
        ('STEEM'),
        ('STG'),
        ('STMX'),
        ('STO'),
        ('STORJ'),
        ('STORM'),
        ('STPT'),
        ('STRAT'),
        ('STRAX'),
        ('STRK'),
        ('STX'),
        ('SUB'),
        ('SUI'),
        ('SUN'),
        ('SUPER'),
        ('SUSD'),
        ('SUSHI'),
        ('SWRV'),
        ('SXP'),
        ('SXT'),
        ('SYN'),
        ('SYRUP'),
        ('SYS'),
        ('T'),
        ('TAO'),
        ('TCT'),
        ('TFUEL'),
        ('THE'),
        ('THETA'),
        ('TIA'),
        ('TKO'),
        ('TLM'),
        ('TNB'),
        ('TNSR'),
        ('TNT'),
        ('TOMO'),
        ('TON'),
        ('TORN'),
        ('TOWNS'),
        ('TQQQB'),
        ('TRB'),
        ('TREE'),
        ('TRIBE'),
        ('TRIG'),
        ('TROY'),
        ('TRU'),
        ('TRUMP'),
        ('TRX'),
        ('TSLAB'),
        ('TSMB'),
        ('TST'),
        ('TURBO'),
        ('TURTLE'),
        ('TUSD'),
        ('TUSDB'),
        ('TUT'),
        ('TVK'),
        ('TWT'),
        ('U'),
        ('UFT'),
        ('UMA'),
        ('UNFI'),
        ('UNI'),
        ('USD1'),
        ('USDC'),
        ('USDE'),
        ('USDP'),
        ('USDS'),
        ('USDSB'),
        ('USDT'),
        ('UST'),
        ('USTC'),
        ('USUAL'),
        ('UTK'),
        ('VANA'),
        ('VANRY'),
        ('VELODROME'),
        ('VEN'),
        ('VET'),
        ('VGX'),
        ('VIA'),
        ('VIB'),
        ('VIBE'),
        ('VIC'),
        ('VIDT'),
        ('VIRTUAL'),
        ('VITE'),
        ('VOXEL'),
        ('VTHO'),
        ('W'),
        ('WABI'),
        ('WAL'),
        ('WAN'),
        ('WAVES'),
        ('WAXP'),
        ('WBETH'),
        ('WBTC'),
        ('WCT'),
        ('WDCB'),
        ('WIF'),
        ('WIN'),
        ('WING'),
        ('WINGS'),
        ('WLD'),
        ('WLFI'),
        ('WNXM'),
        ('WOO'),
        ('WPR'),
        ('WRX'),
        ('WTC'),
        ('XAI'),
        ('XAUT'),
        ('XEC'),
        ('XEM'),
        ('XLM'),
        ('XMR'),
        ('XNO'),
        ('XPL'),
        ('XRP'),
        ('XTZ'),
        ('XUSD'),
        ('XVG'),
        ('XVS'),
        ('XZC'),
        ('YB'),
        ('YFI'),
        ('YFII'),
        ('YGG'),
        ('YOYO'),
        ('ZAMA'),
        ('ZBT'),
        ('ZEC'),
        ('ZEN'),
        ('ZIL'),
        ('ZK'),
        ('ZKC'),
        ('ZKP'),
        ('ZRO'),
        ('ZRX'),
        ('币安人生')
    ) AS v(base)
),
excl AS (
    SELECT base FROM bn
    WHERE mod(from_big_endian_32(from_hex('000000' || substr(to_hex(sha256(to_utf8(base))), 1, 2))), 5) = 0
),
cp AS (
    /* 由 pump 程序在迁移交易里创建、池序号为 0 的 PumpSwap 池 */
    SELECT pool, min(evt_block_time) AS created_at, max(base_mint) AS mint, max(quote_mint) AS quote_mint,
           max(base_mint_decimals) AS bd, max(quote_mint_decimals) AS qd,
           min_by(evt_block_slot, evt_block_time) AS c_slot, min_by(evt_tx_index, evt_block_time) AS c_txi,
           min_by(evt_outer_instruction_index, evt_block_time) AS c_oix,
           min_by(COALESCE(evt_inner_instruction_index, -1), evt_block_time) AS c_iix,
           min_by(evt_tx_id, evt_block_time) AS c_tx
    FROM pumpdotfun_solana.pump_amm_evt_createpoolevent
    WHERE evt_block_date BETWEEN DATE '2025-04-09' AND DATE '2025-10-13'
      AND evt_outer_executing_account = '6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P'
      AND index = 0
    GROUP BY 1
),
cand AS (
    SELECT * FROM cp
    WHERE created_at >= TIMESTAMP '2025-10-07 00:00:00' - INTERVAL '180' DAY
      AND created_at < TIMESTAMP '2025-10-13 00:00:00' + INTERVAL '1' DAY
      AND created_at >= TIMESTAMP '2025-10-07 00:00:00' AND created_at < TIMESTAMP '2025-10-07 03:00:00'
),
cc AS (
    /* 曲线创建事件，全历史 */
    SELECT mint, min(evt_block_time) AS curve_created_at, min_by(symbol, evt_block_time) AS symbol
    FROM pumpdotfun_solana.pump_evt_createevent
    WHERE evt_block_date BETWEEN DATE '2024-01-01' AND DATE '2025-10-13'
      AND mint IN (SELECT mint FROM cand)
    GROUP BY 1
),
pools AS (
    SELECT c.*, s.curve_created_at, s.symbol
    FROM cand c
    JOIN cc s ON s.mint = c.mint
    WHERE NOT (s.curve_created_at >= TIMESTAMP '2026-06-15 00:00:00' AND s.curve_created_at < TIMESTAMP '2026-07-13 00:00:00')
      AND upper(trim(replace(s.symbol, '$', ''))) NOT IN (SELECT base FROM excl)
),
ev AS (
    SELECT pool, evt_block_time AS ts, evt_block_slot AS slot, evt_tx_index AS txi,
           evt_outer_instruction_index AS oix, COALESCE(evt_inner_instruction_index, -1) AS iix,
           'B' AS side, "user" AS usr,
           CAST(pool_quote_token_reserves AS DECIMAL(38,0)) AS q0,
           CAST(pool_base_token_reserves AS DECIMAL(38,0)) AS b0,
           CAST(quote_amount_in_with_lp_fee AS DECIMAL(38,0)) AS q_pool,
           CAST(base_amount_out AS DECIMAL(38,0)) AS b_amt,
           CAST(user_quote_amount_in AS DECIMAL(38,0)) AS q_user,
           CAST(lp_fee AS DECIMAL(38,0)) AS f_lp,
           CAST(protocol_fee AS DECIMAL(38,0)) AS f_pr,
           CAST(coin_creator_fee AS DECIMAL(38,0)) AS f_cr,
           CAST(NULL AS DECIMAL(38,0)) AS f_cb, CAST(NULL AS DECIMAL(38,0)) AS f_bb,
           CAST(NULL AS DECIMAL(38,0)) AS q_gross_out
    FROM pumpdotfun_solana.pump_amm_evt_buyevent
    WHERE evt_block_date BETWEEN DATE '2025-10-07' AND DATE '2025-10-13'
    UNION ALL
    SELECT pool, evt_block_time, evt_block_slot, evt_tx_index,
           evt_outer_instruction_index, COALESCE(evt_inner_instruction_index, -1),
           'S', "user",
           CAST(pool_quote_token_reserves AS DECIMAL(38,0)),
           CAST(pool_base_token_reserves AS DECIMAL(38,0)),
           CAST(quote_amount_out AS DECIMAL(38,0)) - COALESCE(CAST(lp_fee AS DECIMAL(38,0)), 0),
           CAST(base_amount_in AS DECIMAL(38,0)),
           CAST(user_quote_amount_out AS DECIMAL(38,0)),
           CAST(lp_fee AS DECIMAL(38,0)),
           CAST(protocol_fee AS DECIMAL(38,0)),
           CAST(coin_creator_fee AS DECIMAL(38,0)),
           CAST(cashback AS DECIMAL(38,0)),
           CAST(buyback_fee AS DECIMAL(38,0)),
           CAST(quote_amount_out AS DECIMAL(38,0))
    FROM pumpdotfun_solana.pump_amm_evt_sellevent
    WHERE evt_block_date BETWEEN DATE '2025-10-07' AND DATE '2025-10-13'
),
k AS (
    SELECT e.*, p.created_at, p.bd, p.qd,
           CASE WHEN e.side = 'B' THEN e.q0 + e.q_pool ELSE e.q0 - e.q_pool END AS q1,
           CASE WHEN e.side = 'B' THEN e.b0 - e.b_amt ELSE e.b0 + e.b_amt END AS b1,
           date_diff('millisecond', p.created_at, e.ts) AS age_ms,
           CAST(e.slot AS BIGINT) * 10000000000 + CAST(e.txi AS BIGINT) * 100000
             + CAST(e.oix AS BIGINT) * 1000 + CAST(e.iix AS BIGINT) AS ord,
           CASE WHEN e.txi >= 100000 OR e.oix >= 100 OR e.iix >= 1000 OR e.iix < 0 OR e.oix IS NULL
                THEN 1 ELSE 0 END AS ovf,
           /* 卖出反解 vq：ceil(a/d)＝(a＋d−1 − mod(a＋d−1, d))/d，全程整数 */
           CASE WHEN e.side = 'S' AND e.b_amt > 0 THEN
                (e.q_gross_out * (e.b0 + e.b_amt) + e.b_amt - 1
                 - mod(e.q_gross_out * (e.b0 + e.b_amt) + e.b_amt - 1, e.b_amt)) / e.b_amt - e.q0 END AS vlo,
           CASE WHEN e.side = 'S' AND e.b_amt > 0 THEN
                ((e.q_gross_out + 1) * (e.b0 + e.b_amt) + e.b_amt - 1
                 - mod((e.q_gross_out + 1) * (e.b0 + e.b_amt) + e.b_amt - 1, e.b_amt)) / e.b_amt - 1 - e.q0 END AS vhi
    FROM ev e
    JOIN pools p ON p.pool = e.pool
    WHERE e.ts >= p.created_at AND e.ts < p.created_at + INTERVAL '180' DAY
),
kp AS (
    SELECT k.*, max(vlo) OVER (PARTITION BY pool) AS pvlo, min(vhi) OVER (PARTITION BY pool) AS pvhi
    FROM k
),
kb AS (
    SELECT kp.*,
           CASE WHEN age_ms < 300000 THEN 'S' WHEN age_ms < 3600000 THEN 'M'
                WHEN age_ms < 604800000 THEN 'H' ELSE 'D' END AS kind,
           CASE WHEN age_ms < 300000 THEN floor(age_ms / 5000e0)
                WHEN age_ms < 3600000 THEN floor(age_ms / 60000e0)
                WHEN age_ms < 604800000 THEN floor(age_ms / 3600000e0)
                ELSE floor(age_ms / 86400000e0) END AS bkey,
           CASE WHEN age_ms < 300000 THEN 5 WHEN age_ms < 3600000 THEN 60
                WHEN age_ms < 604800000 THEN 3600 ELSE 86400 END AS w,
           CASE WHEN pvlo <= pvhi
                THEN ((CAST(q1 AS DOUBLE) + (CAST(pvlo AS DOUBLE) + CAST(pvhi AS DOUBLE)) / 2) / power(10, qd))
                     / nullif(CAST(b1 AS DOUBLE) / power(10, bd), 0) END AS px
    FROM kp
),
kbs AS (
    SELECT kb.*,
           CASE WHEN created_at + bkey * w * INTERVAL '1' SECOND < TIMESTAMP '2025-10-07 00:00:00'
                  OR created_at + (bkey + 1) * w * INTERVAL '1' SECOND > TIMESTAMP '2025-10-13 00:00:00' + INTERVAL '1' DAY
                THEN true ELSE false END AS straddle
    FROM kb
)
SELECT kind, pool, CAST(bkey AS BIGINT) AS bkey, straddle,
       count(*) AS n, count_if(side = 'B') AS n_buy, approx_distinct(usr) AS n_users,
       array_join(array_sort(array_distinct(array_agg(usr) FILTER (WHERE straddle))), ',') AS users_straddle,
       CAST(sum(CASE WHEN side = 'B' THEN q_user ELSE 0 END) AS varchar) AS q_buy_user,
       CAST(sum(CASE WHEN side = 'S' THEN q_user ELSE 0 END) AS varchar) AS q_sell_user,
       CAST(sum(CASE WHEN side = 'B' THEN q_pool ELSE 0 END) AS varchar) AS q_buy_pool,
       CAST(sum(CASE WHEN side = 'S' THEN q_pool ELSE 0 END) AS varchar) AS q_sell_pool,
       CAST(sum(CASE WHEN side = 'B' THEN b_amt ELSE 0 END) AS varchar) AS b_buy,
       CAST(sum(CASE WHEN side = 'S' THEN b_amt ELSE 0 END) AS varchar) AS b_sell,
       CAST(sum(f_lp) AS varchar) AS f_lp, CAST(sum(f_pr) AS varchar) AS f_pr, CAST(sum(f_cr) AS varchar) AS f_cr,
       CAST(sum(f_cb) AS varchar) AS f_cb_sell, CAST(sum(f_bb) AS varchar) AS f_bb_sell,
       count_if(f_lp IS NULL OR f_pr IS NULL OR f_cr IS NULL) AS n_fee_null,
       min_by(slot, ord) AS slot_f, min_by(txi, ord) AS txi_f, min_by(oix, ord) AS oix_f, min_by(iix, ord) AS iix_f,
       max_by(slot, ord) AS slot_l, max_by(txi, ord) AS txi_l, max_by(oix, ord) AS oix_l, max_by(iix, ord) AS iix_l,
       CAST(min_by(q0, ord) AS varchar) AS q0_open, CAST(min_by(b0, ord) AS varchar) AS b0_open, min_by(side, ord) AS side_first,
       CAST(max_by(q1, ord) AS varchar) AS q1_close, CAST(max_by(b1, ord) AS varchar) AS b1_close, max_by(side, ord) AS side_last,
       CAST(max_by(q_pool, ord) AS varchar) AS q_pool_last, CAST(max_by(b_amt, ord) AS varchar) AS b_amt_last,
       CAST(max(vlo) AS varchar) AS vq_lo, CAST(min(vhi) AS varchar) AS vq_hi, count(vlo) AS n_vq_obs,
       max(px) AS px_high, min(px) AS px_low, count_if(px IS NULL) AS n_px_unknown,
       to_unixtime(min(ts)) AS t_first, to_unixtime(max(ts)) AS t_last,
       sum(ovf) AS n_ord_overflow
FROM kbs
GROUP BY 1, 2, 3, 4
