/* DQ-35 v2.1 数据留存（10-04，执行模型）：层 P；pump 迁移池在 2026-07-13～2026-07-13 的事件；只存不分析；由 build_grad_sql_v21.py 生成 */
WITH
bn(base) AS (
    /* 币安现货全部 746 个基础资产名（Probe L 母表 u_trade，公开信息）；留出按 sha256(baseAsset) 首字节 mod 5 == 0 在下面计算 */
    SELECT base FROM (VALUES
        ('0G'),
        ('1000CAT'),
        ('1000CHEEMS'),
        ('1000SATS'),
        ('1INCH'),
        ('1MBABYDOGE'),
        ('2Z'),
        ('A'),
        ('A2Z'),
        ('AAOIB'),
        ('AAPLB'),
        ('AAVE'),
        ('ACA'),
        ('ACE'),
        ('ACH'),
        ('ACM'),
        ('ACT'),
        ('ACX'),
        ('ADA'),
        ('ADX'),
        ('AE'),
        ('AERGO'),
        ('AERO'),
        ('AEUR'),
        ('AEVO'),
        ('AGI'),
        ('AGIX'),
        ('AGLD'),
        ('AI'),
        ('AIGENSYN'),
        ('AION'),
        ('AIXBT'),
        ('AKRO'),
        ('ALCX'),
        ('ALGO'),
        ('ALICE'),
        ('ALLO'),
        ('ALPACA'),
        ('ALPHA'),
        ('ALPINE'),
        ('ALT'),
        ('AMATB'),
        ('AMB'),
        ('AMDB'),
        ('AMP'),
        ('AMZNB'),
        ('ANC'),
        ('ANIME'),
        ('ANKR'),
        ('ANT'),
        ('ANY'),
        ('APE'),
        ('API3'),
        ('APPC'),
        ('APT'),
        ('AR'),
        ('ARB'),
        ('ARDR'),
        ('ARK'),
        ('ARKM'),
        ('ARMB'),
        ('ARN'),
        ('ARPA'),
        ('ASR'),
        ('AST'),
        ('ASTER'),
        ('ASTR'),
        ('AT'),
        ('ATA'),
        ('ATM'),
        ('ATOM'),
        ('AUCTION'),
        ('AUD'),
        ('AUDIO'),
        ('AUTO'),
        ('AVA'),
        ('AVAX'),
        ('AVGOB'),
        ('AVNT'),
        ('AWE'),
        ('AXL'),
        ('AXS'),
        ('AXTIB'),
        ('BABAB'),
        ('BABY'),
        ('BADGER'),
        ('BAKE'),
        ('BAL'),
        ('BANANA'),
        ('BANANAS31'),
        ('BAND'),
        ('BANK'),
        ('BAR'),
        ('BARD'),
        ('BAT'),
        ('BB'),
        ('BCC'),
        ('BCD'),
        ('BCH'),
        ('BCHA'),
        ('BCHABC'),
        ('BCHSV'),
        ('BCN'),
        ('BCPT'),
        ('BDOT'),
        ('BEAM'),
        ('BEAMX'),
        ('BEAR'),
        ('BEB'),
        ('BEL'),
        ('BERA'),
        ('BETA'),
        ('BETH'),
        ('BFUSD'),
        ('BGBP'),
        ('BICO'),
        ('BIFI'),
        ('BIGTIME'),
        ('BIO'),
        ('BKRW'),
        ('BLUR'),
        ('BLZ'),
        ('BMT'),
        ('BNB'),
        ('BNSOL'),
        ('BNT'),
        ('BNX'),
        ('BOME'),
        ('BOND'),
        ('BONK'),
        ('BOT'),
        ('BQX'),
        ('BRD'),
        ('BREV'),
        ('BROCCOLI714'),
        ('BSW'),
        ('BTC'),
        ('BTCB'),
        ('BTCST'),
        ('BTG'),
        ('BTS'),
        ('BTT'),
        ('BTTC'),
        ('BULL'),
        ('BURGER'),
        ('BUSD'),
        ('BZRX'),
        ('C'),
        ('C98'),
        ('CAKE'),
        ('CATI'),
        ('CBRSB'),
        ('CDT'),
        ('CELO'),
        ('CELR'),
        ('CETUS'),
        ('CFG'),
        ('CFX'),
        ('CGPT'),
        ('CHAT'),
        ('CHESS'),
        ('CHIP'),
        ('CHR'),
        ('CHZ'),
        ('CITY'),
        ('CKB'),
        ('CLOAK'),
        ('CLV'),
        ('CMT'),
        ('CND'),
        ('COCOS'),
        ('COINB'),
        ('COMBO'),
        ('COMP'),
        ('COOKIE'),
        ('COS'),
        ('COTI'),
        ('COVER'),
        ('COW'),
        ('CRCLB'),
        ('CREAM'),
        ('CRV'),
        ('CRWVB'),
        ('CTK'),
        ('CTSI'),
        ('CTXC'),
        ('CVC'),
        ('CVP'),
        ('CVX'),
        ('CYBER'),
        ('D'),
        ('DAI'),
        ('DAR'),
        ('DASH'),
        ('DATA'),
        ('DCR'),
        ('DEGO'),
        ('DELLB'),
        ('DENT'),
        ('DEXE'),
        ('DF'),
        ('DGB'),
        ('DGD'),
        ('DIA'),
        ('DLT'),
        ('DNT'),
        ('DOCK'),
        ('DODO'),
        ('DOGE'),
        ('DOGS'),
        ('DOLO'),
        ('DOT'),
        ('DRAMB'),
        ('DREP'),
        ('DUSK'),
        ('DYDX'),
        ('DYM'),
        ('EASY'),
        ('EDEN'),
        ('EDO'),
        ('EDU'),
        ('EGLD'),
        ('EIGEN'),
        ('ELF'),
        ('ENA'),
        ('ENG'),
        ('ENJ'),
        ('ENS'),
        ('ENSO'),
        ('EOS'),
        ('EPIC'),
        ('EPS'),
        ('EPX'),
        ('ERA'),
        ('ERD'),
        ('ERN'),
        ('ESP'),
        ('ETC'),
        ('ETH'),
        ('ETHFI'),
        ('EUL'),
        ('EUR'),
        ('EURI'),
        ('EVX'),
        ('EWYB'),
        ('EZ'),
        ('F'),
        ('FARM'),
        ('FDUSD'),
        ('FET'),
        ('FF'),
        ('FIDA'),
        ('FIL'),
        ('FIO'),
        ('FIRO'),
        ('FIS'),
        ('FLM'),
        ('FLNCB'),
        ('FLOKI'),
        ('FLOW'),
        ('FLUX'),
        ('FOGO'),
        ('FOR'),
        ('FORM'),
        ('FORTH'),
        ('FRAX'),
        ('FRONT'),
        ('FTM'),
        ('FTT'),
        ('FUEL'),
        ('FUN'),
        ('FXS'),
        ('G'),
        ('GAL'),
        ('GALA'),
        ('GAS'),
        ('GBP'),
        ('GENIUS'),
        ('GFT'),
        ('GHST'),
        ('GIGGLE'),
        ('GLM'),
        ('GLMR'),
        ('GLWB'),
        ('GMT'),
        ('GMX'),
        ('GNO'),
        ('GNS'),
        ('GNT'),
        ('GO'),
        ('GOOGLB'),
        ('GPS'),
        ('GRAM'),
        ('GRS'),
        ('GRT'),
        ('GSB'),
        ('GTC'),
        ('GTO'),
        ('GUN'),
        ('GVT'),
        ('GXS'),
        ('HAEDAL'),
        ('HARD'),
        ('HBAR'),
        ('HC'),
        ('HEGIC'),
        ('HEI'),
        ('HEMI'),
        ('HFT'),
        ('HIFI'),
        ('HIGH'),
        ('HIVE'),
        ('HMSTR'),
        ('HNT'),
        ('HOLO'),
        ('HOME'),
        ('HOODB'),
        ('HOOK'),
        ('HOT'),
        ('HSR'),
        ('HUMA'),
        ('HYPER'),
        ('IBMB'),
        ('ICN'),
        ('ICP'),
        ('ICX'),
        ('ID'),
        ('IDEX'),
        ('ILV'),
        ('IMX'),
        ('INIT'),
        ('INJ'),
        ('INS'),
        ('INTCB'),
        ('INTWB'),
        ('IO'),
        ('IOST'),
        ('IOTA'),
        ('IOTX'),
        ('IQ'),
        ('IRIS'),
        ('JASMY'),
        ('JOE'),
        ('JST'),
        ('JTO'),
        ('JUP'),
        ('JUV'),
        ('KAIA'),
        ('KAITO'),
        ('KAT'),
        ('KAVA'),
        ('KDA'),
        ('KEEP'),
        ('KERNEL'),
        ('KEY'),
        ('KGST'),
        ('KITE'),
        ('KLAY'),
        ('KMD'),
        ('KMNO'),
        ('KNC'),
        ('KORUB'),
        ('KP3R'),
        ('KSM'),
        ('LA'),
        ('LAYER'),
        ('LAZIO'),
        ('LDO'),
        ('LEND'),
        ('LEVER'),
        ('LINA'),
        ('LINEA'),
        ('LINK'),
        ('LISTA'),
        ('LIT'),
        ('LITEB'),
        ('LOKA'),
        ('LOOM'),
        ('LPT'),
        ('LQTY'),
        ('LRC'),
        ('LSK'),
        ('LTC'),
        ('LTO'),
        ('LUMIA'),
        ('LUN'),
        ('LUNA'),
        ('LUNC'),
        ('MAGIC'),
        ('MANA'),
        ('MANTA'),
        ('MANTRA'),
        ('MASK'),
        ('MATIC'),
        ('MAV'),
        ('MBL'),
        ('MBOX'),
        ('MC'),
        ('MCO'),
        ('MDA'),
        ('MDT'),
        ('MDX'),
        ('ME'),
        ('MEGA'),
        ('MEME'),
        ('MET'),
        ('METAB'),
        ('METIS'),
        ('MFT'),
        ('MINA'),
        ('MIR'),
        ('MIRA'),
        ('MITH'),
        ('MITO'),
        ('MKR'),
        ('MLN'),
        ('MMT'),
        ('MOB'),
        ('MOD'),
        ('MORPHO'),
        ('MOVE'),
        ('MOVR'),
        ('MRVLB'),
        ('MSFTB'),
        ('MSTRB'),
        ('MTH'),
        ('MTL'),
        ('MUB'),
        ('MUBARAK'),
        ('MULTI'),
        ('MUUB'),
        ('MVLLB'),
        ('NANO'),
        ('NAS'),
        ('NAV'),
        ('NBISB'),
        ('NBS'),
        ('NBT'),
        ('NCASH'),
        ('NEAR'),
        ('NEBL'),
        ('NEIRO'),
        ('NEO'),
        ('NEWT'),
        ('NEXO'),
        ('NFP'),
        ('NIGHT'),
        ('NIL'),
        ('NKN'),
        ('NMR'),
        ('NOKB'),
        ('NOM'),
        ('NOT'),
        ('NPXS'),
        ('NTRN'),
        ('NU'),
        ('NULS'),
        ('NVDAB'),
        ('NXPC'),
        ('NXS'),
        ('OAX'),
        ('OCEAN'),
        ('OG'),
        ('OGN'),
        ('OM'),
        ('OMG'),
        ('OMNI'),
        ('ONDO'),
        ('ONE'),
        ('ONG'),
        ('ONT'),
        ('OOKI'),
        ('OP'),
        ('OPEN'),
        ('OPG'),
        ('OPN'),
        ('ORCA'),
        ('ORCLB'),
        ('ORDI'),
        ('ORN'),
        ('OSMO'),
        ('OST'),
        ('OXT'),
        ('PARTI'),
        ('PAX'),
        ('PAXG'),
        ('PDA'),
        ('PENDLE'),
        ('PENGU'),
        ('PEOPLE'),
        ('PEPE'),
        ('PERL'),
        ('PERP'),
        ('PHA'),
        ('PHB'),
        ('PHX'),
        ('PIVX'),
        ('PIXEL'),
        ('PLA'),
        ('PLTRB'),
        ('PLUME'),
        ('PNT'),
        ('PNUT'),
        ('POA'),
        ('POE'),
        ('POL'),
        ('POLS'),
        ('POLY'),
        ('POLYX'),
        ('POND'),
        ('PORTAL'),
        ('PORTO'),
        ('POWR'),
        ('PPT'),
        ('PROM'),
        ('PROS'),
        ('PROVE'),
        ('PSG'),
        ('PUMP'),
        ('PUNDIX'),
        ('PYPLB'),
        ('PYR'),
        ('PYTH'),
        ('QCOMB'),
        ('QI'),
        ('QKC'),
        ('QLC'),
        ('QNT'),
        ('QNTB'),
        ('QQQB'),
        ('QSP'),
        ('QTUM'),
        ('QUICK'),
        ('RAD'),
        ('RAMP'),
        ('RARE'),
        ('RAY'),
        ('RCN'),
        ('RDN'),
        ('RDNT'),
        ('RE'),
        ('RED'),
        ('REEF'),
        ('REI'),
        ('REN'),
        ('RENBTC'),
        ('RENDER'),
        ('REP'),
        ('REQ'),
        ('RESOLV'),
        ('REZ'),
        ('RGT'),
        ('RIF'),
        ('RKLBB'),
        ('RLC'),
        ('RLUSD'),
        ('RNDR'),
        ('ROBO'),
        ('RONIN'),
        ('ROSE'),
        ('RPL'),
        ('RPX'),
        ('RSR'),
        ('RUNE'),
        ('RVN'),
        ('S'),
        ('SAGA'),
        ('SAHARA'),
        ('SALT'),
        ('SAND'),
        ('SANTOS'),
        ('SAPIEN'),
        ('SC'),
        ('SCR'),
        ('SCRT'),
        ('SEI'),
        ('SENT'),
        ('SFP'),
        ('SHELL'),
        ('SHIB'),
        ('SIGN'),
        ('SKHYB'),
        ('SKL'),
        ('SKY'),
        ('SLF'),
        ('SLP'),
        ('SMHB'),
        ('SNDKB'),
        ('SNGLS'),
        ('SNM'),
        ('SNT'),
        ('SNX'),
        ('SNXXB'),
        ('SOL'),
        ('SOLV'),
        ('SOMI'),
        ('SOPH'),
        ('SOXLB'),
        ('SOXSB'),
        ('SPARTA'),
        ('SPCXB'),
        ('SPELL'),
        ('SPK'),
        ('SPYB'),
        ('SRM'),
        ('SSV'),
        ('STEEM'),
        ('STG'),
        ('STMX'),
        ('STO'),
        ('STORJ'),
        ('STORM'),
        ('STPT'),
        ('STRAT'),
        ('STRAX'),
        ('STRK'),
        ('STX'),
        ('SUB'),
        ('SUI'),
        ('SUN'),
        ('SUPER'),
        ('SUSD'),
        ('SUSHI'),
        ('SWRV'),
        ('SXP'),
        ('SXT'),
        ('SYN'),
        ('SYRUP'),
        ('SYS'),
        ('T'),
        ('TAO'),
        ('TCT'),
        ('TFUEL'),
        ('THE'),
        ('THETA'),
        ('TIA'),
        ('TKO'),
        ('TLM'),
        ('TNB'),
        ('TNSR'),
        ('TNT'),
        ('TOMO'),
        ('TON'),
        ('TORN'),
        ('TOWNS'),
        ('TQQQB'),
        ('TRB'),
        ('TREE'),
        ('TRIBE'),
        ('TRIG'),
        ('TROY'),
        ('TRU'),
        ('TRUMP'),
        ('TRX'),
        ('TSLAB'),
        ('TSMB'),
        ('TST'),
        ('TURBO'),
        ('TURTLE'),
        ('TUSD'),
        ('TUSDB'),
        ('TUT'),
        ('TVK'),
        ('TWT'),
        ('U'),
        ('UFT'),
        ('UMA'),
        ('UNFI'),
        ('UNI'),
        ('USD1'),
        ('USDC'),
        ('USDE'),
        ('USDP'),
        ('USDS'),
        ('USDSB'),
        ('USDT'),
        ('UST'),
        ('USTC'),
        ('USUAL'),
        ('UTK'),
        ('VANA'),
        ('VANRY'),
        ('VELODROME'),
        ('VEN'),
        ('VET'),
        ('VGX'),
        ('VIA'),
        ('VIB'),
        ('VIBE'),
        ('VIC'),
        ('VIDT'),
        ('VIRTUAL'),
        ('VITE'),
        ('VOXEL'),
        ('VTHO'),
        ('W'),
        ('WABI'),
        ('WAL'),
        ('WAN'),
        ('WAVES'),
        ('WAXP'),
        ('WBETH'),
        ('WBTC'),
        ('WCT'),
        ('WDCB'),
        ('WIF'),
        ('WIN'),
        ('WING'),
        ('WINGS'),
        ('WLD'),
        ('WLFI'),
        ('WNXM'),
        ('WOO'),
        ('WPR'),
        ('WRX'),
        ('WTC'),
        ('XAI'),
        ('XAUT'),
        ('XEC'),
        ('XEM'),
        ('XLM'),
        ('XMR'),
        ('XNO'),
        ('XPL'),
        ('XRP'),
        ('XTZ'),
        ('XUSD'),
        ('XVG'),
        ('XVS'),
        ('XZC'),
        ('YB'),
        ('YFI'),
        ('YFII'),
        ('YGG'),
        ('YOYO'),
        ('ZAMA'),
        ('ZBT'),
        ('ZEC'),
        ('ZEN'),
        ('ZIL'),
        ('ZK'),
        ('ZKC'),
        ('ZKP'),
        ('ZRO'),
        ('ZRX'),
        ('币安人生')
    ) AS v(base)
),
excl AS (
    SELECT base FROM bn
    WHERE mod(from_big_endian_32(from_hex('000000' || substr(to_hex(sha256(to_utf8(base))), 1, 2))), 5) = 0
),
cp AS (
    /* 由 pump 程序在迁移交易里创建、池序号为 0 的 PumpSwap 池 */
    SELECT pool, min(evt_block_time) AS created_at, max(base_mint) AS mint, max(quote_mint) AS quote_mint,
           max(base_mint_decimals) AS bd, max(quote_mint_decimals) AS qd,
           min_by(evt_block_slot, evt_block_time) AS c_slot, min_by(evt_tx_index, evt_block_time) AS c_txi,
           min_by(evt_outer_instruction_index, evt_block_time) AS c_oix,
           min_by(COALESCE(evt_inner_instruction_index, -1), evt_block_time) AS c_iix,
           min_by(evt_tx_id, evt_block_time) AS c_tx
    FROM pumpdotfun_solana.pump_amm_evt_createpoolevent
    WHERE evt_block_date BETWEEN DATE '2026-01-13' AND DATE '2026-07-13'
      AND evt_outer_executing_account = '6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P'
      AND index = 0
    GROUP BY 1
),
cand AS (
    SELECT * FROM cp
    WHERE created_at >= TIMESTAMP '2026-07-13 00:00:00' - INTERVAL '180' DAY
      AND created_at < TIMESTAMP '2026-07-13 00:00:00' + INTERVAL '1' DAY
      AND created_at >= TIMESTAMP '2026-07-13 00:00:00' AND created_at < TIMESTAMP '2026-07-13 06:00:00'
),
cc AS (
    /* 曲线创建事件，全历史 */
    SELECT mint, min(evt_block_time) AS curve_created_at, min_by(symbol, evt_block_time) AS symbol
    FROM pumpdotfun_solana.pump_evt_createevent
    WHERE evt_block_date BETWEEN DATE '2024-01-01' AND DATE '2026-07-13'
      AND mint IN (SELECT mint FROM cand)
    GROUP BY 1
),
pools AS (
    SELECT c.*, s.curve_created_at, s.symbol
    FROM cand c
    JOIN cc s ON s.mint = c.mint
    WHERE NOT (s.curve_created_at >= TIMESTAMP '2026-06-15 00:00:00' AND s.curve_created_at < TIMESTAMP '2026-07-13 00:00:00')
      AND upper(trim(replace(s.symbol, '$', ''))) NOT IN (SELECT base FROM excl)
),
ev AS (
    SELECT pool, evt_block_time AS ts, evt_block_slot AS slot, evt_tx_index AS txi,
           evt_outer_instruction_index AS oix, COALESCE(evt_inner_instruction_index, -1) AS iix,
           'B' AS side, "user" AS usr,
           CAST(pool_quote_token_reserves AS DECIMAL(38,0)) AS q0,
           CAST(pool_base_token_reserves AS DECIMAL(38,0)) AS b0,
           CAST(quote_amount_in_with_lp_fee AS DECIMAL(38,0)) AS q_pool,
           CAST(base_amount_out AS DECIMAL(38,0)) AS b_amt,
           CAST(user_quote_amount_in AS DECIMAL(38,0)) AS q_user,
           CAST(lp_fee AS DECIMAL(38,0)) AS f_lp,
           CAST(protocol_fee AS DECIMAL(38,0)) AS f_pr,
           CAST(coin_creator_fee AS DECIMAL(38,0)) AS f_cr,
           CAST(NULL AS DECIMAL(38,0)) AS f_cb, CAST(NULL AS DECIMAL(38,0)) AS f_bb,
           CAST(NULL AS DECIMAL(38,0)) AS q_gross_out
    FROM pumpdotfun_solana.pump_amm_evt_buyevent
    WHERE evt_block_date BETWEEN DATE '2026-07-13' AND DATE '2026-07-21'
    UNION ALL
    SELECT pool, evt_block_time, evt_block_slot, evt_tx_index,
           evt_outer_instruction_index, COALESCE(evt_inner_instruction_index, -1),
           'S', "user",
           CAST(pool_quote_token_reserves AS DECIMAL(38,0)),
           CAST(pool_base_token_reserves AS DECIMAL(38,0)),
           CAST(quote_amount_out AS DECIMAL(38,0)) - COALESCE(CAST(lp_fee AS DECIMAL(38,0)), 0),
           CAST(base_amount_in AS DECIMAL(38,0)),
           CAST(user_quote_amount_out AS DECIMAL(38,0)),
           CAST(lp_fee AS DECIMAL(38,0)),
           CAST(protocol_fee AS DECIMAL(38,0)),
           CAST(coin_creator_fee AS DECIMAL(38,0)),
           CAST(cashback AS DECIMAL(38,0)),
           CAST(buyback_fee AS DECIMAL(38,0)),
           CAST(quote_amount_out AS DECIMAL(38,0))
    FROM pumpdotfun_solana.pump_amm_evt_sellevent
    WHERE evt_block_date BETWEEN DATE '2026-07-13' AND DATE '2026-07-21'
),
k AS (
    SELECT e.*, p.created_at, p.bd, p.qd,
           CASE WHEN e.side = 'B' THEN e.q0 + e.q_pool ELSE e.q0 - e.q_pool END AS q1,
           CASE WHEN e.side = 'B' THEN e.b0 - e.b_amt ELSE e.b0 + e.b_amt END AS b1,
           date_diff('millisecond', p.created_at, e.ts) AS age_ms,
           CAST(e.slot AS BIGINT) * 10000000000 + CAST(e.txi AS BIGINT) * 100000
             + CAST(e.oix AS BIGINT) * 1000 + CAST(e.iix AS BIGINT) AS ord,
           CASE WHEN e.txi >= 100000 OR e.oix >= 100 OR e.iix >= 1000 OR e.iix < 0 OR e.oix IS NULL
                THEN 1 ELSE 0 END AS ovf,
           /* 卖出反解 vq：ceil(a/d)＝(a＋d−1 − mod(a＋d−1, d))/d，全程整数 */
           CASE WHEN e.side = 'S' AND e.b_amt > 0 THEN
                (e.q_gross_out * (e.b0 + e.b_amt) + e.b_amt - 1
                 - mod(e.q_gross_out * (e.b0 + e.b_amt) + e.b_amt - 1, e.b_amt)) / e.b_amt - e.q0 END AS vlo,
           CASE WHEN e.side = 'S' AND e.b_amt > 0 THEN
                ((e.q_gross_out + 1) * (e.b0 + e.b_amt) + e.b_amt - 1
                 - mod((e.q_gross_out + 1) * (e.b0 + e.b_amt) + e.b_amt - 1, e.b_amt)) / e.b_amt - 1 - e.q0 END AS vhi
    FROM ev e
    JOIN pools p ON p.pool = e.pool
    WHERE e.ts >= p.created_at AND e.ts < p.created_at + INTERVAL '7' DAY
),
meta AS (
    SELECT mint, min_by(name, evt_block_time) AS name, min_by(uri, evt_block_time) AS uri,
           min_by(COALESCE(creator, "user"), evt_block_time) AS creator,
           min_by(is_mayhem_mode, evt_block_time) AS mayhem, min_by(is_cashback_enabled, evt_block_time) AS cashback,
           min_by(quote_mint, evt_block_time) AS curve_quote_mint
    FROM pumpdotfun_solana.pump_evt_createevent
    WHERE evt_block_date BETWEEN DATE '2024-01-01' AND DATE '2026-07-13'
      AND mint IN (SELECT mint FROM pools)
    GROUP BY 1
),
comp AS (
    SELECT mint, min(evt_block_time) AS completed_at
    FROM pumpdotfun_solana.pump_evt_completeevent
    WHERE evt_block_date BETWEEN DATE '2024-01-01' AND DATE '2026-07-13'
      AND mint IN (SELECT mint FROM pools)
    GROUP BY 1
),
sn AS (
    SELECT pool, count(*) AS n_7d, CAST(max(vlo) AS varchar) AS vq_lo_7d, CAST(min(vhi) AS varchar) AS vq_hi_7d,
           count(vlo) AS n_vq_obs_7d,
       max_by(slot, ord) FILTER (WHERE age_ms < 2000) AS a2_slot, max_by(txi, ord) FILTER (WHERE age_ms < 2000) AS a2_txi,
       max_by(oix, ord) FILTER (WHERE age_ms < 2000) AS a2_oix, max_by(iix, ord) FILTER (WHERE age_ms < 2000) AS a2_iix,
       CAST(max_by(q1, ord) FILTER (WHERE age_ms < 2000) AS varchar) AS a2_q1,
       CAST(max_by(b1, ord) FILTER (WHERE age_ms < 2000) AS varchar) AS a2_b1,
       to_unixtime(max_by(ts, ord) FILTER (WHERE age_ms < 2000)) AS a2_t,
       min_by(slot, ord) FILTER (WHERE age_ms >= 2000) AS b2_slot, min_by(txi, ord) FILTER (WHERE age_ms >= 2000) AS b2_txi,
       min_by(oix, ord) FILTER (WHERE age_ms >= 2000) AS b2_oix, min_by(iix, ord) FILTER (WHERE age_ms >= 2000) AS b2_iix,
       CAST(min_by(q0, ord) FILTER (WHERE age_ms >= 2000) AS varchar) AS b2_q0,
       CAST(min_by(b0, ord) FILTER (WHERE age_ms >= 2000) AS varchar) AS b2_b0,
       to_unixtime(min_by(ts, ord) FILTER (WHERE age_ms >= 2000)) AS b2_t,
       max_by(slot, ord) FILTER (WHERE age_ms < 10000) AS a10_slot, max_by(txi, ord) FILTER (WHERE age_ms < 10000) AS a10_txi,
       max_by(oix, ord) FILTER (WHERE age_ms < 10000) AS a10_oix, max_by(iix, ord) FILTER (WHERE age_ms < 10000) AS a10_iix,
       CAST(max_by(q1, ord) FILTER (WHERE age_ms < 10000) AS varchar) AS a10_q1,
       CAST(max_by(b1, ord) FILTER (WHERE age_ms < 10000) AS varchar) AS a10_b1,
       to_unixtime(max_by(ts, ord) FILTER (WHERE age_ms < 10000)) AS a10_t,
       min_by(slot, ord) FILTER (WHERE age_ms >= 10000) AS b10_slot, min_by(txi, ord) FILTER (WHERE age_ms >= 10000) AS b10_txi,
       min_by(oix, ord) FILTER (WHERE age_ms >= 10000) AS b10_oix, min_by(iix, ord) FILTER (WHERE age_ms >= 10000) AS b10_iix,
       CAST(min_by(q0, ord) FILTER (WHERE age_ms >= 10000) AS varchar) AS b10_q0,
       CAST(min_by(b0, ord) FILTER (WHERE age_ms >= 10000) AS varchar) AS b10_b0,
       to_unixtime(min_by(ts, ord) FILTER (WHERE age_ms >= 10000)) AS b10_t,
       max_by(slot, ord) FILTER (WHERE age_ms < 45000) AS a45_slot, max_by(txi, ord) FILTER (WHERE age_ms < 45000) AS a45_txi,
       max_by(oix, ord) FILTER (WHERE age_ms < 45000) AS a45_oix, max_by(iix, ord) FILTER (WHERE age_ms < 45000) AS a45_iix,
       CAST(max_by(q1, ord) FILTER (WHERE age_ms < 45000) AS varchar) AS a45_q1,
       CAST(max_by(b1, ord) FILTER (WHERE age_ms < 45000) AS varchar) AS a45_b1,
       to_unixtime(max_by(ts, ord) FILTER (WHERE age_ms < 45000)) AS a45_t,
       min_by(slot, ord) FILTER (WHERE age_ms >= 45000) AS b45_slot, min_by(txi, ord) FILTER (WHERE age_ms >= 45000) AS b45_txi,
       min_by(oix, ord) FILTER (WHERE age_ms >= 45000) AS b45_oix, min_by(iix, ord) FILTER (WHERE age_ms >= 45000) AS b45_iix,
       CAST(min_by(q0, ord) FILTER (WHERE age_ms >= 45000) AS varchar) AS b45_q0,
       CAST(min_by(b0, ord) FILTER (WHERE age_ms >= 45000) AS varchar) AS b45_b0,
       to_unixtime(min_by(ts, ord) FILTER (WHERE age_ms >= 45000)) AS b45_t,
       max_by(slot, ord) FILTER (WHERE age_ms < 60000) AS a60_slot, max_by(txi, ord) FILTER (WHERE age_ms < 60000) AS a60_txi,
       max_by(oix, ord) FILTER (WHERE age_ms < 60000) AS a60_oix, max_by(iix, ord) FILTER (WHERE age_ms < 60000) AS a60_iix,
       CAST(max_by(q1, ord) FILTER (WHERE age_ms < 60000) AS varchar) AS a60_q1,
       CAST(max_by(b1, ord) FILTER (WHERE age_ms < 60000) AS varchar) AS a60_b1,
       to_unixtime(max_by(ts, ord) FILTER (WHERE age_ms < 60000)) AS a60_t,
       min_by(slot, ord) FILTER (WHERE age_ms >= 60000) AS b60_slot, min_by(txi, ord) FILTER (WHERE age_ms >= 60000) AS b60_txi,
       min_by(oix, ord) FILTER (WHERE age_ms >= 60000) AS b60_oix, min_by(iix, ord) FILTER (WHERE age_ms >= 60000) AS b60_iix,
       CAST(min_by(q0, ord) FILTER (WHERE age_ms >= 60000) AS varchar) AS b60_q0,
       CAST(min_by(b0, ord) FILTER (WHERE age_ms >= 60000) AS varchar) AS b60_b0,
       to_unixtime(min_by(ts, ord) FILTER (WHERE age_ms >= 60000)) AS b60_t,
       max_by(slot, ord) FILTER (WHERE age_ms < 75000) AS a75_slot, max_by(txi, ord) FILTER (WHERE age_ms < 75000) AS a75_txi,
       max_by(oix, ord) FILTER (WHERE age_ms < 75000) AS a75_oix, max_by(iix, ord) FILTER (WHERE age_ms < 75000) AS a75_iix,
       CAST(max_by(q1, ord) FILTER (WHERE age_ms < 75000) AS varchar) AS a75_q1,
       CAST(max_by(b1, ord) FILTER (WHERE age_ms < 75000) AS varchar) AS a75_b1,
       to_unixtime(max_by(ts, ord) FILTER (WHERE age_ms < 75000)) AS a75_t,
       min_by(slot, ord) FILTER (WHERE age_ms >= 75000) AS b75_slot, min_by(txi, ord) FILTER (WHERE age_ms >= 75000) AS b75_txi,
       min_by(oix, ord) FILTER (WHERE age_ms >= 75000) AS b75_oix, min_by(iix, ord) FILTER (WHERE age_ms >= 75000) AS b75_iix,
       CAST(min_by(q0, ord) FILTER (WHERE age_ms >= 75000) AS varchar) AS b75_q0,
       CAST(min_by(b0, ord) FILTER (WHERE age_ms >= 75000) AS varchar) AS b75_b0,
       to_unixtime(min_by(ts, ord) FILTER (WHERE age_ms >= 75000)) AS b75_t,
       max_by(slot, ord) FILTER (WHERE age_ms < 900000) AS a900_slot, max_by(txi, ord) FILTER (WHERE age_ms < 900000) AS a900_txi,
       max_by(oix, ord) FILTER (WHERE age_ms < 900000) AS a900_oix, max_by(iix, ord) FILTER (WHERE age_ms < 900000) AS a900_iix,
       CAST(max_by(q1, ord) FILTER (WHERE age_ms < 900000) AS varchar) AS a900_q1,
       CAST(max_by(b1, ord) FILTER (WHERE age_ms < 900000) AS varchar) AS a900_b1,
       to_unixtime(max_by(ts, ord) FILTER (WHERE age_ms < 900000)) AS a900_t,
       min_by(slot, ord) FILTER (WHERE age_ms >= 900000) AS b900_slot, min_by(txi, ord) FILTER (WHERE age_ms >= 900000) AS b900_txi,
       min_by(oix, ord) FILTER (WHERE age_ms >= 900000) AS b900_oix, min_by(iix, ord) FILTER (WHERE age_ms >= 900000) AS b900_iix,
       CAST(min_by(q0, ord) FILTER (WHERE age_ms >= 900000) AS varchar) AS b900_q0,
       CAST(min_by(b0, ord) FILTER (WHERE age_ms >= 900000) AS varchar) AS b900_b0,
       to_unixtime(min_by(ts, ord) FILTER (WHERE age_ms >= 900000)) AS b900_t,
       max_by(slot, ord) FILTER (WHERE age_ms < 3600000) AS a3600_slot, max_by(txi, ord) FILTER (WHERE age_ms < 3600000) AS a3600_txi,
       max_by(oix, ord) FILTER (WHERE age_ms < 3600000) AS a3600_oix, max_by(iix, ord) FILTER (WHERE age_ms < 3600000) AS a3600_iix,
       CAST(max_by(q1, ord) FILTER (WHERE age_ms < 3600000) AS varchar) AS a3600_q1,
       CAST(max_by(b1, ord) FILTER (WHERE age_ms < 3600000) AS varchar) AS a3600_b1,
       to_unixtime(max_by(ts, ord) FILTER (WHERE age_ms < 3600000)) AS a3600_t,
       min_by(slot, ord) FILTER (WHERE age_ms >= 3600000) AS b3600_slot, min_by(txi, ord) FILTER (WHERE age_ms >= 3600000) AS b3600_txi,
       min_by(oix, ord) FILTER (WHERE age_ms >= 3600000) AS b3600_oix, min_by(iix, ord) FILTER (WHERE age_ms >= 3600000) AS b3600_iix,
       CAST(min_by(q0, ord) FILTER (WHERE age_ms >= 3600000) AS varchar) AS b3600_q0,
       CAST(min_by(b0, ord) FILTER (WHERE age_ms >= 3600000) AS varchar) AS b3600_b0,
       to_unixtime(min_by(ts, ord) FILTER (WHERE age_ms >= 3600000)) AS b3600_t,
       max_by(slot, ord) FILTER (WHERE age_ms < 86400000) AS a86400_slot, max_by(txi, ord) FILTER (WHERE age_ms < 86400000) AS a86400_txi,
       max_by(oix, ord) FILTER (WHERE age_ms < 86400000) AS a86400_oix, max_by(iix, ord) FILTER (WHERE age_ms < 86400000) AS a86400_iix,
       CAST(max_by(q1, ord) FILTER (WHERE age_ms < 86400000) AS varchar) AS a86400_q1,
       CAST(max_by(b1, ord) FILTER (WHERE age_ms < 86400000) AS varchar) AS a86400_b1,
       to_unixtime(max_by(ts, ord) FILTER (WHERE age_ms < 86400000)) AS a86400_t,
       min_by(slot, ord) FILTER (WHERE age_ms >= 86400000) AS b86400_slot, min_by(txi, ord) FILTER (WHERE age_ms >= 86400000) AS b86400_txi,
       min_by(oix, ord) FILTER (WHERE age_ms >= 86400000) AS b86400_oix, min_by(iix, ord) FILTER (WHERE age_ms >= 86400000) AS b86400_iix,
       CAST(min_by(q0, ord) FILTER (WHERE age_ms >= 86400000) AS varchar) AS b86400_q0,
       CAST(min_by(b0, ord) FILTER (WHERE age_ms >= 86400000) AS varchar) AS b86400_b0,
       to_unixtime(min_by(ts, ord) FILTER (WHERE age_ms >= 86400000)) AS b86400_t
    FROM k
    GROUP BY 1
)
SELECT p.pool, p.mint, p.quote_mint,
       CASE WHEN p.quote_mint = 'So11111111111111111111111111111111111111112' THEN 'SOL' WHEN p.quote_mint = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v' THEN 'USDC' ELSE 'OTHER' END AS quote_class,
       p.bd, p.qd, to_unixtime(p.created_at) AS created_t,
       p.c_slot, p.c_txi, p.c_oix, p.c_iix, p.c_tx,
       to_unixtime(p.curve_created_at) AS curve_created_t, to_unixtime(cm.completed_at) AS curve_completed_t,
       p.symbol, m.name, m.uri, m.creator, m.mayhem, m.cashback, m.curve_quote_mint,
       sn.n_7d, sn.vq_lo_7d, sn.vq_hi_7d, sn.n_vq_obs_7d, sn.a2_slot, sn.a2_txi, sn.a2_oix, sn.a2_iix, sn.a2_q1, sn.a2_b1, sn.a2_t, sn.b2_slot, sn.b2_txi, sn.b2_oix, sn.b2_iix, sn.b2_q0, sn.b2_b0, sn.b2_t, sn.a10_slot, sn.a10_txi, sn.a10_oix, sn.a10_iix, sn.a10_q1, sn.a10_b1, sn.a10_t, sn.b10_slot, sn.b10_txi, sn.b10_oix, sn.b10_iix, sn.b10_q0, sn.b10_b0, sn.b10_t, sn.a45_slot, sn.a45_txi, sn.a45_oix, sn.a45_iix, sn.a45_q1, sn.a45_b1, sn.a45_t, sn.b45_slot, sn.b45_txi, sn.b45_oix, sn.b45_iix, sn.b45_q0, sn.b45_b0, sn.b45_t, sn.a60_slot, sn.a60_txi, sn.a60_oix, sn.a60_iix, sn.a60_q1, sn.a60_b1, sn.a60_t, sn.b60_slot, sn.b60_txi, sn.b60_oix, sn.b60_iix, sn.b60_q0, sn.b60_b0, sn.b60_t, sn.a75_slot, sn.a75_txi, sn.a75_oix, sn.a75_iix, sn.a75_q1, sn.a75_b1, sn.a75_t, sn.b75_slot, sn.b75_txi, sn.b75_oix, sn.b75_iix, sn.b75_q0, sn.b75_b0, sn.b75_t, sn.a900_slot, sn.a900_txi, sn.a900_oix, sn.a900_iix, sn.a900_q1, sn.a900_b1, sn.a900_t, sn.b900_slot, sn.b900_txi, sn.b900_oix, sn.b900_iix, sn.b900_q0, sn.b900_b0, sn.b900_t, sn.a3600_slot, sn.a3600_txi, sn.a3600_oix, sn.a3600_iix, sn.a3600_q1, sn.a3600_b1, sn.a3600_t, sn.b3600_slot, sn.b3600_txi, sn.b3600_oix, sn.b3600_iix, sn.b3600_q0, sn.b3600_b0, sn.b3600_t, sn.a86400_slot, sn.a86400_txi, sn.a86400_oix, sn.a86400_iix, sn.a86400_q1, sn.a86400_b1, sn.a86400_t, sn.b86400_slot, sn.b86400_txi, sn.b86400_oix, sn.b86400_iix, sn.b86400_q0, sn.b86400_b0, sn.b86400_t
FROM pools p
LEFT JOIN meta m ON m.mint = p.mint
LEFT JOIN comp cm ON cm.mint = p.mint
LEFT JOIN sn ON sn.pool = p.pool
WHERE p.created_at >= TIMESTAMP '2026-07-13 00:00:00' AND p.created_at < TIMESTAMP '2026-07-13 00:00:00' + INTERVAL '1' DAY
