/* DQ-37 曲线阶段留存 v1（T，10-06，执行模型；批 1a-ii 待审）：曲线创建于 2026-07-27～2026-08-02 的全部 pump 新币；只存不分析；build_curve_sql_v1.py 生成 */
WITH
bn(base) AS (
    /* 币安现货全部 746 个基础资产名（Probe L 母表 u_trade，公开信息）；留出按 sha256(baseAsset) 首字节 mod 5 == 0 在下面计算 */
    SELECT base FROM (VALUES
        ('0G'),
        ('1000CAT'),
        ('1000CHEEMS'),
        ('1000SATS'),
        ('1INCH'),
        ('1MBABYDOGE'),
        ('2Z'),
        ('A'),
        ('A2Z'),
        ('AAOIB'),
        ('AAPLB'),
        ('AAVE'),
        ('ACA'),
        ('ACE'),
        ('ACH'),
        ('ACM'),
        ('ACT'),
        ('ACX'),
        ('ADA'),
        ('ADX'),
        ('AE'),
        ('AERGO'),
        ('AERO'),
        ('AEUR'),
        ('AEVO'),
        ('AGI'),
        ('AGIX'),
        ('AGLD'),
        ('AI'),
        ('AIGENSYN'),
        ('AION'),
        ('AIXBT'),
        ('AKRO'),
        ('ALCX'),
        ('ALGO'),
        ('ALICE'),
        ('ALLO'),
        ('ALPACA'),
        ('ALPHA'),
        ('ALPINE'),
        ('ALT'),
        ('AMATB'),
        ('AMB'),
        ('AMDB'),
        ('AMP'),
        ('AMZNB'),
        ('ANC'),
        ('ANIME'),
        ('ANKR'),
        ('ANT'),
        ('ANY'),
        ('APE'),
        ('API3'),
        ('APPC'),
        ('APT'),
        ('AR'),
        ('ARB'),
        ('ARDR'),
        ('ARK'),
        ('ARKM'),
        ('ARMB'),
        ('ARN'),
        ('ARPA'),
        ('ASR'),
        ('AST'),
        ('ASTER'),
        ('ASTR'),
        ('AT'),
        ('ATA'),
        ('ATM'),
        ('ATOM'),
        ('AUCTION'),
        ('AUD'),
        ('AUDIO'),
        ('AUTO'),
        ('AVA'),
        ('AVAX'),
        ('AVGOB'),
        ('AVNT'),
        ('AWE'),
        ('AXL'),
        ('AXS'),
        ('AXTIB'),
        ('BABAB'),
        ('BABY'),
        ('BADGER'),
        ('BAKE'),
        ('BAL'),
        ('BANANA'),
        ('BANANAS31'),
        ('BAND'),
        ('BANK'),
        ('BAR'),
        ('BARD'),
        ('BAT'),
        ('BB'),
        ('BCC'),
        ('BCD'),
        ('BCH'),
        ('BCHA'),
        ('BCHABC'),
        ('BCHSV'),
        ('BCN'),
        ('BCPT'),
        ('BDOT'),
        ('BEAM'),
        ('BEAMX'),
        ('BEAR'),
        ('BEB'),
        ('BEL'),
        ('BERA'),
        ('BETA'),
        ('BETH'),
        ('BFUSD'),
        ('BGBP'),
        ('BICO'),
        ('BIFI'),
        ('BIGTIME'),
        ('BIO'),
        ('BKRW'),
        ('BLUR'),
        ('BLZ'),
        ('BMT'),
        ('BNB'),
        ('BNSOL'),
        ('BNT'),
        ('BNX'),
        ('BOME'),
        ('BOND'),
        ('BONK'),
        ('BOT'),
        ('BQX'),
        ('BRD'),
        ('BREV'),
        ('BROCCOLI714'),
        ('BSW'),
        ('BTC'),
        ('BTCB'),
        ('BTCST'),
        ('BTG'),
        ('BTS'),
        ('BTT'),
        ('BTTC'),
        ('BULL'),
        ('BURGER'),
        ('BUSD'),
        ('BZRX'),
        ('C'),
        ('C98'),
        ('CAKE'),
        ('CATI'),
        ('CBRSB'),
        ('CDT'),
        ('CELO'),
        ('CELR'),
        ('CETUS'),
        ('CFG'),
        ('CFX'),
        ('CGPT'),
        ('CHAT'),
        ('CHESS'),
        ('CHIP'),
        ('CHR'),
        ('CHZ'),
        ('CITY'),
        ('CKB'),
        ('CLOAK'),
        ('CLV'),
        ('CMT'),
        ('CND'),
        ('COCOS'),
        ('COINB'),
        ('COMBO'),
        ('COMP'),
        ('COOKIE'),
        ('COS'),
        ('COTI'),
        ('COVER'),
        ('COW'),
        ('CRCLB'),
        ('CREAM'),
        ('CRV'),
        ('CRWVB'),
        ('CTK'),
        ('CTSI'),
        ('CTXC'),
        ('CVC'),
        ('CVP'),
        ('CVX'),
        ('CYBER'),
        ('D'),
        ('DAI'),
        ('DAR'),
        ('DASH'),
        ('DATA'),
        ('DCR'),
        ('DEGO'),
        ('DELLB'),
        ('DENT'),
        ('DEXE'),
        ('DF'),
        ('DGB'),
        ('DGD'),
        ('DIA'),
        ('DLT'),
        ('DNT'),
        ('DOCK'),
        ('DODO'),
        ('DOGE'),
        ('DOGS'),
        ('DOLO'),
        ('DOT'),
        ('DRAMB'),
        ('DREP'),
        ('DUSK'),
        ('DYDX'),
        ('DYM'),
        ('EASY'),
        ('EDEN'),
        ('EDO'),
        ('EDU'),
        ('EGLD'),
        ('EIGEN'),
        ('ELF'),
        ('ENA'),
        ('ENG'),
        ('ENJ'),
        ('ENS'),
        ('ENSO'),
        ('EOS'),
        ('EPIC'),
        ('EPS'),
        ('EPX'),
        ('ERA'),
        ('ERD'),
        ('ERN'),
        ('ESP'),
        ('ETC'),
        ('ETH'),
        ('ETHFI'),
        ('EUL'),
        ('EUR'),
        ('EURI'),
        ('EVX'),
        ('EWYB'),
        ('EZ'),
        ('F'),
        ('FARM'),
        ('FDUSD'),
        ('FET'),
        ('FF'),
        ('FIDA'),
        ('FIL'),
        ('FIO'),
        ('FIRO'),
        ('FIS'),
        ('FLM'),
        ('FLNCB'),
        ('FLOKI'),
        ('FLOW'),
        ('FLUX'),
        ('FOGO'),
        ('FOR'),
        ('FORM'),
        ('FORTH'),
        ('FRAX'),
        ('FRONT'),
        ('FTM'),
        ('FTT'),
        ('FUEL'),
        ('FUN'),
        ('FXS'),
        ('G'),
        ('GAL'),
        ('GALA'),
        ('GAS'),
        ('GBP'),
        ('GENIUS'),
        ('GFT'),
        ('GHST'),
        ('GIGGLE'),
        ('GLM'),
        ('GLMR'),
        ('GLWB'),
        ('GMT'),
        ('GMX'),
        ('GNO'),
        ('GNS'),
        ('GNT'),
        ('GO'),
        ('GOOGLB'),
        ('GPS'),
        ('GRAM'),
        ('GRS'),
        ('GRT'),
        ('GSB'),
        ('GTC'),
        ('GTO'),
        ('GUN'),
        ('GVT'),
        ('GXS'),
        ('HAEDAL'),
        ('HARD'),
        ('HBAR'),
        ('HC'),
        ('HEGIC'),
        ('HEI'),
        ('HEMI'),
        ('HFT'),
        ('HIFI'),
        ('HIGH'),
        ('HIVE'),
        ('HMSTR'),
        ('HNT'),
        ('HOLO'),
        ('HOME'),
        ('HOODB'),
        ('HOOK'),
        ('HOT'),
        ('HSR'),
        ('HUMA'),
        ('HYPER'),
        ('IBMB'),
        ('ICN'),
        ('ICP'),
        ('ICX'),
        ('ID'),
        ('IDEX'),
        ('ILV'),
        ('IMX'),
        ('INIT'),
        ('INJ'),
        ('INS'),
        ('INTCB'),
        ('INTWB'),
        ('IO'),
        ('IOST'),
        ('IOTA'),
        ('IOTX'),
        ('IQ'),
        ('IRIS'),
        ('JASMY'),
        ('JOE'),
        ('JST'),
        ('JTO'),
        ('JUP'),
        ('JUV'),
        ('KAIA'),
        ('KAITO'),
        ('KAT'),
        ('KAVA'),
        ('KDA'),
        ('KEEP'),
        ('KERNEL'),
        ('KEY'),
        ('KGST'),
        ('KITE'),
        ('KLAY'),
        ('KMD'),
        ('KMNO'),
        ('KNC'),
        ('KORUB'),
        ('KP3R'),
        ('KSM'),
        ('LA'),
        ('LAYER'),
        ('LAZIO'),
        ('LDO'),
        ('LEND'),
        ('LEVER'),
        ('LINA'),
        ('LINEA'),
        ('LINK'),
        ('LISTA'),
        ('LIT'),
        ('LITEB'),
        ('LOKA'),
        ('LOOM'),
        ('LPT'),
        ('LQTY'),
        ('LRC'),
        ('LSK'),
        ('LTC'),
        ('LTO'),
        ('LUMIA'),
        ('LUN'),
        ('LUNA'),
        ('LUNC'),
        ('MAGIC'),
        ('MANA'),
        ('MANTA'),
        ('MANTRA'),
        ('MASK'),
        ('MATIC'),
        ('MAV'),
        ('MBL'),
        ('MBOX'),
        ('MC'),
        ('MCO'),
        ('MDA'),
        ('MDT'),
        ('MDX'),
        ('ME'),
        ('MEGA'),
        ('MEME'),
        ('MET'),
        ('METAB'),
        ('METIS'),
        ('MFT'),
        ('MINA'),
        ('MIR'),
        ('MIRA'),
        ('MITH'),
        ('MITO'),
        ('MKR'),
        ('MLN'),
        ('MMT'),
        ('MOB'),
        ('MOD'),
        ('MORPHO'),
        ('MOVE'),
        ('MOVR'),
        ('MRVLB'),
        ('MSFTB'),
        ('MSTRB'),
        ('MTH'),
        ('MTL'),
        ('MUB'),
        ('MUBARAK'),
        ('MULTI'),
        ('MUUB'),
        ('MVLLB'),
        ('NANO'),
        ('NAS'),
        ('NAV'),
        ('NBISB'),
        ('NBS'),
        ('NBT'),
        ('NCASH'),
        ('NEAR'),
        ('NEBL'),
        ('NEIRO'),
        ('NEO'),
        ('NEWT'),
        ('NEXO'),
        ('NFP'),
        ('NIGHT'),
        ('NIL'),
        ('NKN'),
        ('NMR'),
        ('NOKB'),
        ('NOM'),
        ('NOT'),
        ('NPXS'),
        ('NTRN'),
        ('NU'),
        ('NULS'),
        ('NVDAB'),
        ('NXPC'),
        ('NXS'),
        ('OAX'),
        ('OCEAN'),
        ('OG'),
        ('OGN'),
        ('OM'),
        ('OMG'),
        ('OMNI'),
        ('ONDO'),
        ('ONE'),
        ('ONG'),
        ('ONT'),
        ('OOKI'),
        ('OP'),
        ('OPEN'),
        ('OPG'),
        ('OPN'),
        ('ORCA'),
        ('ORCLB'),
        ('ORDI'),
        ('ORN'),
        ('OSMO'),
        ('OST'),
        ('OXT'),
        ('PARTI'),
        ('PAX'),
        ('PAXG'),
        ('PDA'),
        ('PENDLE'),
        ('PENGU'),
        ('PEOPLE'),
        ('PEPE'),
        ('PERL'),
        ('PERP'),
        ('PHA'),
        ('PHB'),
        ('PHX'),
        ('PIVX'),
        ('PIXEL'),
        ('PLA'),
        ('PLTRB'),
        ('PLUME'),
        ('PNT'),
        ('PNUT'),
        ('POA'),
        ('POE'),
        ('POL'),
        ('POLS'),
        ('POLY'),
        ('POLYX'),
        ('POND'),
        ('PORTAL'),
        ('PORTO'),
        ('POWR'),
        ('PPT'),
        ('PROM'),
        ('PROS'),
        ('PROVE'),
        ('PSG'),
        ('PUMP'),
        ('PUNDIX'),
        ('PYPLB'),
        ('PYR'),
        ('PYTH'),
        ('QCOMB'),
        ('QI'),
        ('QKC'),
        ('QLC'),
        ('QNT'),
        ('QNTB'),
        ('QQQB'),
        ('QSP'),
        ('QTUM'),
        ('QUICK'),
        ('RAD'),
        ('RAMP'),
        ('RARE'),
        ('RAY'),
        ('RCN'),
        ('RDN'),
        ('RDNT'),
        ('RE'),
        ('RED'),
        ('REEF'),
        ('REI'),
        ('REN'),
        ('RENBTC'),
        ('RENDER'),
        ('REP'),
        ('REQ'),
        ('RESOLV'),
        ('REZ'),
        ('RGT'),
        ('RIF'),
        ('RKLBB'),
        ('RLC'),
        ('RLUSD'),
        ('RNDR'),
        ('ROBO'),
        ('RONIN'),
        ('ROSE'),
        ('RPL'),
        ('RPX'),
        ('RSR'),
        ('RUNE'),
        ('RVN'),
        ('S'),
        ('SAGA'),
        ('SAHARA'),
        ('SALT'),
        ('SAND'),
        ('SANTOS'),
        ('SAPIEN'),
        ('SC'),
        ('SCR'),
        ('SCRT'),
        ('SEI'),
        ('SENT'),
        ('SFP'),
        ('SHELL'),
        ('SHIB'),
        ('SIGN'),
        ('SKHYB'),
        ('SKL'),
        ('SKY'),
        ('SLF'),
        ('SLP'),
        ('SMHB'),
        ('SNDKB'),
        ('SNGLS'),
        ('SNM'),
        ('SNT'),
        ('SNX'),
        ('SNXXB'),
        ('SOL'),
        ('SOLV'),
        ('SOMI'),
        ('SOPH'),
        ('SOXLB'),
        ('SOXSB'),
        ('SPARTA'),
        ('SPCXB'),
        ('SPELL'),
        ('SPK'),
        ('SPYB'),
        ('SRM'),
        ('SSV'),
        ('STEEM'),
        ('STG'),
        ('STMX'),
        ('STO'),
        ('STORJ'),
        ('STORM'),
        ('STPT'),
        ('STRAT'),
        ('STRAX'),
        ('STRK'),
        ('STX'),
        ('SUB'),
        ('SUI'),
        ('SUN'),
        ('SUPER'),
        ('SUSD'),
        ('SUSHI'),
        ('SWRV'),
        ('SXP'),
        ('SXT'),
        ('SYN'),
        ('SYRUP'),
        ('SYS'),
        ('T'),
        ('TAO'),
        ('TCT'),
        ('TFUEL'),
        ('THE'),
        ('THETA'),
        ('TIA'),
        ('TKO'),
        ('TLM'),
        ('TNB'),
        ('TNSR'),
        ('TNT'),
        ('TOMO'),
        ('TON'),
        ('TORN'),
        ('TOWNS'),
        ('TQQQB'),
        ('TRB'),
        ('TREE'),
        ('TRIBE'),
        ('TRIG'),
        ('TROY'),
        ('TRU'),
        ('TRUMP'),
        ('TRX'),
        ('TSLAB'),
        ('TSMB'),
        ('TST'),
        ('TURBO'),
        ('TURTLE'),
        ('TUSD'),
        ('TUSDB'),
        ('TUT'),
        ('TVK'),
        ('TWT'),
        ('U'),
        ('UFT'),
        ('UMA'),
        ('UNFI'),
        ('UNI'),
        ('USD1'),
        ('USDC'),
        ('USDE'),
        ('USDP'),
        ('USDS'),
        ('USDSB'),
        ('USDT'),
        ('UST'),
        ('USTC'),
        ('USUAL'),
        ('UTK'),
        ('VANA'),
        ('VANRY'),
        ('VELODROME'),
        ('VEN'),
        ('VET'),
        ('VGX'),
        ('VIA'),
        ('VIB'),
        ('VIBE'),
        ('VIC'),
        ('VIDT'),
        ('VIRTUAL'),
        ('VITE'),
        ('VOXEL'),
        ('VTHO'),
        ('W'),
        ('WABI'),
        ('WAL'),
        ('WAN'),
        ('WAVES'),
        ('WAXP'),
        ('WBETH'),
        ('WBTC'),
        ('WCT'),
        ('WDCB'),
        ('WIF'),
        ('WIN'),
        ('WING'),
        ('WINGS'),
        ('WLD'),
        ('WLFI'),
        ('WNXM'),
        ('WOO'),
        ('WPR'),
        ('WRX'),
        ('WTC'),
        ('XAI'),
        ('XAUT'),
        ('XEC'),
        ('XEM'),
        ('XLM'),
        ('XMR'),
        ('XNO'),
        ('XPL'),
        ('XRP'),
        ('XTZ'),
        ('XUSD'),
        ('XVG'),
        ('XVS'),
        ('XZC'),
        ('YB'),
        ('YFI'),
        ('YFII'),
        ('YGG'),
        ('YOYO'),
        ('ZAMA'),
        ('ZBT'),
        ('ZEC'),
        ('ZEN'),
        ('ZIL'),
        ('ZK'),
        ('ZKC'),
        ('ZKP'),
        ('ZRO'),
        ('ZRX'),
        ('币安人生')
    ) AS v(base)
),
excl AS (
    SELECT base FROM bn
    WHERE mod(from_big_endian_32(from_hex('000000' || substr(to_hex(sha256(to_utf8(base))), 1, 2))), 5) = 0
),
c0 AS (
    SELECT mint, min(evt_block_time) AS created_at, count(*) AS n_create,
           min_by(name, evt_block_time) AS name, min_by(symbol, evt_block_time) AS symbol,
           min_by(uri, evt_block_time) AS uri, min_by(COALESCE(creator, "user"), evt_block_time) AS creator,
           min_by("user", evt_block_time) AS create_user, min_by(evt_tx_signer, evt_block_time) AS create_signer,
           min_by(evt_tx_id, evt_block_time) AS create_tx, min_by(evt_block_slot, evt_block_time) AS create_slot,
           min_by(token_program, evt_block_time) AS token_program,
           min_by(is_mayhem_mode, evt_block_time) AS is_mayhem_mode,
           min_by(is_cashback_enabled, evt_block_time) AS is_cashback_enabled,
           min_by(quote_mint, evt_block_time) AS quote_mint,
           min_by(CAST(virtual_sol_reserves AS DECIMAL(38,0)), evt_block_time) AS vsr0,
           min_by(CAST(virtual_token_reserves AS DECIMAL(38,0)), evt_block_time) AS vtr0,
           min_by(CAST(real_token_reserves AS DECIMAL(38,0)), evt_block_time) AS rtr0,
           min_by(CAST(virtual_quote_reserves AS DECIMAL(38,0)), evt_block_time) AS vqr0,
           min_by(CAST(token_total_supply AS DECIMAL(38,0)), evt_block_time) AS supply
    FROM pumpdotfun_solana.pump_evt_createevent
    WHERE evt_block_date BETWEEN DATE '2026-07-27' AND DATE '2026-08-02'
    GROUP BY 1
),
c1 AS (
    SELECT c0.*,
           CASE WHEN symbol IS NULL OR trim(replace(symbol, '$', '')) = '' THEN 'no_symbol'
                WHEN upper(trim(replace(symbol, '$', ''))) IN (SELECT base FROM excl) THEN 'holdout_name'
                ELSE 'in' END AS pop_class
    FROM c0
    WHERE created_at >= TIMESTAMP '2026-07-27 00:00:00' AND created_at < TIMESTAMP '2026-08-02 00:00:00' + INTERVAL '1' DAY
      AND created_at >= TIMESTAMP '2026-07-27 00:00:00' AND created_at < TIMESTAMP '2026-07-27 01:00:00'
),
coins AS (SELECT * FROM c1 WHERE pop_class = 'in'),
tr AS (
    SELECT t.mint, k.created_at, t.evt_block_time AS ts,
           CAST(t.evt_block_slot AS BIGINT) * 10000000000 + CAST(t.evt_tx_index AS BIGINT) * 100000
             + CAST(t.evt_outer_instruction_index AS BIGINT) * 1000 + COALESCE(t.evt_inner_instruction_index, 0) AS ord,
           t.evt_block_slot AS slot, t.evt_tx_index AS txi, t.evt_outer_instruction_index AS oix,
           t.evt_inner_instruction_index AS iix, t.evt_tx_id AS tx_id, t.evt_tx_signer AS signer,
           CAST(t."user" AS varchar) AS usr, COALESCE(t.is_buy, t.isBuy) AS is_buy,
           CAST(COALESCE(t.sol_amount, t.solAmount) AS DECIMAL(38,0)) AS sol,
           CAST(COALESCE(t.token_amount, t.tokenAmount) AS DECIMAL(38,0)) AS tok,
           CAST(COALESCE(t.virtual_sol_reserves, t.virtualSolReserves) AS DECIMAL(38,0)) AS vsr,
           CAST(COALESCE(t.virtual_token_reserves, t.virtualTokenReserves) AS DECIMAL(38,0)) AS vtr,
           CAST(t.real_sol_reserves AS DECIMAL(38,0)) AS rsr, CAST(t.real_token_reserves AS DECIMAL(38,0)) AS rtr,
           CAST(t.fee AS DECIMAL(38,0)) AS f_pr, CAST(t.creator_fee AS DECIMAL(38,0)) AS f_cr,
           CAST(t.cashback AS DECIMAL(38,0)) AS f_cb, CAST(t.buyback_fee AS DECIMAL(38,0)) AS f_bb,
           CAST(t.fee_basis_points AS DECIMAL(38,0)) AS fee_bps, CAST(t.creator_fee_basis_points AS DECIMAL(38,0)) AS cfee_bps,
           t.mayhem_mode AS mayhem, t.ix_name, t.track_volume, t.quote_mint AS q_mint,
           CAST(t.quote_amount AS DECIMAL(38,0)) AS q_amt
    FROM pumpdotfun_solana.pump_evt_tradeevent t
    JOIN coins k ON k.mint = t.mint
    WHERE t.evt_block_date BETWEEN DATE '2026-07-27' AND DATE '2026-08-09'
      AND t.evt_block_time >= k.created_at AND t.evt_block_time < k.created_at + INTERVAL '7' DAY
      AND t.evt_block_time < TIMESTAMP '2026-10-05 00:00:00'
),
r AS (
    SELECT tr.*, row_number() OVER (PARTITION BY mint ORDER BY ord) AS rn,
           count(*) OVER (PARTITION BY mint, ord) AS n_dup_key
    FROM tr
),
ic AS (
    SELECT tx_id, outer_instruction_index AS oix, inner_instruction_index AS iix, block_slot AS slot, tx_index AS txi, data AS b
    FROM solana.instruction_calls
    WHERE block_date BETWEEN DATE '2026-07-27' AND DATE '2026-08-09'
      AND executing_account = '6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P' AND is_inner = true AND tx_success = true
      AND bytearray_substring(data, 1, 8) = 0xe445a52e51cb9a1d
      AND bytearray_substring(data, 9, 8) = 0xbddb7fd34ee661ee
      AND tx_id IN (SELECT tx_id FROM tr)
),
icn AS (
    SELECT ic.*, CAST(bytearray_to_bigint(reverse(bytearray_substring(b, 267, 4))) AS INTEGER) AS n FROM ic
),
ick AS (
    SELECT icn.*,
           CASE WHEN length(b) >= 307 + n THEN CAST(bytearray_to_bigint(reverse(bytearray_substring(b, 304 + n, 4))) AS INTEGER) END AS k
    FROM icn
),
icb AS (SELECT ick.*, 308 + n + 34 * k AS base FROM ick),
rv AS (
    SELECT tx_id, oix, iix,
           to_base58(bytearray_substring(b, 17, 32)) AS r_mint,
           (CAST(bytearray_to_bigint(reverse(bytearray_substring(b, 49, 8))) AS DECIMAL(38,0)) + CASE WHEN bytearray_to_bigint(reverse(bytearray_substring(b, 49, 8))) < 0 THEN DECIMAL '18446744073709551616' ELSE DECIMAL '0' END) AS r_sol,
           CASE WHEN base IS NOT NULL AND length(b) >= base + 39 THEN (CAST(bytearray_to_bigint(reverse(bytearray_substring(b, base + 32, 8))) AS DECIMAL(38,0)) + CASE WHEN bytearray_to_bigint(reverse(bytearray_substring(b, base + 32, 8))) < 0 THEN DECIMAL '18446744073709551616' ELSE DECIMAL '0' END) END AS r_qa,
           CASE WHEN base IS NOT NULL AND length(b) >= base + 55 THEN (CAST(bytearray_to_bigint(reverse(bytearray_substring(b, base + 40, 8))) AS DECIMAL(38,0)) + CASE WHEN bytearray_to_bigint(reverse(bytearray_substring(b, base + 40, 8))) < 0 THEN DECIMAL '18446744073709551616' ELSE DECIMAL '0' END) END AS vqr,
           CASE WHEN base IS NOT NULL AND length(b) >= base + 55 THEN (CAST(bytearray_to_bigint(reverse(bytearray_substring(b, base + 48, 8))) AS DECIMAL(38,0)) + CASE WHEN bytearray_to_bigint(reverse(bytearray_substring(b, base + 48, 8))) < 0 THEN DECIMAL '18446744073709551616' ELSE DECIMAL '0' END) END AS rqr,
           CASE WHEN base IS NOT NULL AND length(b) >= base + 71 THEN (CAST(bytearray_to_bigint(reverse(bytearray_substring(b, base + 56, 8))) AS DECIMAL(38,0)) + CASE WHEN bytearray_to_bigint(reverse(bytearray_substring(b, base + 56, 8))) < 0 THEN DECIMAL '18446744073709551616' ELSE DECIMAL '0' END) END AS hr_bps,
           CASE WHEN base IS NOT NULL AND length(b) >= base + 71 THEN (CAST(bytearray_to_bigint(reverse(bytearray_substring(b, base + 64, 8))) AS DECIMAL(38,0)) + CASE WHEN bytearray_to_bigint(reverse(bytearray_substring(b, base + 64, 8))) < 0 THEN DECIMAL '18446744073709551616' ELSE DECIMAL '0' END) END AS hr,
           length(b) AS blen
    FROM icb
)
SELECT 'solana' AS chain, r.mint, to_unixtime(r.created_at) AS created_t, r.rn, to_unixtime(r.ts) AS ts,
       CAST(r.ord AS varchar) AS ord, r.slot, r.txi, r.oix, r.iix, r.n_dup_key, r.tx_id, r.signer, r.usr, r.is_buy,
       CAST(r.sol AS varchar) AS sol, CAST(r.tok AS varchar) AS tok,
       CAST(r.vsr AS varchar) AS vsr, CAST(r.vtr AS varchar) AS vtr, CAST(r.rsr AS varchar) AS rsr, CAST(r.rtr AS varchar) AS rtr,
       CAST(r.f_pr AS varchar) AS f_pr, CAST(r.f_cr AS varchar) AS f_cr, CAST(r.f_cb AS varchar) AS f_cb, CAST(r.f_bb AS varchar) AS f_bb,
       CAST(r.fee_bps AS varchar) AS fee_bps, CAST(r.cfee_bps AS varchar) AS cfee_bps,
       r.mayhem, r.ix_name, r.track_volume, r.q_mint, CAST(r.q_amt AS varchar) AS q_amt,
       CAST(rv.vqr AS varchar) AS vqr, CAST(rv.rqr AS varchar) AS rqr, CAST(rv.hr_bps AS varchar) AS hr_bps, CAST(rv.hr AS varchar) AS hr,
       CASE WHEN r.ts < TIMESTAMP '2026-07-27 00:00:00' THEN 'layout0' WHEN rv.tx_id IS NULL THEN 'missing'
            WHEN rv.vqr IS NOT NULL THEN 'raw' ELSE 'layout0' END AS q_src,
       CASE WHEN rv.tx_id IS NULL THEN NULL
            WHEN rv.r_mint = r.mint AND rv.r_sol = r.sol AND (rv.r_qa IS NULL OR r.q_amt IS NULL OR rv.r_qa = r.q_amt) THEN 1 ELSE 0 END AS xchk_ok,
       rv.blen
FROM r
LEFT JOIN rv ON rv.tx_id = r.tx_id AND rv.oix = r.oix AND rv.iix IS NOT DISTINCT FROM r.iix
WHERE r.rn <= 100
